
import type { Product, Promotion, EarningPeriod, Transaction, Order, Category } from './types';
import { 
  Carrot, 
  Milk, 
  ShoppingCart, 
  Coffee,
  Drumstick 
} from 'lucide-react';

export const CATEGORIES: Category[] = [
  {
    id: 'cat-1',
    name_en: 'Vegetables & Fruits',
    name_hi: 'Sabji aur Fal',
    slug: 'vegetables-fruits',
    icon: Carrot,
    description: 'Fresh vegetables and fruits from local farms',
    description_hi: 'Local farms se fresh vegetables aur fruits',
    image: 'https://picsum.photos/seed/cat-1/400/400',
    tags: ['fresh', 'organic', 'seasonal', 'local'],
    is_active: true,
    display_order: 1,
    parent_id: null,
    subCategories: [
      { name: 'Fresh Vegetables', slug: 'fresh-vegetables' },
      { name: 'Fresh Fruits', slug: 'fresh-fruits' },
      { name: 'Organic', slug: 'organic' },
      { name: 'Exotic Fruits', slug: 'exotic-fruits' },
      { name: 'Leafy Greens', slug: 'leafy-greens' },
    ],
    featured: true,
    meta_title: 'Fresh Vegetables and Fruits Online',
    meta_description: 'Buy fresh vegetables and fruits online with quick delivery'
  },
  {
    id: 'cat-2',
    name_en: 'Dairy & Bakery', 
    name_hi: 'Doodh aur Bread',
    slug: 'dairy-bakery',
    icon: Milk,
    description: 'Fresh dairy products and bakery items',
    description_hi: 'Fresh dairy products aur bakery items',
    image: 'https://picsum.photos/seed/cat-2/400/400',
    tags: ['fresh', 'daily', 'baked', 'milk'],
    is_active: true,
    display_order: 2,
    parent_id: null,
    subCategories: [
      { name: 'Milk', slug: 'milk' },
      { name: 'Curd & Yogurt', slug: 'curd-yogurt' },
      { name: 'Cheese', slug: 'cheese' },
      { name: 'Butter', slug: 'butter' },
      { name: 'Bread', slug: 'bread' },
      { name: 'Cakes', slug: 'cakes' },
      { name: 'Frozen', slug: 'frozen' },
    ],
    featured: true,
    meta_title: 'Dairy and Bakery Products Online',
    meta_description: 'Fresh dairy and bakery products delivered to your doorstep'
  },
  {
    id: 'cat-3',
    name_en: 'Snacks & Beverages',
    name_hi: 'Nashte aur Peene ki Cheezein',
    slug: 'snacks-beverages', 
    icon: Coffee,
    description: 'Snacks and beverages for quick refreshment',
    description_hi: 'Quick refreshment ke liye snacks aur beverages',
    image: 'https://picsum.photos/seed/cat-3/400/400',
    tags: ['snacks', 'beverages', 'drinks', 'refreshment'],
    is_active: true,
    display_order: 4,
    parent_id: null,
    subCategories: [
      { name: 'Cookies', slug: 'cookies' },
      { name: 'Namkeen', slug: 'namkeen' },
      { name: 'Chips', slug: 'chips' },
      { name: 'Cold Drinks', slug: 'cold-drinks' },
      { name: 'Juices', slug: 'juices' },
      { name: 'Water', slug: 'water' },
      { name: 'Tea & Coffee', slug: 'tea-coffee' },
    ],
    featured: true,
    meta_title: 'Snacks and Beverages Online',
    meta_description: 'Wide range of snacks and beverages available'
  },
  {
    id: 'cat-4',
    name_en: 'Staples & Grocery',
    name_hi: 'Kirane ka Saman', 
    slug: 'staples-grocery',
    icon: ShoppingCart,
    description: 'Daily essentials and grocery items',
    description_hi: 'Daily essentials aur grocery items',
    image: 'https://picsum.photos/seed/cat-4/400/400',
    tags: ['essentials', 'grocery', 'staples', 'kitchen'],
    is_active: true,
    display_order: 3,
    parent_id: null,
    subCategories: [
      { name: 'Pulses', slug: 'pulses' },
      { name: 'Flour & Atta', slug: 'flour-atta' },
      { name: 'Rice & Grains', slug: 'rice-grains' },
      { name: 'Spices', slug: 'spices' },
      { name: 'Oil & Ghee', slug: 'oil-ghee' },
      { name: 'Sugar & Salt', slug: 'sugar-salt' },
    ],
    featured: true,
    meta_title: 'Staples and Grocery Items Online',
    meta_description: 'All your kitchen essentials in one place'
  },
  {
    id: 'cat-5',
    name_en: 'Non-Veg',
    name_hi: 'Ande aur Chicken',
    slug: 'non-veg',
    icon: Drumstick,
    description: 'Fresh non-vegetarian products',
    description_hi: 'Fresh non-vegetarian products',
    image: 'https://picsum.photos/seed/cat-5/400/400',
    tags: ['fresh', 'meat', 'chicken', 'fish', 'mutton'],
    is_active: true,
    display_order: 5,
    parent_id: null,
    subCategories: [
      { name: 'Eggs', slug: 'eggs' },
      { name: 'Chicken', slug: 'chicken' },
      { name: 'Mutton', slug: 'mutton' },
      { name: 'Fish', slug: 'fish' },
      { name: 'Seafood', slug: 'seafood' },
      { name: 'Frozen Meat', slug: 'frozen-meat' },
    ],
    featured: true,
    meta_title: 'Fresh Non-Veg Products Online',
    meta_description: 'Quality non-vegetarian products with quick delivery'
  }
];


export const products: Product[] = [
  {
    id: '1',
    name_en: 'Organic Avocados',
    description: 'Creamy and delicious organic Hass avocados, perfect for toast or guacamole.',
    price: 375,
    mrp: 400,
    category: 'Fruits',
    image: 'https://picsum.photos/seed/avocado/400/400',
    imageHint: 'avocado fruit',
    stock_qty: 50,
    brand: 'Freshoz',
  },
  {
    id: '2',
    name_en: 'Fresh Strawberries',
    description: 'Sweet, juicy, and locally grown strawberries. A seasonal favorite.',
    price: 260,
    mrp: 300,
    category: 'Fruits',
    image: 'https://picsum.photos/seed/strawberry/400/400',
    imageHint: 'strawberry fruit',
    stock_qty: 80,
    brand: 'Local Farms',
  },
  {
    id: '3',
    name_en: 'Heirloom Tomatoes',
    description: 'Flavorful and colorful heirloom tomatoes, straight from the farm.',
    price: 390,
    mrp: 420,
    category: 'Vegetables',
    image: 'https://picsum.photos/seed/tomato/400/400',
    imageHint: 'tomato vegetable',
    stock_qty: 40,
    brand: 'Farm Fresh',
  },
  {
    id: '4',
    name_en: 'Crisp Romain Lettuce',
    description: 'Fresh and crisp heads of Romaine lettuce, ideal for salads and sandwiches.',
    price: 210,
    mrp: 230,
    category: 'Vegetables',
    image: 'https://picsum.photos/seed/lettuce/400/400',
    imageHint: 'lettuce vegetable',
    stock_qty: 60,
    brand: 'Green Fields',
  },
  {
    id: '5',
    name_en: 'Artisanal Sourdough',
    description: 'A rustic loaf of naturally leavened sourdough, baked fresh daily.',
    price: 450,
    mrp: 500,
    category: 'Bakery',
    image: 'https://picsum.photos/seed/bread/400/400',
    imageHint: 'bread loaf',
    stock_qty: 30,
    brand: 'The Bakehouse',
  },
  {
    id: '6',
    name_en: 'Free-Range Eggs',
    description: 'One dozen large brown eggs from pasture-raised, free-range chickens.',
    price: 560,
    mrp: 600,
    category: 'Dairy',
    image: 'https://picsum.photos/seed/eggs/400/400',
    imageHint: 'eggs carton',
    stock_qty: 100,
    brand: 'Happy Hens',
  },
  {
    id: '7',
    name_en: 'Organic Milk',
    description: 'A half-gallon of fresh, organic whole milk. Rich and wholesome.',
    price: 320,
    mrp: 350,
    category: 'Dairy',
    image: 'https://picsum.photos/seed/milk/400/400',
    imageHint: 'milk bottle',
    stock_qty: 75,
    brand: 'Pure Dairy',
  },
  {
    id: '8',
    name_en: 'Cold-Pressed Juice',
    description: 'A refreshing blend of apple, kale, and ginger cold-pressed juice.',
    price: 410,
    mrp: 450,
    category: 'Beverages',
    image: 'https://picsum.photos/seed/juice/400/400',
    imageHint: 'juice bottle',
    stock_qty: 45,
    brand: 'Juice Up',
  },
  {
    id: '9',
    name_en: 'Sweet Oranges',
    description: 'Juicy and sweet Navel oranges, packed with Vitamin C.',
    price: 240,
    mrp: 260,
    category: 'Fruits',
    image: 'https://picsum.photos/seed/oranges/400/400',
    imageHint: 'oranges fruit',
    stock_qty: 90,
    brand: 'Citrus Grove',
  },
  {
    id: '10',
    name_en: 'Fresh Broccoli',
    description: 'Crisp and tender broccoli crowns, perfect for steaming or roasting.',
    price: 225,
    mrp: 250,
    category: 'Vegetables',
    image: 'https://picsum.photos/seed/broccoli/400/400',
    imageHint: 'broccoli vegetable',
    stock_qty: 55,
    brand: 'Green Giant',
  },
];

export const promotions: Promotion[] = [
  {
    id: 'promo-1',
    title: 'Weekly Special',
    description: 'Get 20% off all organic berries!',
    imageUrl: 'https://picsum.photos/seed/promo-berries/600/400',
    imageHint: 'berries fruit',
  },
  {
    id: 'promo-2',
    title: 'Bakery Bonanza',
    description: 'Buy one, get one free on all sourdough bread.',
    imageUrl: 'https://picsum.photos/seed/promo-bread/600/400',
    imageHint: 'fresh bread',
  },
  {
    id: 'promo-3',
    title: 'Veggie Power',
    description: 'Save ₹400 when you spend ₹2000 on fresh vegetables.',
    imageUrl: 'https://picsum.photos/seed/promo-veggies/600/400',
    imageHint: 'vegetables variety',
  },
];

export const earningsData: EarningPeriod[] = [
  { day: 'Mon', earnings: 120 },
  { day: 'Tue', earnings: 150 },
  { day: 'Wed', earnings: 170 },
  { day: 'Thu', earnings: 130 },
  { day: 'Fri', earnings: 210 },
  { day: 'Sat', earnings: 250 },
  { day: 'Sun', earnings: 180 },
];

export const transactions: Transaction[] = [
  { id: '#3210', status: 'Completed', amount: 25.0, date: '2023-10-26' },
  { id: '#3209', status: 'Completed', amount: 15.0, date: '2023-10-26' },
  { id: '#3208', status: 'Completed', amount: 42.5, date: '2023-10-25' },
  { id: '#3207', status: 'Pending', amount: 10.0, date: '2023-10-25' },
  { id: '#3206', status: 'Completed', amount: 35.75, date: '2023-10-24' },
];

export const orders: Partial<Order>[] = [
    {
      id: 'FZ-12345',
      userId: 'user1',
      items: [
        { productId: '1', name: 'Organic Avocados', price: 375, quantity: 2 },
        { productId: '5', name: 'Artisanal Sourdough', price: 450, quantity: 1 },
      ],
      totalAmount: 1200,
      status: 'out for delivery',
      createdAt: new Date('2023-10-27T10:00:00Z'),
      updatedAt: new Date('2023-10-27T11:00:00Z'),
    },
     {
      id: 'FZ-67890',
      userId: 'user1',
      items: [
        { productId: '2', name: 'Fresh Strawberries', price: 260, quantity: 1 },
      ],
      totalAmount: 260,
      status: 'delivered',
      createdAt: new Date('2023-10-25T14:30:00Z'),
      updatedAt: new Date('2023-10-25T15:15:00Z'),
    }
  ];


