
import type { Product, Promotion, EarningPeriod, Transaction, Order } from './types';

export const products: Product[] = [
  {
    id: '1',
    name_en: 'Organic Avocados',
    description: 'Creamy and delicious organic Hass avocados, perfect for toast or guacamole.',
    price: 375,
    mrp: 400,
    category: 'Fruits',
    image: 'https://picsum.photos/seed/avocado/400/400',
    imageHint: 'avocado fruit',
    stock_qty: 50,
    brand: 'Freshoz',
  },
  {
    id: '2',
    name_en: 'Fresh Strawberries',
    description: 'Sweet, juicy, and locally grown strawberries. A seasonal favorite.',
    price: 260,
    mrp: 300,
    category: 'Fruits',
    image: 'https://picsum.photos/seed/strawberry/400/400',
    imageHint: 'strawberry fruit',
    stock_qty: 80,
    brand: 'Local Farms',
  },
  {
    id: '3',
    name_en: 'Heirloom Tomatoes',
    description: 'Flavorful and colorful heirloom tomatoes, straight from the farm.',
    price: 390,
    mrp: 420,
    category: 'Vegetables',
    image: 'https://picsum.photos/seed/tomato/400/400',
    imageHint: 'tomato vegetable',
    stock_qty: 40,
    brand: 'Farm Fresh',
  },
  {
    id: '4',
    name_en: 'Crisp Romain Lettuce',
    description: 'Fresh and crisp heads of Romaine lettuce, ideal for salads and sandwiches.',
    price: 210,
    mrp: 230,
    category: 'Vegetables',
    image: 'https://picsum.photos/seed/lettuce/400/400',
    imageHint: 'lettuce vegetable',
    stock_qty: 60,
    brand: 'Green Fields',
  },
  {
    id: '5',
    name_en: 'Artisanal Sourdough',
    description: 'A rustic loaf of naturally leavened sourdough, baked fresh daily.',
    price: 450,
    mrp: 500,
    category: 'Bakery',
    image: 'https://picsum.photos/seed/bread/400/400',
    imageHint: 'bread loaf',
    stock_qty: 30,
    brand: 'The Bakehouse',
  },
  {
    id: '6',
    name_en: 'Free-Range Eggs',
    description: 'One dozen large brown eggs from pasture-raised, free-range chickens.',
    price: 560,
    mrp: 600,
    category: 'Dairy',
    image: 'https://picsum.photos/seed/eggs/400/400',
    imageHint: 'eggs carton',
    stock_qty: 100,
    brand: 'Happy Hens',
  },
  {
    id: '7',
    name_en: 'Organic Milk',
    description: 'A half-gallon of fresh, organic whole milk. Rich and wholesome.',
    price: 320,
    mrp: 350,
    category: 'Dairy',
    image: 'https://picsum.photos/seed/milk/400/400',
    imageHint: 'milk bottle',
    stock_qty: 75,
    brand: 'Pure Dairy',
  },
  {
    id: '8',
    name_en: 'Cold-Pressed Juice',
    description: 'A refreshing blend of apple, kale, and ginger cold-pressed juice.',
    price: 410,
    mrp: 450,
    category: 'Beverages',
    image: 'https://picsum.photos/seed/juice/400/400',
    imageHint: 'juice bottle',
    stock_qty: 45,
    brand: 'Juice Up',
  },
  {
    id: '9',
    name_en: 'Sweet Oranges',
    description: 'Juicy and sweet Navel oranges, packed with Vitamin C.',
    price: 240,
    mrp: 260,
    category: 'Fruits',
    image: 'https://picsum.photos/seed/oranges/400/400',
    imageHint: 'oranges fruit',
    stock_qty: 90,
    brand: 'Citrus Grove',
  },
  {
    id: '10',
    name_en: 'Fresh Broccoli',
    description: 'Crisp and tender broccoli crowns, perfect for steaming or roasting.',
    price: 225,
    mrp: 250,
    category: 'Vegetables',
    image: 'https://picsum.photos/seed/broccoli/400/400',
    imageHint: 'broccoli vegetable',
    stock_qty: 55,
    brand: 'Green Giant',
  },
];

export const promotions: Promotion[] = [
  {
    id: 'promo-1',
    title: 'Weekly Special',
    description: 'Get 20% off all organic berries!',
    imageUrl: 'https://picsum.photos/seed/promo-berries/600/400',
    imageHint: 'berries fruit',
  },
  {
    id: 'promo-2',
    title: 'Bakery Bonanza',
    description: 'Buy one, get one free on all sourdough bread.',
    imageUrl: 'https://picsum.photos/seed/promo-bread/600/400',
    imageHint: 'fresh bread',
  },
  {
    id: 'promo-3',
    title: 'Veggie Power',
    description: 'Save ₹400 when you spend ₹2000 on fresh vegetables.',
    imageUrl: 'https://picsum.photos/seed/promo-veggies/600/400',
    imageHint: 'vegetables variety',
  },
];

export const earningsData: EarningPeriod[] = [
  { day: 'Mon', earnings: 120 },
  { day: 'Tue', earnings: 150 },
  { day: 'Wed', earnings: 170 },
  { day: 'Thu', earnings: 130 },
  { day: 'Fri', earnings: 210 },
  { day: 'Sat', earnings: 250 },
  { day: 'Sun', earnings: 180 },
];

export const transactions: Transaction[] = [
  { id: '#3210', status: 'Completed', amount: 25.0, date: '2023-10-26' },
  { id: '#3209', status: 'Completed', amount: 15.0, date: '2023-10-26' },
  { id: '#3208', status: 'Completed', amount: 42.5, date: '2023-10-25' },
  { id: '#3207', status: 'Pending', amount: 10.0, date: '2023-10-25' },
  { id: '#3206', status: 'Completed', amount: 35.75, date: '2023-10-24' },
];

export const orders: Partial<Order>[] = [
    {
      id: 'FZ-12345',
      userId: 'user1',
      items: [
        { productId: '1', name: 'Organic Avocados', price: 375, quantity: 2 },
        { productId: '5', name: 'Artisanal Sourdough', price: 450, quantity: 1 },
      ],
      totalAmount: 1200,
      status: 'out for delivery',
      createdAt: new Date('2023-10-27T10:00:00Z'),
      updatedAt: new Date('2023-10-27T11:00:00Z'),
    },
     {
      id: 'FZ-67890',
      userId: 'user1',
      items: [
        { productId: '2', name: 'Fresh Strawberries', price: 260, quantity: 1 },
      ],
      totalAmount: 260,
      status: 'delivered',
      createdAt: new Date('2023-10-25T14:30:00Z'),
      updatedAt: new Date('2023-10-25T15:15:00Z'),
    }
  ];

