import { Product } from '../../types';

export const BAKERY_PRODUCTS: Product[] = [
  {
    id: 'bread-small',
    name_en: 'Small Bread',
    name_hi: 'Chhota Bread',
    description: 'A small loaf of fresh white bread, perfect for sandwiches.',
    brand: 'Local Bakery',
    category_id: 'cat-2',
    mrp: 20,
    price: 18,
    stock_qty: 100,
    pack_size: '1 loaf',
    is_veg: true,
    delivery_mode: 'quick',
    image: 'https://firebasestorage.googleapis.com/v0/b/freshoz-fresh-fast.firebasestorage.app/o/categories%2Fdairy%2Fproducts%2Fbread-small.webp?alt=media&token=a0c1b7a2-7b1d-4b5b-9b4e-4b0e3b6e8d2a',
    imageHint: 'small bread loaf',
    tags: ['bakery', 'bread', 'white bread'],
    rating: 4.3,
    rating_count: 120,
    warehouse_stock: [{ warehouse_id: 'sultanganj', stock: 100 }],
  },
  {
    id: 'bread-big',
    name_en: 'Big Bread',
    name_hi: 'Bada Bread',
    description: 'A large loaf of fresh white bread for the whole family.',
    brand: 'Local Bakery',
    category_id: 'cat-2',
    mrp: 35,
    price: 32,
    stock_qty: 80,
    pack_size: '1 loaf',
    is_veg: true,
    delivery_mode: 'quick',
    image: 'https://firebasestorage.googleapis.com/v0/b/freshoz-fresh-fast.firebasestorage.app/o/categories%2Fdairy%2Fproducts%2Fbread-big.webp?alt=media&token=c19ac51c-4394-4361-9cde-607062402511',
    imageHint: 'large bread loaf',
    tags: ['bakery', 'bread', 'white bread', 'family pack'],
    rating: 4.5,
    rating_count: 150,
    warehouse_stock: [{ warehouse_id: 'sultanganj', stock: 80 }],
  },
  {
    id: 'brown-bread',
    name_en: 'Brown Bread',
    name_hi: 'Brown Bread',
    description: 'Healthy and delicious brown bread made with whole wheat.',
    brand: 'Healthy Bites',
    category_id: 'cat-2',
    mrp: 40,
    price: 38,
    stock_qty: 60,
    pack_size: '1 loaf',
    is_veg: true,
    delivery_mode: 'quick',
    image: 'https://firebasestorage.googleapis.com/v0/b/freshoz-fresh-fast.firebasestorage.app/o/categories%2Fdairy%2Fproducts%2Fbrown-bread.webp?alt=media&token=8d2e85a6-f283-42e7-9d7a-7c917ab8e90e',
    imageHint: 'brown bread loaf',
    tags: ['bakery', 'bread', 'brown bread', 'whole wheat', 'healthy'],
    rating: 4.7,
    rating_count: 180,
    warehouse_stock: [{ warehouse_id: 'sultanganj', stock: 60 }],
  },
];
