import { Product } from '../../types';

export const DAIRY_PRODUCTS: Product[] = [
  {
    id: 'milk-1',
    name_en: 'Amul Gold Milk',
    name_hi: 'Amul Gold Doodh',
    description: 'Premium homogenized milk with high nutrition value. Rich in calcium and protein.',
    brand: 'Amul',
    category_id: 'cat-2',
    mrp: 60,
    price: 56,
    stock_qty: 100,
    unit: 'packet',
    is_veg: true,
    delivery_mode: 'quick',
    image: 'https://firebasestorage.googleapis.com/v0/b/freshoz-fresh-fast.firebasestorage.app/o/categories%2Fdairy%2Fproducts%2Famul-gold.webp?alt=media&token=e11c5d07-29b4-47c0-a070-5b5849884c7e',
    imageHint: 'Amul Milk',
    tags: ['dairy', 'milk', 'amul', 'premium', 'calcium'],
    rating: 4.5,
    rating_count: 250,
    warehouse_stock: [
      { warehouse_id: 'sultanganj', stock: 50 },
      { warehouse_id: 'bhagalpur', stock: 0 },
      { warehouse_id: 'khagaria', stock: 0 }
    ],
    variants: [
        { id: 'milk-1-1', pack_size: '500ml', mrp: 30, price: 28, stock_qty: 50 },
        { id: 'milk-1-2', pack_size: '1ltr', mrp: 60, price: 56, stock_qty: 50 },
    ]
  },
  {
    id: 'milk-2',
    name_en: 'Amul Taaza Milk',
    name_hi: 'Amul Taaza Doodh',
    description: 'Fresh and pure milk with balanced nutrition. Perfect for daily use.',
    brand: 'Amul',
    category_id: 'cat-2',
    mrp: 55,
    price: 52,
    stock_qty: 150,
    unit: 'packet',
    pack_size: '500 ml',
    is_veg: true,
    delivery_mode: 'quick',
    image: 'https://firebasestorage.googleapis.com/v0/b/freshoz-fresh-fast.firebasestorage.app/o/categories%2Fdairy%2Fproducts%2Famul-taaza.webp?alt=media&token=6831d10e-436d-495c-99d4-1a9807538b76',
    imageHint: 'Amul Taaza',
    tags: ['dairy', 'milk', 'amul', 'fresh', 'daily'],
    rating: 4.4,
    rating_count: 300,
    warehouse_stock: [
      { warehouse_id: 'sultanganj', stock: 70 },
      { warehouse_id: 'bhagalpur', stock: 0 },
      { warehouse_id: 'khagaria', stock: 0 }
    ],
    variants: [
        { id: 'milk-2-1', pack_size: '500 ml', mrp: 28, price: 26, stock_qty: 100 },
        { id: 'milk-2-2', pack_size: '1 L', mrp: 55, price: 52, stock_qty: 50 },
    ]
  },
  {
    id: 'curd-1',
    name_en: 'Amul Masti Curd',
    name_hi: 'Amul Masti Dahi',
    description: 'Fresh and creamy curd with probiotic benefits. Good for digestion.',
    brand: 'Amul',
    category_id: 'cat-2',
    mrp: 40,
    price: 38,
    stock_qty: 80,
    unit: 'cup',
    pack_size: '400 g',
    is_veg: true,
    delivery_mode: 'quick',
    image: 'https://firebasestorage.googleapis.com/v0/b/freshoz-fresh-fast.firebasestorage.app/o/categories%2Fdairy%2Fproducts%2Famul-curd.webp?alt=media&token=7c1c0e3a-5f0e-4e4b-9e4a-4e2b0c1b7a2e',
    imageHint: 'Amul Curd',
    tags: ['dairy', 'curd', 'yogurt', 'probiotic', 'digestion'],
    rating: 4.3,
    rating_count: 180,
    warehouse_stock: [
      { warehouse_id: 'sultanganj', stock: 40 },
      { warehouse_id: 'bhagalpur', stock: 0 },
      { warehouse_id: 'khagaria', stock: 0 }
    ],
    variants: [
        { id: 'curd-1-1', pack_size: '200 g', mrp: 22, price: 20, stock_qty: 40 },
        { id: 'curd-1-2', pack_size: '400 g', mrp: 40, price: 38, stock_qty: 40 },
    ]
  },
  {
    id: 'curd-2',
    name_en: 'Raj Curd',
    name_hi: 'Raj Dahi',
    description: 'Pure and fresh curd with traditional taste. No preservatives.',
    brand: 'Raj',
    category_id: 'cat-2',
    mrp: 42,
    price: 40,
    stock_qty: 90,
    unit: 'cup',
    pack_size: '400 g',
    is_veg: true,
    delivery_mode: 'quick',
    image: 'https://picsum.photos/seed/curd-2/400/400',
    imageHint: 'Raj Curd',
    tags: ['dairy', 'curd', 'raj', 'fresh', 'traditional'],
    rating: 4.6,
    rating_count: 220,
    warehouse_stock: [
      { warehouse_id: 'sultanganj', stock: 45 },
      { warehouse_id: 'bhagalpur', stock: 0 },
      { warehouse_id: 'khagaria', stock: 0 }
    ],
    variants: [
        { id: 'curd-2-1', pack_size: '200 g', mrp: 23, price: 21, stock_qty: 45 },
        { id: 'curd-2-2', pack_size: '400 g', mrp: 42, price: 40, stock_qty: 45 },
    ]
  },
  {
    id: 'paneer-1',
    name_en: 'Amul Fresh Paneer',
    name_hi: 'Amul Fresh Paneer',
    description: 'Fresh and soft paneer. Perfect for curries and snacks.',
    brand: 'Amul',
    category_id: 'cat-2',
    mrp: 90,
    price: 85,
    stock_qty: 60,
    unit: 'pack',
    pack_size: '200 g',
    is_veg: true,
    delivery_mode: 'quick',
    image: 'https://picsum.photos/seed/paneer-1/400/400',
    imageHint: 'Amul Paneer',
    tags: ['dairy', 'paneer', 'cottage cheese', 'fresh', 'cooking'],
    rating: 4.7,
    rating_count: 190,
    warehouse_stock: [
      { warehouse_id: 'sultanganj', stock: 30 },
      { warehouse_id: 'bhagalpur', stock: 0 },
      { warehouse_id: 'khagaria', stock: 0 }
    ],
    variants: [
        { id: 'paneer-1-1', pack_size: '200 g', mrp: 90, price: 85, stock_qty: 30 },
        { id: 'paneer-1-2', pack_size: '500 g', mrp: 220, price: 210, stock_qty: 30 },
    ]
  },
  {
    id: 'butter-1',
    name_en: 'Amul Butter',
    name_hi: 'Amul Butter',
    description: 'Pure and creamy butter. Perfect for cooking and spreading.',
    brand: 'Amul',
    category_id: 'cat-2',
    mrp: 55,
    price: 52,
    stock_qty: 120,
    unit: 'pack',
    pack_size: '100 g',
    is_veg: true,
    delivery_mode: 'quick',
    image: 'https://picsum.photos/seed/butter-1/400/400',
    imageHint: 'Amul Butter',
    tags: ['dairy', 'butter', 'amul', 'cooking', 'spread'],
    rating: 4.8,
    rating_count: 350,
    warehouse_stock: [
      { warehouse_id: 'sultanganj', stock: 60 },
      { warehouse_id: 'bhagalpur', stock: 0 },
      { warehouse_id: 'khagaria', stock: 0 }
    ],
    variants: [
        { id: 'butter-1-1', pack_size: '100 g', mrp: 55, price: 52, stock_qty: 60 },
        { id: 'butter-1-2', pack_size: '500 g', mrp: 270, price: 260, stock_qty: 60 },
    ]
  },
  {
    id: 'butter-2',
    name_en: 'Amul Garlic Butter',
    name_hi: 'Amul Garlic Butter',
    description: 'Flavorful garlic butter. Perfect for bread and cooking.',
    brand: 'Amul',
    category_id: 'cat-2',
    mrp: 60,
    price: 57,
    stock_qty: 70,
    unit: 'pack',
    pack_size: '100 g',
    is_veg: true,
    delivery_mode: 'quick',
    image: 'https://picsum.photos/seed/butter-2/400/400',
    imageHint: 'Garlic Butter',
    tags: ['dairy', 'butter', 'garlic', 'flavored', 'cooking'],
    rating: 4.5,
    rating_count: 120,
    warehouse_stock: [
      { warehouse_id: 'sultanganj', stock: 35 },
      { warehouse_id: 'bhagalpur', stock: 0 },
      { warehouse_id: 'khagaria', stock: 0 }
    ],
    variants: [
        { id: 'butter-2-1', pack_size: '100 g', mrp: 60, price: 57, stock_qty: 70 },
    ]
  },
  {
    id: 'cheese-1',
    name_en: 'Amul Processed Cheese',
    name_hi: 'Amul Processed Cheese',
    description: 'Creamy processed cheese. Perfect for sandwiches and pizzas.',
    brand: 'Amul',
    category_id: 'cat-2',
    mrp: 45,
    price: 42,
    stock_qty: 100,
    unit: 'pack',
    pack_size: '200 g',
    is_veg: true,
    delivery_mode: 'quick',
    image: 'https://picsum.photos/seed/cheese-1/400/400',
    imageHint: 'Amul Cheese',
    tags: ['dairy', 'cheese', 'processed', 'sandwich', 'pizza'],
    rating: 4.4,
    rating_count: 280,
    warehouse_stock: [
      { warehouse_id: 'sultanganj', stock: 50 },
      { warehouse_id: 'bhagalpur', stock: 0 },
      { warehouse_id: 'khagaria', stock: 0 }
    ],
    variants: [
        { id: 'cheese-1-1', pack_size: '100 g', mrp: 75, price: 70, stock_qty: 50 },
        { id: 'cheese-1-2', pack_size: '400 g', mrp: 140, price: 135, stock_qty: 50 },
    ]
  },
  {
    id: 'cheese-2',
    name_en: 'Amul Cheese Slices',
    name_hi: 'Amul Cheese Slices',
    description: 'Pre-sliced cheese. Convenient for sandwiches and burgers.',
    brand: 'Amul',
    category_id: 'cat-2',
    mrp: 50,
    price: 47,
    stock_qty: 80,
    unit: 'pack',
    pack_size: '10 slices',
    is_veg: true,
    delivery_mode: 'quick',
    image: 'https://picsum.photos/seed/cheese-2/400/400',
    imageHint: 'Cheese Slices',
    tags: ['dairy', 'cheese', 'slices', 'sandwich', 'burger'],
    rating: 4.3,
    rating_count: 150,
    warehouse_stock: [
      { warehouse_id: 'sultanganj', stock: 40 },
      { warehouse_id: 'bhagalpur', stock: 0 },
      { warehouse_id: 'khagaria', stock: 0 }
    ],
    variants: [
        { id: 'cheese-2-1', pack_size: '10 slices', mrp: 80, price: 75, stock_qty: 40 },
        { id: 'cheese-2-2', pack_size: '20 slices', mrp: 150, price: 145, stock_qty: 40 },
    ]
  },
  {
    id: 'ghee-1',
    name_en: 'Amul Pure Ghee',
    name_hi: 'Amul Shuddh Ghee',
    description: 'Pure and aromatic desi ghee. Perfect for Indian cooking.',
    brand: 'Amul',
    category_id: 'cat-2',
    mrp: 220,
    price: 210,
    stock_qty: 50,
    unit: 'bottle',
    pack_size: '500 ml',
    is_veg: true,
    delivery_mode: 'quick',
    image: 'https://picsum.photos/seed/ghee-1/400/400',
    imageHint: 'Amul Ghee',
    tags: ['dairy', 'ghee', 'pure', 'desi', 'cooking'],
    rating: 4.9,
    rating_count: 420,
    warehouse_stock: [
      { warehouse_id: 'sultanganj', stock: 25 },
      { warehouse_id: 'bhagalpur', stock: 0 },
      { warehouse_id: 'khagaria', stock: 0 }
    ],
    variants: [
        { id: 'ghee-1-1', pack_size: '200 ml', mrp: 110, price: 105, stock_qty: 25 },
        { id: 'ghee-1-2', pack_size: '500 ml', mrp: 220, price: 210, stock_qty: 15 },
        { id: 'ghee-1-3', pack_size: '1 L', mrp: 430, price: 410, stock_qty: 10 },
    ]
  },
  {
    id: 'amul-shakti',
    name_en: 'Amul Shakti Milk',
    name_hi: 'Amul Shakti Doodh',
    description: 'Homogenised toned milk, a perfect balance of health and taste.',
    brand: 'Amul',
    category_id: 'cat-2',
    mrp: 27,
    price: 26,
    stock_qty: 100,
    is_veg: true,
    delivery_mode: 'quick',
    image: 'https://firebasestorage.googleapis.com/v0/b/freshoz-fresh-fast.firebasestorage.app/o/categories%2Fdairy%2Fproducts%2Famul-shakti.webp?alt=media&token=e16f3e5c-7d7d-4b5b-9b4e-4b0e3b6e8d2a',
    imageHint: 'Amul Shakti milk',
    tags: ['dairy', 'milk', 'toned'],
    rating: 4.4,
    rating_count: 200,
    warehouse_stock: [{ warehouse_id: 'sultanganj', stock: 100 }],
    variants: [
      { id: 'amul-shakti-500', pack_size: '500ml', mrp: 27, price: 26, stock_qty: 50 },
      { id: 'amul-shakti-1000', pack_size: '1ltr', mrp: 54, price: 52, stock_qty: 50 },
    ],
  },
  {
    id: 'amul-cow-milk',
    name_en: 'Amul Cow Milk',
    name_hi: 'Amul Gaay ka Doodh',
    description: 'Pure and fresh cow milk, pasteurised for safety.',
    brand: 'Amul',
    category_id: 'cat-2',
    mrp: 28,
    price: 27,
    stock_qty: 80,
    is_veg: true,
    delivery_mode: 'quick',
    image: 'https://firebasestorage.googleapis.com/v0/b/freshoz-fresh-fast.firebasestorage.app/o/categories%2Fdairy%2Fproducts%2Famul-cow.webp?alt=media&token=c19ac51c-4394-4361-9cde-607062402511',
    imageHint: 'Amul cow milk',
    tags: ['dairy', 'milk', 'cow milk'],
    rating: 4.6,
    rating_count: 180,
    warehouse_stock: [{ warehouse_id: 'sultanganj', stock: 80 }],
    variants: [
      { id: 'amul-cow-500', pack_size: '500ml', mrp: 28, price: 27, stock_qty: 40 },
      { id: 'amul-cow-1000', pack_size: '1ltr', mrp: 56, price: 54, stock_qty: 40 },
    ],
  },
  {
    id: 'sudha-gold',
    name_en: 'Sudha Gold Milk',
    name_hi: 'Sudha Gold Doodh',
    description: 'Full cream milk from Sudha Dairy, rich and creamy.',
    brand: 'Sudha',
    category_id: 'cat-2',
    mrp: 30,
    price: 29,
    stock_qty: 120,
    is_veg: true,
    delivery_mode: 'quick',
    image: 'https://firebasestorage.googleapis.com/v0/b/freshoz-fresh-fast.firebasestorage.app/o/categories%2Fdairy%2Fproducts%2Fsudha-gold.webp?alt=media&token=787c88b3-3a7a-4c2e-8c3e-8f1e0d3b6e8a',
    imageHint: 'Sudha milk pack',
    tags: ['dairy', 'milk', 'full cream'],
    rating: 4.5,
    rating_count: 220,
    warehouse_stock: [{ warehouse_id: 'sultanganj', stock: 120 }],
    variants: [
      { id: 'sudha-gold-500', pack_size: '500ml', mrp: 30, price: 29, stock_qty: 60 },
      { id: 'sudha-gold-1000', pack_size: '1ltr', mrp: 60, price: 58, stock_qty: 60 },
    ],
  },
  {
    id: 'sudha-shakti',
    name_en: 'Sudha Shakti Milk',
    name_hi: 'Sudha Shakti Doodh',
    description: 'Toned milk from Sudha, ideal for daily consumption.',
    brand: 'Sudha',
    category_id: 'cat-2',
    mrp: 26,
    price: 25,
    stock_qty: 150,
    is_veg: true,
    delivery_mode: 'quick',
    image: 'https://firebasestorage.googleapis.com/v0/b/freshoz-fresh-fast.firebasestorage.app/o/categories%2Fdairy%2Fproducts%2Fsudha-shakti.webp?alt=media&token=8d2e85a6-f283-42e7-9d7a-7c917ab8e90e',
    imageHint: 'Sudha milk packet',
    tags: ['dairy', 'milk', 'toned'],
    rating: 4.3,
    rating_count: 190,
    warehouse_stock: [{ warehouse_id: 'sultanganj', stock: 150 }],
    variants: [
      { id: 'sudha-shakti-500', pack_size: '500ml', mrp: 26, price: 25, stock_qty: 75 },
      { id: 'sudha-shakti-1000', pack_size: '1ltr', mrp: 52, price: 50, stock_qty: 75 },
    ],
  },
  {
    id: 'sudha-cow-milk',
    name_en: 'Sudha Cow Milk',
    name_hi: 'Sudha Gaay ka Doodh',
    description: 'Fresh and pure cow milk from Sudha.',
    brand: 'Sudha',
    category_id: 'cat-2',
    mrp: 27,
    price: 26,
    stock_qty: 90,
    is_veg: true,
    delivery_mode: 'quick',
    image: 'https://firebasestorage.googleapis.com/v0/b/freshoz-fresh-fast.firebasestorage.app/o/categories%2Fdairy%2Fproducts%2Fsudha-cow.webp?alt=media&token=c19ac51c-4394-4361-9cde-607062402511',
    imageHint: 'Sudha cow milk',
    tags: ['dairy', 'milk', 'cow milk'],
    rating: 4.6,
    rating_count: 170,
    warehouse_stock: [{ warehouse_id: 'sultanganj', stock: 90 }],
    variants: [
      { id: 'sudha-cow-500', pack_size: '500ml', mrp: 27, price: 26, stock_qty: 45 },
      { id: 'sudha-cow-1000', pack_size: '1ltr', mrp: 54, price: 52, stock_qty: 45 },
    ],
  }
];
