import { Product } from '../../types';

export const DAIRY_PRODUCTS: Product[] = [
  {
    id: 'milk-1',
    name_en: 'Amul Gold Milk',
    name_hi: 'Amul Gold Doodh',
    description: 'Premium homogenized milk with high nutrition value. Rich in calcium and protein.',
    brand: 'Amul',
    category_id: 'cat-2',
    mrp: 60,
    price: 56,
    stock_qty: 100,
    unit: 'packet',
    pack_size: '500 ml',
    is_veg: true,
    delivery_mode: 'quick',
    image: 'https://picsum.photos/seed/milk-1/400/400',
    imageHint: 'Amul Milk',
    tags: ['dairy', 'milk', 'amul', 'premium', 'calcium'],
    rating: 4.5,
    rating_count: 250,
    warehouse_stock: [
      { warehouse_id: 'sultanganj', stock: 50 },
      { warehouse_id: 'bhagalpur', stock: 0 },
      { warehouse_id: 'khagaria', stock: 0 }
    ]
  },
  {
    id: 'milk-2',
    name_en: 'Amul Taaza Milk',
    name_hi: 'Amul Taaza Doodh',
    description: 'Fresh and pure milk with balanced nutrition. Perfect for daily use.',
    brand: 'Amul',
    category_id: 'cat-2',
    mrp: 55,
    price: 52,
    stock_qty: 150,
    unit: 'packet',
    pack_size: '500 ml',
    is_veg: true,
    delivery_mode: 'quick',
    image: 'https://picsum.photos/seed/milk-2/400/400',
    imageHint: 'Amul Taaza',
    tags: ['dairy', 'milk', 'amul', 'fresh', 'daily'],
    rating: 4.4,
    rating_count: 300,
    warehouse_stock: [
      { warehouse_id: 'sultanganj', stock: 70 },
      { warehouse_id: 'bhagalpur', stock: 0 },
      { warehouse_id: 'khagaria', stock: 0 }
    ]
  },
  {
    id: 'curd-1',
    name_en: 'Amul Masti Curd',
    name_hi: 'Amul Masti Dahi',
    description: 'Fresh and creamy curd with probiotic benefits. Good for digestion.',
    brand: 'Amul',
    category_id: 'cat-2',
    mrp: 40,
    price: 38,
    stock_qty: 80,
    unit: 'cup',
    pack_size: '400 g',
    is_veg: true,
    delivery_mode: 'quick',
    image: 'https://picsum.photos/seed/curd-1/400/400',
    imageHint: 'Amul Curd',
    tags: ['dairy', 'curd', 'yogurt', 'probiotic', 'digestion'],
    rating: 4.3,
    rating_count: 180,
    warehouse_stock: [
      { warehouse_id: 'sultanganj', stock: 40 },
      { warehouse_id: 'bhagalpur', stock: 0 },
      { warehouse_id: 'khagaria', stock: 0 }
    ]
  },
  {
    id: 'curd-2',
    name_en: 'Mother Dairy Curd',
    name_hi: 'Mother Dairy Dahi',
    description: 'Pure and fresh curd with traditional taste. No preservatives.',
    brand: 'Mother Dairy',
    category_id: 'cat-2',
    mrp: 42,
    price: 40,
    stock_qty: 90,
    unit: 'cup',
    pack_size: '400 g',
    is_veg: true,
    delivery_mode: 'quick',
    image: 'https://picsum.photos/seed/curd-2/400/400',
    imageHint: 'Mother Dairy Curd',
    tags: ['dairy', 'curd', 'mother dairy', 'fresh', 'traditional'],
    rating: 4.6,
    rating_count: 220,
    warehouse_stock: [
      { warehouse_id: 'sultanganj', stock: 45 },
      { warehouse_id: 'bhagalpur', stock: 0 },
      { warehouse_id: 'khagaria', stock: 0 }
    ]
  },
  {
    id: 'paneer-1',
    name_en: 'Amul Fresh Paneer',
    name_hi: 'Amul Fresh Paneer',
    description: 'Fresh and soft paneer. Perfect for curries and snacks.',
    brand: 'Amul',
    category_id: 'cat-2',
    mrp: 90,
    price: 85,
    stock_qty: 60,
    unit: 'pack',
    pack_size: '200 g',
    is_veg: true,
    delivery_mode: 'quick',
    image: 'https://picsum.photos/seed/paneer-1/400/400',
    imageHint: 'Amul Paneer',
    tags: ['dairy', 'paneer', 'cottage cheese', 'fresh', 'cooking'],
    rating: 4.7,
    rating_count: 190,
    warehouse_stock: [
      { warehouse_id: 'sultanganj', stock: 30 },
      { warehouse_id: 'bhagalpur', stock: 0 },
      { warehouse_id: 'khagaria', stock: 0 }
    ]
  },
  {
    id: 'butter-1',
    name_en: 'Amul Butter',
    name_hi: 'Amul Butter',
    description: 'Pure and creamy butter. Perfect for cooking and spreading.',
    brand: 'Amul',
    category_id: 'cat-2',
    mrp: 55,
    price: 52,
    stock_qty: 120,
    unit: 'pack',
    pack_size: '100 g',
    is_veg: true,
    delivery_mode: 'quick',
    image: 'https://picsum.photos/seed/butter-1/400/400',
    imageHint: 'Amul Butter',
    tags: ['dairy', 'butter', 'amul', 'cooking', 'spread'],
    rating: 4.8,
    rating_count: 350,
    warehouse_stock: [
      { warehouse_id: 'sultanganj', stock: 60 },
      { warehouse_id: 'bhagalpur', stock: 0 },
      { warehouse_id: 'khagaria', stock: 0 }
    ]
  },
  {
    id: 'butter-2',
    name_en: 'Amul Garlic Butter',
    name_hi: 'Amul Garlic Butter',
    description: 'Flavorful garlic butter. Perfect for bread and cooking.',
    brand: 'Amul',
    category_id: 'cat-2',
    mrp: 60,
    price: 57,
    stock_qty: 70,
    unit: 'pack',
    pack_size: '100 g',
    is_veg: true,
    delivery_mode: 'quick',
    image: 'https://picsum.photos/seed/butter-2/400/400',
    imageHint: 'Garlic Butter',
    tags: ['dairy', 'butter', 'garlic', 'flavored', 'cooking'],
    rating: 4.5,
    rating_count: 120,
    warehouse_stock: [
      { warehouse_id: 'sultanganj', stock: 35 },
      { warehouse_id: 'bhagalpur', stock: 0 },
      { warehouse_id: 'khagaria', stock: 0 }
    ]
  },
  {
    id: 'cheese-1',
    name_en: 'Amul Processed Cheese',
    name_hi: 'Amul Processed Cheese',
    description: 'Creamy processed cheese. Perfect for sandwiches and pizzas.',
    brand: 'Amul',
    category_id: 'cat-2',
    mrp: 45,
    price: 42,
    stock_qty: 100,
    unit: 'pack',
    pack_size: '200 g',
    is_veg: true,
    delivery_mode: 'quick',
    image: 'https://picsum.photos/seed/cheese-1/400/400',
    imageHint: 'Amul Cheese',
    tags: ['dairy', 'cheese', 'processed', 'sandwich', 'pizza'],
    rating: 4.4,
    rating_count: 280,
    warehouse_stock: [
      { warehouse_id: 'sultanganj', stock: 50 },
      { warehouse_id: 'bhagalpur', stock: 0 },
      { warehouse_id: 'khagaria', stock: 0 }
    ]
  },
  {
    id: 'cheese-2',
    name_en: 'Amul Cheese Slices',
    name_hi: 'Amul Cheese Slices',
    description: 'Pre-sliced cheese. Convenient for sandwiches and burgers.',
    brand: 'Amul',
    category_id: 'cat-2',
    mrp: 50,
    price: 47,
    stock_qty: 80,
    unit: 'pack',
    pack_size: '10 slices',
    is_veg: true,
    delivery_mode: 'quick',
    image: 'https://picsum.photos/seed/cheese-2/400/400',
    imageHint: 'Cheese Slices',
    tags: ['dairy', 'cheese', 'slices', 'sandwich', 'burger'],
    rating: 4.3,
    rating_count: 150,
    warehouse_stock: [
      { warehouse_id: 'sultanganj', stock: 40 },
      { warehouse_id: 'bhagalpur', stock: 0 },
      { warehouse_id: 'khagaria', stock: 0 }
    ]
  },
  {
    id: 'ghee-1',
    name_en: 'Amul Pure Ghee',
    name_hi: 'Amul Shuddh Ghee',
    description: 'Pure and aromatic desi ghee. Perfect for Indian cooking.',
    brand: 'Amul',
    category_id: 'cat-2',
    mrp: 220,
    price: 210,
    stock_qty: 50,
    unit: 'bottle',
    pack_size: '500 ml',
    is_veg: true,
    delivery_mode: 'quick',
    image: 'https://picsum.photos/seed/ghee-1/400/400',
    imageHint: 'Amul Ghee',
    tags: ['dairy', 'ghee', 'pure', 'desi', 'cooking'],
    rating: 4.9,
    rating_count: 420,
    warehouse_stock: [
      { warehouse_id: 'sultanganj', stock: 25 },
      { warehouse_id: 'bhagalpur', stock: 0 },
      { warehouse_id: 'khagaria', stock: 0 }
    ]
  }
];