import { Product } from '../../types';

export const FROZEN_PRODUCTS: Product[] = [
  {
    id: 'frozen-1',
    name_en: 'McCain French Fries',
    name_hi: 'McCain French Fries',
    description: 'Crispy and golden french fries. Ready to fry.',
    brand: 'McCain',
    category_id: 'cat-2',
    mrp: 199,
    price: 179,
    stock_qty: 35,
    unit: 'pack',
    pack_size: '500 g',
    is_veg: true,
    delivery_mode: 'quick',
    image: 'https://picsum.photos/seed/frozen-1/400/400',
    imageHint: 'French Fries',
    tags: ['frozen', 'french fries', 'snacks', 'ready to cook'],
    rating: 4.3,
    rating_count: 120,
    warehouse_stock: [
      { warehouse_id: 'sultanganj', stock: 15 },
      { warehouse_id: 'bhagalpur', stock: 0 },
      { warehouse_id: 'khagaria', stock: 0 }
    ]
  },
  {
    id: 'frozen-2',
    name_en: 'Sumeru Veg Spring Rolls',
    name_hi: 'Sumeru Veg Spring Rolls',
    description: 'Crispy vegetable spring rolls. Ready to fry.',
    brand: 'Sumeru',
    category_id: 'cat-2',
    mrp: 179,
    price: 159,
    stock_qty: 30,
    unit: 'pack',
    pack_size: '300 g',
    is_veg: true,
    delivery_mode: 'quick',
    image: 'https://picsum.photos/seed/frozen-2/400/400',
    imageHint: 'Veg Spring Rolls',
    tags: ['frozen', 'spring rolls', 'veg', 'snacks'],
    rating: 4.0,
    rating_count: 95,
    warehouse_stock: [
      { warehouse_id: 'sultanganj', stock: 12 },
      { warehouse_id: 'bhagalpur', stock: 0 },
      { warehouse_id: 'khagaria', stock: 0 }
    ]
  },
  {
    id: 'frozen-3',
    name_en: 'Sumeru Green Peas',
    name_hi: 'Sumeru Hara Matar',
    description: 'Frozen green peas. Perfect for cooking.',
    brand: 'Sumeru',
    category_id: 'cat-2',
    mrp: 99,
    price: 89,
    stock_qty: 50,
    unit: 'pack',
    pack_size: '500 g',
    is_veg: true,
    delivery_mode: 'quick',
    image: 'https://picsum.photos/seed/frozen-3/400/400',
    imageHint: 'Green Peas',
    tags: ['frozen', 'green peas', 'vegetables', 'cooking'],
    rating: 4.1,
    rating_count: 150,
    warehouse_stock: [
      { warehouse_id: 'sultanganj', stock: 20 },
      { warehouse_id: 'bhagalpur', stock: 0 },
      { warehouse_id: 'khagaria', stock: 0 }
    ]
  },
  {
    id: 'frozen-4',
    name_en: 'McCain Aloo Tikki',
    name_hi: 'McCain Aloo Tikki',
    description: 'Crispy potato patties. Ready to cook.',
    brand: 'McCain',
    category_id: 'cat-2',
    mrp: 159,
    price: 139,
    stock_qty: 40,
    unit: 'pack',
    pack_size: '400 g',
    is_veg: true,
    delivery_mode: 'quick',
    image: 'https://picsum.photos/seed/frozen-4/400/400',
    imageHint: 'Aloo Tikki',
    tags: ['frozen', 'aloo tikki', 'snacks', 'ready to cook'],
    rating: 4.2,
    rating_count: 110,
    warehouse_stock: [
      { warehouse_id: 'sultanganj', stock: 16 },
      { warehouse_id: 'bhagalpur', stock: 0 },
      { warehouse_id: 'khagaria', stock: 0 }
    ]
  },
  {
    id: 'frozen-5',
    name_en: 'Sumeru Mixed Vegetables',
    name_hi: 'Sumeru Mix Sabji',
    description: 'Assorted frozen vegetables for cooking.',
    brand: 'Sumeru',
    category_id: 'cat-2',
    mrp: 129,
    price: 115,
    stock_qty: 35,
    unit: 'pack',
    pack_size: '500 g',
    is_veg: true,
    delivery_mode: 'quick',
    image: 'https://picsum.photos/seed/frozen-5/400/400',
    imageHint: 'Mixed Vegetables',
    tags: ['frozen', 'mixed vegetables', 'cooking'],
    rating: 4.0,
    rating_count: 85,
    warehouse_stock: [
      { warehouse_id: 'sultanganj', stock: 14 },
      { warehouse_id: 'bhagalpur', stock: 0 },
      { warehouse_id: 'khagaria', stock: 0 }
    ]
  },
  {
    id: 'frozen-6',
    name_en: 'McCain Smiles',
    name_hi: 'McCain Smiles',
    description: 'Fun-shaped potato snacks. Kids favorite.',
    brand: 'McCain',
    category_id: 'cat-2',
    mrp: 189,
    price: 169,
    stock_qty: 25,
    unit: 'pack',
    pack_size: '450 g',
    is_veg: true,
    delivery_mode: 'quick',
    image: 'https://picsum.photos/seed/frozen-6/400/400',
    imageHint: 'Potato Smiles',
    tags: ['frozen', 'potato smiles', 'kids', 'snacks'],
    rating: 4.4,
    rating_count: 95,
    warehouse_stock: [
      { warehouse_id: 'sultanganj', stock: 10 },
      { warehouse_id: 'bhagalpur', stock: 0 },
      { warehouse_id: 'khagaria', stock: 0 }
    ]
  },
  {
    id: 'frozen-7',
    name_en: 'Sumeru Corn Kernels',
    name_hi: 'Sumeru Sweet Corn',
    description: 'Frozen sweet corn kernels. Perfect for salads.',
    brand: 'Sumeru',
    category_id: 'cat-2',
    mrp: 89,
    price: 79,
    stock_qty: 45,
    unit: 'pack',
    pack_size: '400 g',
    is_veg: true,
    delivery_mode: 'quick',
    image: 'https://picsum.photos/seed/frozen-7/400/400',
    imageHint: 'Corn Kernels',
    tags: ['frozen', 'corn', 'salads', 'cooking'],
    rating: 4.2,
    rating_count: 120,
    warehouse_stock: [
      { warehouse_id: 'sultanganj', stock: 18 },
      { warehouse_id: 'bhagalpur', stock: 0 },
      { warehouse_id: 'khagaria', stock: 0 }
    ]
  },
  {
    id: 'frozen-8',
    name_en: 'McCain Veg Burger Patty',
    name_hi: 'McCain Veg Burger Patty',
    description: 'Ready to cook vegetable burger patties.',
    brand: 'McCain',
    category_id: 'cat-2',
    mrp: 219,
    price: 199,
    stock_qty: 30,
    unit: 'pack',
    pack_size: '400 g',
    is_veg: true,
    delivery_mode: 'quick',
    image: 'https://picsum.photos/seed/frozen-8/400/400',
    imageHint: 'Veg Burger Patty',
    tags: ['frozen', 'burger patty', 'veg', 'ready to cook'],
    rating: 4.1,
    rating_count: 80,
    warehouse_stock: [
      { warehouse_id: 'sultanganj', stock: 12 },
      { warehouse_id: 'bhagalpur', stock: 0 },
      { warehouse_id: 'khagaria', stock: 0 }
    ]
  },
  {
    id: 'frozen-9',
    name_en: 'Sumeru Cauliflower Florets',
    name_hi: 'Sumeru Cauliflower Florets',
    description: 'Frozen cauliflower florets for cooking.',
    brand: 'Sumeru',
    category_id: 'cat-2',
    mrp: 119,
    price: 105,
    stock_qty: 28,
    unit: 'pack',
    pack_size: '400 g',
    is_veg: true,
    delivery_mode: 'quick',
    image: 'https://picsum.photos/seed/frozen-9/400/400',
    imageHint: 'Cauliflower Florets',
    tags: ['frozen', 'cauliflower', 'vegetables', 'cooking'],
    rating: 4.0,
    rating_count: 65,
    warehouse_stock: [
      { warehouse_id: 'sultanganj', stock: 11 },
      { warehouse_id: 'bhagalpur', stock: 0 },
      { warehouse_id: 'khagaria', stock: 0 }
    ]
  },
  {
    id: 'frozen-10',
    name_en: 'McCain Cheese Nuggets',
    name_hi: 'McCain Cheese Nuggets',
    description: 'Crispy cheese nuggets. Perfect snack.',
    brand: 'McCain',
    category_id: 'cat-2',
    mrp: 239,
    price: 215,
    stock_qty: 22,
    unit: 'pack',
    pack_size: '350 g',
    is_veg: true,
    delivery_mode: 'quick',
    image: 'https://picsum.photos/seed/frozen-10/400/400',
    imageHint: 'Cheese Nuggets',
    tags: ['frozen', 'cheese nuggets', 'snacks', 'vegetarian'],
    rating: 4.3,
    rating_count: 70,
    warehouse_stock: [
      { warehouse_id: 'sultanganj', stock: 9 },
      { warehouse_id: 'bhagalpur', stock: 0 },
      { warehouse_id: 'khagaria', stock: 0 }
    ]
  }
];