import { Product } from '../../types';

export const FRUITS_PRODUCTS: Product[] = [
  {
    id: 'fruit-1',
    name_en: 'Banana',
    name_hi: 'Kela',
    description: 'Fresh ripe bananas',
    brand: 'Local Farmer',
    category_id: 'cat-1',
    mrp: 45,
    price: 40,
    stock_qty: 120,
    unit: 'dozen',
    pack_size: '12 pieces',
    is_veg: true,
    delivery_mode: 'quick',
    image: 'https://firebasestorage.googleapis.com/v0/b/freshoz-fresh-fast.firebasestorage.app/o/categories%2Ffruits%2Fproducts%2Fbanana.webp?alt=media&token=3e1cb18f-ce43-4994-83e3-d2cd0ee36fc6',
    imageHint: 'fresh bananas',
    tags: ['fruit', 'banana', 'ripe', 'fresh'],
    rating: 4.5,
    rating_count: 180,
    warehouse_stock: [
      { warehouse_id: 'sultanganj', stock: 50 },
      { warehouse_id: 'bhagalpur', stock: 40 },
      { warehouse_id: 'khagaria', stock: 30 }
    ]
  },
  {
    id: 'fruit-2',
    name_en: 'Apple',
    name_hi: 'Apple',
    description: 'Fresh Kashmiri apples',
    brand: 'Local Farmer',
    category_id: 'cat-1',
    mrp: 120,
    price: 110,
    stock_qty: 80,
    unit: 'kg',
    pack_size: '1 kg',
    is_veg: true,
    delivery_mode: 'quick',
    image: 'https://picsum.photos/seed/fruit-2/400/400',
    imageHint: 'fresh apples',
    tags: ['fruit', 'apple', 'kashmiri', 'fresh'],
    rating: 4.6,
    rating_count: 160,
    warehouse_stock: [
      { warehouse_id: 'sultanganj', stock: 35 },
      { warehouse_id: 'bhagalpur', stock: 25 },
      { warehouse_id: 'khagaria', stock: 20 }
    ]
  },
  {
    id: 'fruit-3',
    name_en: 'Orange',
    name_hi: 'Orange',
    description: 'Fresh Nagpur oranges',
    brand: 'Local Farmer',
    category_id: 'cat-1',
    mrp: 80,
    price: 70,
    stock_qty: 95,
    unit: 'kg',
    pack_size: '1 kg',
    is_veg: true,
    delivery_mode: 'quick',
    image: 'https://firebasestorage.googleapis.com/v0/b/freshoz-fresh-fast.firebasestorage.app/o/categories%2Ffruits%2Fproducts%2Forange.webp?alt=media&token=9afdd9c6-c355-4225-8c71-34b005eaa263',
    imageHint: 'fresh oranges',
    tags: ['fruit', 'orange', 'nagpur', 'fresh'],
    rating: 4.4,
    rating_count: 140,
    warehouse_stock: [
      { warehouse_id: 'sultanganj', stock: 40 },
      { warehouse_id: 'bhagalpur', stock: 30 },
      { warehouse_id: 'khagaria', stock: 25 }
    ]
  },
  {
    id: 'fruit-4',
    name_en: 'Mango',
    name_hi: 'Mango',
    description: 'Fresh seasonal mangoes',
    brand: 'Local Farmer',
    category_id: 'cat-1',
    mrp: 90,
    price: 80,
    stock_qty: 60,
    unit: 'kg',
    pack_size: '1 kg',
    is_veg: true,
    delivery_mode: 'quick',
    image: 'https://firebasestorage.googleapis.com/v0/b/freshoz-fresh-fast.firebasestorage.app/o/categories%2Ffruits%2Fproducts%2Fmango.webp?alt=media&token=92efb5e8-2a5d-4ed5-a24a-cca2497f4914',
    imageHint: 'seasonal mangoes',
    tags: ['fruit', 'mango', 'seasonal', 'fresh'],
    rating: 4.7,
    rating_count: 200,
    warehouse_stock: [
      { warehouse_id: 'sultanganj', stock: 25 },
      { warehouse_id: 'bhagalpur', stock: 20 },
      { warehouse_id: 'khagaria', stock: 15 }
    ]
  },
  {
    id: 'fruit-5',
    name_en: 'Papaya',
    name_hi: 'Papaya',
    description: 'Fresh ripe papaya',
    brand: 'Local Farmer',
    category_id: 'cat-1',
    mrp: 40,
    price: 35,
    stock_qty: 45,
    unit: 'kg',
    pack_size: '1 kg',
    is_veg: true,
    delivery_mode: 'quick',
    image: 'https://firebasestorage.googleapis.com/v0/b/freshoz-fresh-fast.firebasestorage.app/o/categories%2Ffruits%2Fproducts%2Fpapaya.webp?alt=media&token=2abb10b5-4590-4b47-b30c-191aa715b1b7',
    imageHint: 'ripe papaya',
    tags: ['fruit', 'papaya', 'ripe', 'fresh'],
    rating: 4.3,
    rating_count: 110,
    warehouse_stock: [
      { warehouse_id: 'sultanganj', stock: 20 },
      { warehouse_id: 'bhagalpur', stock: 15 },
      { warehouse_id: 'khagaria', stock: 10 }
    ]
  },
  {
    id: 'fruit-6',
    name_en: 'Guava',
    name_hi: 'Guava',
    description: 'Fresh green guavas',
    brand: 'Local Farmer',
    category_id: 'cat-1',
    mrp: 50,
    price: 45,
    stock_qty: 55,
    unit: 'kg',
    pack_size: '1 kg',
    is_veg: true,
    delivery_mode: 'quick',
    image: 'https://firebasestorage.googleapis.com/v0/b/freshoz-fresh-fast.firebasestorage.app/o/categories%2Ffruits%2Fproducts%2Fguava.webp?alt=media&token=5ed97f82-6418-47e7-a91b-1516b47ee1ba',
    imageHint: 'green guavas',
    tags: ['fruit', 'guava', 'fresh', 'green'],
    rating: 4.2,
    rating_count: 95,
    warehouse_stock: [
      { warehouse_id: 'sultanganj', stock: 25 },
      { warehouse_id: 'bhagalpur', stock: 20 },
      { warehouse_id: 'khagaria', stock: 10 }
    ]
  },
  {
    id: 'fruit-7',
    name_en: 'Pomegranate',
    name_hi: 'Pomegranate',
    description: 'Fresh pomegranates',
    brand: 'Local Farmer',
    category_id: 'cat-1',
    mrp: 100,
    price: 90,
    stock_qty: 40,
    unit: 'kg',
    pack_size: '1 kg',
    is_veg: true,
    delivery_mode: 'quick',
    image: 'https://firebasestorage.googleapis.com/v0/b/freshoz-fresh-fast.firebasestorage.app/o/categories%2Ffruits%2Fproducts%2Fpomigranet.webp?alt=media&token=80d3841c-18cc-4611-9805-2e55cc5f5487',
    imageHint: 'fresh pomegranates',
    tags: ['fruit', 'pomegranate', 'fresh', 'red'],
    rating: 4.5,
    rating_count: 120,
    warehouse_stock: [
      { warehouse_id: 'sultanganj', stock: 18 },
      { warehouse_id: 'bhagalpur', stock: 12 },
      { warehouse_id: 'khagaria', stock: 10 }
    ]
  },
  {
    id: 'fruit-8',
    name_en: 'Grapes',
    name_hi: 'Grapes',
    description: 'Fresh black grapes',
    brand: 'Local Farmer',
    category_id: 'cat-1',
    mrp: 70,
    price: 65,
    stock_qty: 35,
    unit: 'kg',
    pack_size: '500 g',
    is_veg: true,
    delivery_mode: 'quick',
    image: 'https://firebasestorage.googleapis.com/v0/b/freshoz-fresh-fast.firebasestorage.app/o/categories%2Ffruits%2Fproducts%2Fgrapes2.webp?alt=media&token=2c5f70f1-0c50-4de5-895b-287c6dcecadb',
    imageHint: 'black grapes',
    tags: ['fruit', 'grapes', 'black', 'fresh'],
    rating: 4.4,
    rating_count: 100,
    warehouse_stock: [
      { warehouse_id: 'sultanganj', stock: 15 },
      { warehouse_id: 'bhagalpur', stock: 12 },
      { warehouse_id: 'khagaria', stock: 8 }
    ]
  },
  {
    id: 'fruit-9',
    name_en: 'Watermelon',
    name_hi: 'Watermelon',
    description: 'Fresh watermelon',
    brand: 'Local Farmer',
    category_id: 'cat-1',
    mrp: 30,
    price: 25,
    stock_qty: 25,
    unit: 'piece',
    pack_size: '1 piece (approx 3kg)',
    is_veg: true,
    delivery_mode: 'quick',
    image: 'https://picsum.photos/seed/fruit-9/400/400',
    imageHint: 'fresh watermelon',
    tags: ['fruit', 'watermelon', 'fresh', 'summer'],
    rating: 4.6,
    rating_count: 150,
    warehouse_stock: [
      { warehouse_id: 'sultanganj', stock: 10 },
      { warehouse_id: 'bhagalpur', stock: 8 },
      { warehouse_id: 'khagaria', stock: 7 }
    ]
  },
  {
    id: 'fruit-10',
    name_en: 'Muskmelon',
    name_hi: 'Muskmelon',
    description: 'Fresh muskmelon',
    brand: 'Local Farmer',
    category_id: 'cat-1',
    mrp: 35,
    price: 30,
    stock_qty: 30,
    unit: 'piece',
    pack_size: '1 piece (approx 1kg)',
    is_veg: true,
    delivery_mode: 'quick',
    image: 'https://picsum.photos/seed/fruit-10/400/400',
    imageHint: 'fresh muskmelon',
    tags: ['fruit', 'muskmelon', 'fresh', 'summer'],
    rating: 4.3,
    rating_count: 90,
    warehouse_stock: [
      { warehouse_id: 'sultanganj', stock: 12 },
      { warehouse_id: 'bhagalpur', stock: 10 },
      { warehouse_id: 'khagaria', stock: 8 }
    ]
  },
  {
    id: 'fruit-11',
    name_en: 'Pineapple',
    name_hi: 'Pineapple',
    description: 'Fresh pineapple',
    brand: 'Local Farmer',
    category_id: 'cat-1',
    mrp: 45,
    price: 40,
    stock_qty: 20,
    unit: 'piece',
    pack_size: '1 piece',
    is_veg: true,
    delivery_mode: 'quick',
    image: 'https://firebasestorage.googleapis.com/v0/b/freshoz-fresh-fast.firebasestorage.app/o/categories%2Ffruits%2Fproducts%2Fpineapple.webp?alt=media&token=0115373d-171c-438d-b57f-7656380a8bad',
    imageHint: 'fresh pineapple',
    tags: ['fruit', 'pineapple', 'fresh', 'tropical'],
    rating: 4.4,
    rating_count: 80,
    warehouse_stock: [
      { warehouse_id: 'sultanganj', stock: 8 },
      { warehouse_id: 'bhagalpur', stock: 7 },
      { warehouse_id: 'khagaria', stock: 5 }
    ]
  },
  {
    id: 'fruit-12',
    name_en: 'Custard Apple',
    name_hi: 'Custard Apple',
    description: 'Fresh custard apple',
    brand: 'Local Farmer',
    category_id: 'cat-1',
    mrp: 80,
    price: 75,
    stock_qty: 25,
    unit: 'kg',
    pack_size: '500 g',
    is_veg: true,
    delivery_mode: 'quick',
    image: 'https://picsum.photos/seed/fruit-12/400/400',
    imageHint: 'custard apple',
    tags: ['fruit', 'custard apple', 'sitafal', 'fresh'],
    rating: 4.5,
    rating_count: 70,
    warehouse_stock: [
      { warehouse_id: 'sultanganj', stock: 10 },
      { warehouse_id: 'bhagalpur', stock: 8 },
      { warehouse_id: 'khagaria', stock: 7 }
    ]
  },
  {
    id: 'fruit-13',
    name_en: 'Sapota',
    name_hi: 'Sapota',
    description: 'Fresh sapota (chikoo)',
    brand: 'Local Farmer',
    category_id: 'cat-1',
    mrp: 60,
    price: 55,
    stock_qty: 35,
    unit: 'kg',
    pack_size: '500 g',
    is_veg: true,
    delivery_mode: 'quick',
    image: 'https://picsum.photos/seed/fruit-13/400/400',
    imageHint: 'fresh sapota',
    tags: ['fruit', 'sapota', 'chikoo', 'fresh'],
    rating: 4.3,
    rating_count: 85,
    warehouse_stock: [
      { warehouse_id: 'sultanganj', stock: 15 },
      { warehouse_id: 'bhagalpur', stock: 12 },
      { warehouse_id: 'khagaria', stock: 8 }
    ]
  },
  {
    id: 'fruit-14',
    name_en: 'Litchi',
    name_hi: 'Litchi',
    description: 'Fresh litchi',
    brand: 'Local Farmer',
    category_id: 'cat-1',
    mrp: 90,
    price: 85,
    stock_qty: 30,
    unit: 'kg',
    pack_size: '500 g',
    is_veg: true,
    delivery_mode: 'quick',
    image: 'https://picsum.photos/seed/fruit-14/400/400',
    imageHint: 'fresh litchi',
    tags: ['fruit', 'litchi', 'fresh', 'seasonal'],
    rating: 4.6,
    rating_count: 110,
    warehouse_stock: [
      { warehouse_id: 'sultanganj', stock: 12 },
      { warehouse_id: 'bhagalpur', stock: 10 },
      { warehouse_id: 'khagaria', stock: 8 }
    ]
  },
  {
    id: 'fruit-15',
    name_en: 'Pear',
    name_hi: 'Pear',
    description: 'Fresh pears',
    brand: 'Local Farmer',
    category_id: 'cat-1',
    mrp: 70,
    price: 65,
    stock_qty: 40,
    unit: 'kg',
    pack_size: '1 kg',
    is_veg: true,
    delivery_mode: 'quick',
    image: 'https://picsum.photos/seed/fruit-15/400/400',
    imageHint: 'fresh pears',
    tags: ['fruit', 'pear', 'fresh'],
    rating: 4.2,
    rating_count: 75,
    warehouse_stock: [
      { warehouse_id: 'sultanganj', stock: 18 },
      { warehouse_id: 'bhagalpur', stock: 12 },
      { warehouse_id: 'khagaria', stock: 10 }
    ]
  },
  {
    id: 'fruit-16',
    name_en: 'Plum',
    name_hi: 'Plum',
    description: 'Fresh plums',
    brand: 'Local Farmer',
    category_id: 'cat-1',
    mrp: 85,
    price: 80,
    stock_qty: 28,
    unit: 'kg',
    pack_size: '500 g',
    is_veg: true,
    delivery_mode: 'quick',
    image: 'https://picsum.photos/seed/fruit-16/400/400',
    imageHint: 'fresh plums',
    tags: ['fruit', 'plum', 'fresh'],
    rating: 4.3,
    rating_count: 65,
    warehouse_stock: [
      { warehouse_id: 'sultanganj', stock: 12 },
      { warehouse_id: 'bhagalpur', stock: 9 },
      { warehouse_id: 'khagaria', stock: 7 }
    ]
  },
  {
    id: 'fruit-17',
    name_en: 'Kiwi',
    name_hi: 'Kiwi',
    description: 'Fresh kiwis',
    brand: 'Local Farmer',
    category_id: 'cat-1',
    mrp: 150,
    price: 140,
    stock_qty: 22,
    unit: 'dozen',
    pack_size: '6 pieces',
    is_veg: true,
    delivery_mode: 'quick',
    image: 'https://firebasestorage.googleapis.com/v0/b/freshoz-fresh-fast.firebasestorage.app/o/categories%2Ffruits%2Fproducts%2Fkiwi.webp?alt=media&token=b5732d71-0dd6-412d-8e5d-27b9340d80e3',
    imageHint: 'fresh kiwis',
    tags: ['fruit', 'kiwi', 'fresh', 'imported'],
    rating: 4.5,
    rating_count: 90,
    warehouse_stock: [
      { warehouse_id: 'sultanganj', stock: 9 },
      { warehouse_id: 'bhagalpur', stock: 7 },
      { warehouse_id: 'khagaria', stock: 6 }
    ]
  },
  {
    id: 'fruit-18',
    name_en: 'Strawberry',
    name_hi: 'Strawberry',
    description: 'Fresh strawberries',
    brand: 'Local Farmer',
    category_id: 'cat-1',
    mrp: 120,
    price: 110,
    stock_qty: 18,
    unit: 'box',
    pack_size: '250 g',
    is_veg: true,
    delivery_mode: 'quick',
    image: 'https://firebasestorage.googleapis.com/v0/b/freshoz-fresh-fast.firebasestorage.app/o/categories%2Ffruits%2Fproducts%2Fstrawberry.webp?alt=media&token=3eff20d6-7c31-4686-a9e8-6ae5ec8a7853',
    imageHint: 'fresh strawberries',
    tags: ['fruit', 'strawberry', 'fresh', 'seasonal'],
    rating: 4.6,
    rating_count: 85,
    warehouse_stock: [
      { warehouse_id: 'sultanganj', stock: 7 },
      { warehouse_id: 'bhagalpur', stock: 6 },
      { warehouse_id: 'khagaria', stock: 5 }
    ]
  },
  {
    id: 'fruit-19',
    name_en: 'Cherry',
    name_hi: 'Cherry',
    description: 'Fresh cherries',
    brand: 'Local Farmer',
    category_id: 'cat-1',
    mrp: 200,
    price: 185,
    stock_qty: 15,
    unit: 'kg',
    pack_size: '250 g',
    is_veg: true,
    delivery_mode: 'quick',
    image: 'https://picsum.photos/seed/fruit-19/400/400',
    imageHint: 'fresh cherries',
    tags: ['fruit', 'cherry', 'fresh', 'premium'],
    rating: 4.7,
    rating_count: 70,
    warehouse_stock: [
      { warehouse_id: 'sultanganj', stock: 6 },
      { warehouse_id: 'bhagalpur', stock: 5 },
      { warehouse_id: 'khagaria', stock: 4 }
    ]
  },
  {
    id: 'fruit-20',
    name_en: 'Coconut',
    name_hi: 'Coconut',
    description: 'Fresh coconut',
    brand: 'Local Farmer',
    category_id: 'cat-1',
    mrp: 35,
    price: 30,
    stock_qty: 50,
    unit: 'piece',
    pack_size: '1 piece',
    is_veg: true,
    delivery_mode: 'quick',
    image: 'https://firebasestorage.googleapis.com/v0/b/freshoz-fresh-fast.firebasestorage.app/o/categories%2Ffruits%2Fproducts%2Fcoconut2.webp?alt=media&token=65754862-fb9c-461c-8f14-c2554fb80eba',
    imageHint: 'fresh coconut',
    tags: ['fruit', 'coconut', 'fresh', 'nariyal'],
    rating: 4.4,
    rating_count: 120,
    warehouse_stock: [
      { warehouse_id: 'sultanganj', stock: 20 },
      { warehouse_id: 'bhagalpur', stock: 18 },
      { warehouse_id: 'khagaria', stock: 12 }
    ]
  },
  {
    id: 'fruit-21',
    name_en: 'Pomegranate Seeds',
    name_hi: 'Pomegranate Seeds',
    description: 'Fresh pomegranate seeds',
    brand: 'Local Farmer',
    category_id: 'cat-1',
    mrp: 130,
    price: 120,
    stock_qty: 25,
    unit: 'pack',
    pack_size: '200 g',
    is_veg: true,
    delivery_mode: 'quick',
    image: 'https://picsum.photos/seed/fruit-21/400/400',
    imageHint: 'pomegranate seeds',
    tags: ['fruit', 'pomegranate', 'seeds', 'fresh'],
    rating: 4.5,
    rating_count: 95,
    warehouse_stock: [
      { warehouse_id: 'sultanganj', stock: 10 },
      { warehouse_id: 'bhagalpur', stock: 8 },
      { warehouse_id: 'khagaria', stock: 7 }
    ]
  },
  {
    id: 'fruit-22',
    name_en: 'Mixed Fruit Basket',
    name_hi: 'Mixed Fruit Basket',
    description: 'Assorted fresh fruits basket',
    brand: 'Local Farmer',
    category_id: 'cat-1',
    mrp: 250,
    price: 225,
    stock_qty: 20,
    unit: 'basket',
    pack_size: '1 basket (approx 2kg)',
    is_veg: true,
    delivery_mode: 'quick',
    image: 'https://picsum.photos/seed/fruit-22/400/400',
    imageHint: 'fruit basket',
    tags: ['fruit', 'mixed', 'basket', 'fresh'],
    rating: 4.6,
    rating_count: 110,
    warehouse_stock: [
      { warehouse_id: 'sultanganj', stock: 8 },
      { warehouse_id: 'bhagalpur', stock: 7 },
      { warehouse_id: 'khagaria', stock: 5 }
    ]
  },
  {
    id: 'fruit-23',
    name_en: 'Seasonal Fruit Box',
    name_hi: 'Seasonal Fruit Box',
    description: 'Box of seasonal fresh fruits',
    brand: 'Local Farmer',
    category_id: 'cat-1',
    mrp: 180,
    price: 160,
    stock_qty: 30,
    unit: 'box',
    pack_size: '1 box (approx 1.5kg)',
    is_veg: true,
    delivery_mode: 'quick',
    image: 'https://picsum.photos/seed/fruit-23/400/400',
    imageHint: 'seasonal fruits',
    tags: ['fruit', 'seasonal', 'box', 'fresh'],
    rating: 4.4,
    rating_count: 100,
    warehouse_stock: [
      { warehouse_id: 'sultanganj', stock: 12 },
      { warehouse_id: 'bhagalpur', stock: 10 },
      { warehouse_id: 'khagaria', stock: 8 }
    ]
  },
  {
    id: 'fruit-24',
    name_en: 'Fruit Salad Pack',
    name_hi: 'Fruit Salad Pack',
    description: 'Ready to eat fruit salad',
    brand: 'Local Farmer',
    category_id: 'cat-1',
    mrp: 100,
    price: 90,
    stock_qty: 40,
    unit: 'pack',
    pack_size: '500 g',
    is_veg: true,
    delivery_mode: 'quick',
    image: 'https://picsum.photos/seed/fruit-24/400/400',
    imageHint: 'fruit salad',
    tags: ['fruit', 'salad', 'ready to eat', 'fresh'],
    rating: 4.3,
    rating_count: 130,
    warehouse_stock: [
      { warehouse_id: 'sultanganj', stock: 18 },
      { warehouse_id: 'bhagalpur', stock: 12 },
      { warehouse_id: 'khagaria', stock: 10 }
    ]
  },
  {
    id: 'fruit-25',
    name_en: 'Dry Fruits Mix',
    name_hi: 'Dry Fruits Mix',
    description: 'Assorted dry fruits mix',
    brand: 'Local Farmer',
    category_id: 'cat-1',
    mrp: 300,
    price: 280,
    stock_qty: 35,
    unit: 'pack',
    pack_size: '250 g',
    is_veg: true,
    delivery_mode: 'quick',
    image: 'https://picsum.photos/seed/fruit-25/400/400',
    imageHint: 'dry fruits',
    tags: ['fruit', 'dry fruits', 'mixed', 'nuts'],
    rating: 4.7,
    rating_count: 150,
    warehouse_stock: [
      { warehouse_id: 'sultanganj', stock: 15 },
      { warehouse_id: 'bhagalpur', stock: 12 },
      { warehouse_id: 'khagaria', stock: 8 }
    ]
  }
];