import { Product } from '../../types';

export const VEGETABLES_PRODUCTS: Product[] = [
  {
    id: 'veg-1',
    name_en: 'Fresh Tomatoes',
    name_hi: 'Fresh Tomatoes',
    description: 'Fresh red tomatoes from local farms',
    brand: 'Local Farmer',
    category_id: 'cat-1',
    mrp: 40,
    price: 35,
    stock_qty: 100,
    unit: 'kg',
    image: 'https://firebasestorage.googleapis.com/v0/b/freshoz-fresh-fast.firebasestorage.app/o/categories%2Fvegetables%2Fproducts%2Ftomato.webp?alt=media&token=8b5bae88-9422-485c-bdb8-f47364321f95',
    imageHint: 'fresh tomatoes',
    tags: ['vegetable', 'tomato', 'fresh', 'local'],
    rating: 4.2,
    rating_count: 150,
    warehouse_stock: [
      { warehouse_id: 'sultanganj', stock: 40 },
      { warehouse_id: 'bhagalpur', stock: 35 },
      { warehouse_id: 'khagaria', stock: 25 }
    ],
    variants: [
        { id: 'veg-1-1', pack_size: '250 g', mrp: 10, price: 9, stock_qty: 100 },
        { id: 'veg-1-2', pack_size: '500 g', mrp: 20, price: 18, stock_qty: 50 },
        { id: 'veg-1-3', pack_size: '1 kg', mrp: 40, price: 35, stock_qty: 30 },
    ]
  },
  {
    id: 'veg-2',
    name_en: 'Potatoes',
    name_hi: 'Potatoes',
    description: 'Fresh potatoes for daily cooking',
    brand: 'Local Farmer',
    category_id: 'cat-1',
    mrp: 25,
    price: 20,
    stock_qty: 200,
    unit: 'kg',
    image: 'https://firebasestorage.googleapis.com/v0/b/freshoz-fresh-fast.firebasestorage.app/o/categories%2Fvegetables%2Fproducts%2Fpotato.webp?alt=media&token=09d9dec8-44ed-417a-8bad-cbd5d1bd4f7c',
    imageHint: 'fresh potatoes',
    tags: ['vegetable', 'potato', 'staple', 'fresh'],
    rating: 4.3,
    rating_count: 180,
    warehouse_stock: [
      { warehouse_id: 'sultanganj', stock: 80 },
      { warehouse_id: 'bhagalpur', stock: 70 },
      { warehouse_id: 'khagaria', stock: 50 }
    ],
    variants: [
        { id: 'veg-2-1', pack_size: '1 kg', mrp: 25, price: 20, stock_qty: 100 },
        { id: 'veg-2-2', pack_size: '5 kg', mrp: 125, price: 95, stock_qty: 20 },
    ]
  },
  {
    id: 'veg-3',
    name_en: 'Onions',
    name_hi: 'Onions',
    description: 'Fresh onions for cooking',
    brand: 'Local Farmer',
    category_id: 'cat-1',
    mrp: 30,
    price: 25,
    stock_qty: 150,
    unit: 'kg',
    image: 'https://firebasestorage.googleapis.com/v0/b/freshoz-fresh-fast.firebasestorage.app/o/categories%2Fvegetables%2Fproducts%2Fonion.webp?alt=media&token=76cbca61-7b3a-477e-9ad7-67bfdddea852',
    imageHint: 'fresh onions',
    tags: ['vegetable', 'onion', 'essential', 'fresh'],
    rating: 4.1,
    rating_count: 160,
    warehouse_stock: [
      { warehouse_id: 'sultanganj', stock: 60 },
      { warehouse_id: 'bhagalpur', stock: 50 },
      { warehouse_id: 'khagaria', stock: 40 }
    ],
    variants: [
        { id: 'veg-3-1', pack_size: '500 g', mrp: 15, price: 13, stock_qty: 80 },
        { id: 'veg-3-2', pack_size: '1 kg', mrp: 30, price: 25, stock_qty: 70 },
    ]
  },
  {
    id: 'veg-4',
    name_en: 'Cauliflower',
    name_hi: 'Cauliflower',
    description: 'Fresh cauliflower with green leaves',
    brand: 'Local Farmer',
    category_id: 'cat-1',
    mrp: 35,
    price: 30,
    stock_qty: 80,
    unit: 'piece',
    pack_size: '1 piece (approx 500g)',
    is_veg: true,
    delivery_mode: 'quick',
    image: 'https://firebasestorage.googleapis.com/v0/b/freshoz-fresh-fast.firebasestorage.app/o/categories%2Fvegetables%2Fproducts%2Fcauliflower.webp?alt=media&token=e1928a31-f3d6-4bc2-81aa-8cd17cd049ca',
    imageHint: 'fresh cauliflower',
    tags: ['vegetable', 'cauliflower', 'fresh', 'green'],
    rating: 4.4,
    rating_count: 120,
    warehouse_stock: [
      { warehouse_id: 'sultanganj', stock: 30 },
      { warehouse_id: 'bhagalpur', stock: 25 },
      { warehouse_id: 'khagaria', stock: 25 }
    ]
  },
  {
    id: 'veg-5',
    name_en: 'Cabbage',
    name_hi: 'Cabbage',
    description: 'Fresh green cabbage',
    brand: 'Local Farmer',
    category_id: 'cat-1',
    mrp: 20,
    price: 15,
    stock_qty: 60,
    unit: 'piece',
    pack_size: '1 piece (approx 500g)',
    is_veg: true,
    delivery_mode: 'quick',
    image: 'https://picsum.photos/seed/veg-5/400/400',
    imageHint: 'green cabbage',
    tags: ['vegetable', 'cabbage', 'fresh', 'green'],
    rating: 4.0,
    rating_count: 90,
    warehouse_stock: [
      { warehouse_id: 'sultanganj', stock: 25 },
      { warehouse_id: 'bhagalpur', stock: 20 },
      { warehouse_id: 'khagaria', stock: 15 }
    ]
  },
  {
    id: 'veg-6',
    name_en: 'Brinjal',
    name_hi: 'Brinjal',
    description: 'Fresh purple brinjal',
    brand: 'Local Farmer',
    category_id: 'cat-1',
    mrp: 45,
    price: 40,
    stock_qty: 70,
    unit: 'kg',
    pack_size: '1 kg',
    is_veg: true,
    delivery_mode: 'quick',
    image: 'https://picsum.photos/seed/veg-6/400/400',
    imageHint: 'purple brinjal',
    tags: ['vegetable', 'brinjal', 'eggplant', 'fresh'],
    rating: 4.2,
    rating_count: 110,
    warehouse_stock: [
      { warehouse_id: 'sultanganj', stock: 30 },
      { warehouse_id: 'bhagalpur', stock: 25 },
      { warehouse_id: 'khagaria', stock: 15 }
    ]
  },
  {
    id: 'veg-7',
    name_en: 'Lady Finger',
    name_hi: 'Lady Finger',
    description: 'Fresh green lady finger',
    brand: 'Local Farmer',
    category_id: 'cat-1',
    mrp: 50,
    price: 45,
    stock_qty: 55,
    unit: 'kg',
    pack_size: '1 kg',
    is_veg: true,
    delivery_mode: 'quick',
    image: 'https://picsum.photos/seed/veg-7/400/400',
    imageHint: 'green lady finger',
    tags: ['vegetable', 'lady finger', 'okra', 'fresh'],
    rating: 4.3,
    rating_count: 95,
    warehouse_stock: [
      { warehouse_id: 'sultanganj', stock: 25 },
      { warehouse_id: 'bhagalpur', stock: 20 },
      { warehouse_id: 'khagaria', stock: 10 }
    ]
  },
  {
    id: 'veg-8',
    name_en: 'Spinach',
    name_hi: 'Spinach',
    description: 'Fresh green spinach leaves',
    brand: 'Local Farmer',
    category_id: 'cat-1',
    mrp: 25,
    price: 20,
    stock_qty: 90,
    unit: 'bunch',
    pack_size: '1 bunch (approx 250g)',
    is_veg: true,
    delivery_mode: 'quick',
    image: 'https://picsum.photos/seed/veg-8/400/400',
    imageHint: 'green spinach',
    tags: ['vegetable', 'spinach', 'green', 'leafy'],
    rating: 4.5,
    rating_count: 130,
    warehouse_stock: [
      { warehouse_id: 'sultanganj', stock: 40 },
      { warehouse_id: 'bhagalpur', stock: 30 },
      { warehouse_id: 'khagaria', stock: 20 }
    ]
  },
  {
    id: 'veg-9',
    name_en: 'Green Chilies',
    name_hi: 'Green Chilies',
    description: 'Fresh green chilies',
    brand: 'Local Farmer',
    category_id: 'cat-1',
    mrp: 60,
    price: 55,
    stock_qty: 45,
    unit: 'kg',
    pack_size: '250 g',
    is_veg: true,
    delivery_mode: 'quick',
    image: 'https://picsum.photos/seed/veg-9/400/400',
    imageHint: 'green chilies',
    tags: ['vegetable', 'chilies', 'spicy', 'fresh'],
    rating: 4.1,
    rating_count: 85,
    warehouse_stock: [
      { warehouse_id: 'sultanganj', stock: 20 },
      { warehouse_id: 'bhagalpur', stock: 15 },
      { warehouse_id: 'khagaria', stock: 10 }
    ]
  },
  {
    id: 'veg-10',
    name_en: 'Capsicum',
    name_hi: 'Capsicum',
    description: 'Fresh green capsicum',
    brand: 'Local Farmer',
    category_id: 'cat-1',
    mrp: 70,
    price: 65,
    stock_qty: 40,
    unit: 'kg',
    pack_size: '1 kg',
    is_veg: true,
    delivery_mode: 'quick',
    image: 'https://firebasestorage.googleapis.com/v0/b/freshoz-fresh-fast.firebasestorage.app/o/categories%2Fvegetables%2Fproducts%2Fcapsicum.webp?alt=media&token=d8d8c04e-7e7f-409d-8c96-f8a53b7fc739',
    imageHint: 'green capsicum',
    tags: ['vegetable', 'capsicum', 'bell pepper', 'fresh'],
    rating: 4.2,
    rating_count: 75,
    warehouse_stock: [
      { warehouse_id: 'sultanganj', stock: 18 },
      { warehouse_id: 'bhagalpur', stock: 12 },
      { warehouse_id: 'khagaria', stock: 10 }
    ]
  },
  {
    id: 'veg-11',
    name_en: 'Carrot',
    name_hi: 'Carrot',
    description: 'Fresh orange carrots',
    brand: 'Local Farmer',
    category_id: 'cat-1',
    mrp: 40,
    price: 35,
    stock_qty: 65,
    unit: 'kg',
    pack_size: '1 kg',
    is_veg: true,
    delivery_mode: 'quick',
    image: 'https://firebasestorage.googleapis.com/v0/b/freshoz-fresh-fast.firebasestorage.app/o/categories%2Fvegetables%2Fproducts%2Fcarrot.webp?alt=media&token=dd8edca7-7399-40b4-b2b1-38bb4ba1ec85',
    imageHint: 'orange carrots',
    tags: ['vegetable', 'carrot', 'orange', 'fresh'],
    rating: 4.4,
    rating_count: 100,
    warehouse_stock: [
      { warehouse_id: 'sultanganj', stock: 30 },
      { warehouse_id: 'bhagalpur', stock: 20 },
      { warehouse_id: 'khagaria', stock: 15 }
    ]
  },
  {
    id: 'veg-12',
    name_en: 'Radish',
    name_hi: 'Radish',
    description: 'Fresh white radish',
    brand: 'Local Farmer',
    category_id: 'cat-1',
    mrp: 30,
    price: 25,
    stock_qty: 50,
    unit: 'kg',
    pack_size: '1 kg',
    is_veg: true,
    delivery_mode: 'quick',
    image: 'https://picsum.photos/seed/veg-12/400/400',
    imageHint: 'white radish',
    tags: ['vegetable', 'radish', 'white', 'fresh'],
    rating: 4.0,
    rating_count: 70,
    warehouse_stock: [
      { warehouse_id: 'sultanganj', stock: 25 },
      { warehouse_id: 'bhagalpur', stock: 15 },
      { warehouse_id: 'khagaria', stock: 10 }
    ]
  },
  {
    id: 'veg-13',
    name_en: 'Cucumber',
    name_hi: 'Cucumber',
    description: 'Fresh green cucumbers',
    brand: 'Local Farmer',
    category_id: 'cat-1',
    mrp: 35,
    price: 30,
    stock_qty: 75,
    unit: 'kg',
    pack_size: '1 kg',
    is_veg: true,
    delivery_mode: 'quick',
    image: 'https://firebasestorage.googleapis.com/v0/b/freshoz-fresh-fast.firebasestorage.app/o/categories%2Fvegetables%2Fproducts%2Fcucumber.webp?alt=media&token=5cb45e9b-cf48-42ce-8173-9e80aa36777c',
    imageHint: 'green cucumbers',
    tags: ['vegetable', 'cucumber', 'fresh', 'salad'],
    rating: 4.3,
    rating_count: 110,
    warehouse_stock: [
      { warehouse_id: 'sultanganj', stock: 35 },
      { warehouse_id: 'bhagalpur', stock: 25 },
      { warehouse_id: 'khagaria', stock: 15 }
    ]
  },
  {
    id: 'veg-14',
    name_en: 'Bottle Gourd',
    name_hi: 'Bottle Gourd',
    description: 'Fresh bottle gourd',
    brand: 'Local Farmer',
    category_id: 'cat-1',
    mrp: 25,
    price: 20,
    stock_qty: 60,
    unit: 'kg',
    pack_size: '1 kg',
    is_veg: true,
    delivery_mode: 'quick',
    image: 'https://picsum.photos/seed/veg-14/400/400',
    imageHint: 'bottle gourd',
    tags: ['vegetable', 'bottle gourd', 'lauki', 'fresh'],
    rating: 4.1,
    rating_count: 80,
    warehouse_stock: [
      { warehouse_id: 'sultanganj', stock: 30 },
      { warehouse_id: 'bhagalpur', stock: 20 },
      { warehouse_id: 'khagaria', stock: 10 }
    ]
  },
  {
    id: 'veg-15',
    name_en: 'Bitter Gourd',
    name_hi: 'Bitter Gourd',
    description: 'Fresh bitter gourd',
    brand: 'Local Farmer',
    category_id: 'cat-1',
    mrp: 45,
    price: 40,
    stock_qty: 35,
    unit: 'kg',
    pack_size: '1 kg',
    is_veg: true,
    delivery_mode: 'quick',
    image: 'https://picsum.photos/seed/veg-15/400/400',
    imageHint: 'bitter gourd',
    tags: ['vegetable', 'bitter gourd', 'karela', 'fresh'],
    rating: 3.9,
    rating_count: 60,
    warehouse_stock: [
      { warehouse_id: 'sultanganj', stock: 15 },
      { warehouse_id: 'bhagalpur', stock: 12 },
      { warehouse_id: 'khagaria', stock: 8 }
    ]
  },
  {
    id: 'veg-16',
    name_en: 'Pumpkin',
    name_hi: 'Pumpkin',
    description: 'Fresh yellow pumpkin',
    brand: 'Local Farmer',
    category_id: 'cat-1',
    mrp: 30,
    price: 25,
    stock_qty: 45,
    unit: 'kg',
    pack_size: '1 kg',
    is_veg: true,
    delivery_mode: 'quick',
    image: 'https://picsum.photos/seed/veg-16/400/400',
    imageHint: 'yellow pumpkin',
    tags: ['vegetable', 'pumpkin', 'yellow', 'fresh'],
    rating: 4.2,
    rating_count: 75,
    warehouse_stock: [
      { warehouse_id: 'sultanganj', stock: 20 },
      { warehouse_id: 'bhagalpur', stock: 15 },
      { warehouse_id: 'khagaria', stock: 10 }
    ]
  },
  {
    id: 'veg-17',
    name_en: 'Green Beans',
    name_hi: 'Green Beans',
    description: 'Fresh green beans',
    brand: 'Local Farmer',
    category_id: 'cat-1',
    mrp: 55,
    price: 50,
    stock_qty: 40,
    unit: 'kg',
    pack_size: '1 kg',
    is_veg: true,
    delivery_mode: 'quick',
    image: 'https://picsum.photos/seed/veg-17/400/400',
    imageHint: 'green beans',
    tags: ['vegetable', 'green beans', 'fresh'],
    rating: 4.3,
    rating_count: 85,
    warehouse_stock: [
      { warehouse_id: 'sultanganj', stock: 18 },
      { warehouse_id: 'bhagalpur', stock: 12 },
      { warehouse_id: 'khagaria', stock: 10 }
    ]
  },
  {
    id: 'veg-18',
    name_en: 'Peas',
    name_hi: 'Peas',
    description: 'Fresh green peas',
    brand: 'Local Farmer',
    category_id: 'cat-1',
    mrp: 65,
    price: 60,
    stock_qty: 30,
    unit: 'kg',
    pack_size: '1 kg',
    is_veg: true,
    delivery_mode: 'quick',
    image: 'https://picsum.photos/seed/veg-18/400/400',
    imageHint: 'green peas',
    tags: ['vegetable', 'peas', 'green', 'fresh'],
    rating: 4.4,
    rating_count: 95,
    warehouse_stock: [
      { warehouse_id: 'sultanganj', stock: 12 },
      { warehouse_id: 'bhagalpur', stock: 10 },
      { warehouse_id: 'khagaria', stock: 8 }
    ]
  },
  {
    id: 'veg-19',
    name_en: 'Coriander Leaves',
    name_hi: 'Coriander Leaves',
    description: 'Fresh coriander leaves',
    brand: 'Local Farmer',
    category_id: 'cat-1',
    mrp: 20,
    price: 15,
    stock_qty: 85,
    unit: 'bunch',
    pack_size: '1 bunch',
    is_veg: true,
    delivery_mode: 'quick',
    image: 'https://picsum.photos/seed/veg-19/400/400',
    imageHint: 'coriander leaves',
    tags: ['vegetable', 'coriander', 'dhaniya', 'fresh'],
    rating: 4.5,
    rating_count: 140,
    warehouse_stock: [
      { warehouse_id: 'sultanganj', stock: 40 },
      { warehouse_id: 'bhagalpur', stock: 30 },
      { warehouse_id: 'khagaria', stock: 15 }
    ]
  },
  {
    id: 'veg-20',
    name_en: 'Mint Leaves',
    name_hi: 'Mint Leaves',
    description: 'Fresh mint leaves',
    brand: 'Local Farmer',
    category_id: 'cat-1',
    mrp: 25,
    price: 20,
    stock_qty: 70,
    unit: 'bunch',
    pack_size: '1 bunch',
    is_veg: true,
    delivery_mode: 'quick',
    image: 'https://picsum.photos/seed/veg-20/400/400',
    imageHint: 'mint leaves',
    tags: ['vegetable', 'mint', 'pudina', 'fresh'],
    rating: 4.4,
    rating_count: 120,
    warehouse_stock: [
      { warehouse_id: 'sultanganj', stock: 30 },
      { warehouse_id: 'bhagalpur', stock: 25 },
      { warehouse_id: 'khagaria', stock: 15 }
    ]
  },
  {
    id: 'veg-21',
    name_en: 'Lemon',
    name_hi: 'Lemon',
    description: 'Fresh lemons',
    brand: 'Local Farmer',
    category_id: 'cat-1',
    mrp: 50,
    price: 45,
    stock_qty: 95,
    unit: 'dozen',
    pack_size: '12 pieces',
    is_veg: true,
    delivery_mode: 'quick',
    image: 'https://firebasestorage.googleapis.com/v0/b/freshoz-fresh-fast.firebasestorage.app/o/categories%2Fvegetables%2Fproducts%2Flemon.webp?alt=media&token=89c83348-9c23-423e-addb-9054b33ec4a4',
    imageHint: 'fresh lemons',
    tags: ['vegetable', 'lemon', 'nimbu', 'fresh'],
    rating: 4.6,
    rating_count: 160,
    warehouse_stock: [
      { warehouse_id: 'sultanganj', stock: 40 },
      { warehouse_id: 'bhagalpur', stock: 35 },
      { warehouse_id: 'khagaria', stock: 20 }
    ]
  },
  {
    id: 'veg-22',
    name_en: 'Ginger',
    name_hi: 'Ginger',
    description: 'Fresh ginger',
    brand: 'Local Farmer',
    category_id: 'cat-1',
    mrp: 80,
    price: 75,
    stock_qty: 55,
    unit: 'kg',
    pack_size: '250 g',
    is_veg: true,
    delivery_mode: 'quick',
    image: 'https://picsum.photos/seed/veg-22/400/400',
    imageHint: 'fresh ginger',
    tags: ['vegetable', 'ginger', 'adrak', 'fresh'],
    rating: 4.3,
    rating_count: 100,
    warehouse_stock: [
      { warehouse_id: 'sultanganj', stock: 25 },
      { warehouse_id: 'bhagalpur', stock: 20 },
      { warehouse_id: 'khagaria', stock: 10 }
    ]
  },
  {
    id: 'veg-23',
    name_en: 'Garlic',
    name_hi: 'Garlic',
    description: 'Fresh garlic',
    brand: 'Local Farmer',
    category_id: 'cat-1',
    mrp: 70,
    price: 65,
    stock_qty: 65,
    unit: 'kg',
    pack_size: '250 g',
    is_veg: true,
    delivery_mode: 'quick',
    image: 'https://picsum.photos/seed/veg-23/400/400',
    imageHint: 'fresh garlic',
    tags: ['vegetable', 'garlic', 'lasun', 'fresh'],
    rating: 4.4,
    rating_count: 110,
    warehouse_stock: [
      { warehouse_id: 'sultanganj', stock: 30 },
      { warehouse_id: 'bhagalpur', stock: 25 },
      { warehouse_id: 'khagaria', stock: 10 }
    ]
  },
  {
    id: 'veg-24',
    name_en: 'Green Papaya',
    name_hi: 'Green Papaya',
    description: 'Fresh green papaya',
    brand: 'Local Farmer',
    category_id: 'cat-1',
    mrp: 35,
    price: 30,
    stock_qty: 40,
    unit: 'kg',
    pack_size: '1 kg',
    is_veg: true,
    delivery_mode: 'quick',
    image: 'https://picsum.photos/seed/veg-24/400/400',
    imageHint: 'green papaya',
    tags: ['vegetable', 'papaya', 'green', 'fresh'],
    rating: 4.1,
    rating_count: 70,
    warehouse_stock: [
      { warehouse_id: 'sultanganj', stock: 18 },
      { warehouse_id: 'bhagalpur', stock: 12 },
      { warehouse_id: 'khagaria', stock: 10 }
    ]
  },
  {
    id: 'veg-25',
    name_en: 'Drumsticks',
    name_hi: 'Drumsticks',
    description: 'Fresh drumsticks',
    brand: 'Local Farmer',
    category_id: 'cat-1',
    mrp: 40,
    price: 35,
    stock_qty: 35,
    unit: 'bunch',
    pack_size: '1 bunch',
    is_veg: true,
    delivery_mode: 'quick',
    image: 'https://firebasestorage.googleapis.com/v0/b/freshoz-fresh-fast.firebasestorage.app/o/categories%2Fvegetables%2Fproducts%2Fdrumstick.webp?alt=media&token=a57d91a6-f449-44e1-964c-b327bb05d852',
    imageHint: 'fresh drumsticks',
    tags: ['vegetable', 'drumsticks', 'fresh'],
    rating: 4.2,
    rating_count: 65,
    warehouse_stock: [
      { warehouse_id: 'sultanganj', stock: 15 },
      { warehouse_id: 'bhagalpur', stock: 12 },
      { warehouse_id: 'khagaria', stock: 8 }
    ]
  }
];

