import { Product } from '../../types';

export const CHICKEN_PRODUCTS: Product[] = [
  {
    id: 'chicken-1',
    name_en: 'Fresh Chicken Curry Cut',
    name_hi: 'Chicken Curry Piece',
    description: 'Fresh chicken curry cuts with bone. Perfect for Indian curries.',
    brand: 'Local Farm',
    category_id: 'cat-5',
    mrp: 220,
    price: 199,
    stock_qty: 25,
    unit: 'kg',
    pack_size: '1 kg',
    is_veg: false,
    delivery_mode: 'quick',
    image: 'https://picsum.photos/seed/chicken-1/400/400',
    imageHint: 'Chicken Curry Cut',
    tags: ['chicken', 'non-veg', 'curry cut', 'fresh'],
    rating: 4.4,
    rating_count: 180,
    warehouse_stock: [
      { warehouse_id: 'sultanganj', stock: 10 },
      { warehouse_id: 'bhagalpur', stock: 0 },
      { warehouse_id: 'khagaria', stock: 0 }
    ]
  },
  {
    id: 'chicken-2',
    name_en: 'Chicken Boneless Breast',
    name_hi: 'Chicken Boneless Seena',
    description: 'Skinless boneless chicken breast. Lean and protein-rich.',
    brand: 'Local Farm',
    category_id: 'cat-5',
    mrp: 280,
    price: 259,
    stock_qty: 18,
    unit: 'kg',
    pack_size: '500 g',
    is_veg: false,
    delivery_mode: 'quick',
    image: 'https://picsum.photos/seed/chicken-2/400/400',
    imageHint: 'Chicken Breast',
    tags: ['chicken', 'non-veg', 'boneless', 'breast', 'protein'],
    rating: 4.5,
    rating_count: 120,
    warehouse_stock: [
      { warehouse_id: 'sultanganj', stock: 7 },
      { warehouse_id: 'bhagalpur', stock: 0 },
      { warehouse_id: 'khagaria', stock: 0 }
    ]
  },
  {
    id: 'chicken-3',
    name_en: 'Chicken Leg Piece',
    name_hi: 'Chicken Leg Piece',
    description: 'Fresh chicken leg pieces with thigh. Great for grilling.',
    brand: 'Local Farm',
    category_id: 'cat-5',
    mrp: 240,
    price: 219,
    stock_qty: 20,
    unit: 'kg',
    pack_size: '1 kg',
    is_veg: false,
    delivery_mode: 'quick',
    image: 'https://picsum.photos/seed/chicken-3/400/400',
    imageHint: 'Chicken Leg',
    tags: ['chicken', 'non-veg', 'leg piece', 'fresh', 'grill'],
    rating: 4.3,
    rating_count: 150,
    warehouse_stock: [
      { warehouse_id: 'sultanganj', stock: 8 },
      { warehouse_id: 'bhagalpur', stock: 0 },
      { warehouse_id: 'khagaria', stock: 0 }
    ]
  },
  {
    id: 'chicken-4',
    name_en: 'Chicken Mince (Keema)',
    name_hi: 'Chicken Mince (Keema)',
    description: 'Freshly minced chicken. Perfect for kebabs and curries.',
    brand: 'Local Farm',
    category_id: 'cat-5',
    mrp: 260,
    price: 239,
    stock_qty: 15,
    unit: 'kg',
    pack_size: '500 g',
    is_veg: false,
    delivery_mode: 'quick',
    image: 'https://picsum.photos/seed/chicken-4/400/400',
    imageHint: 'Chicken Keema',
    tags: ['chicken', 'non-veg', 'mince', 'keema', 'fresh'],
    rating: 4.2,
    rating_count: 95,
    warehouse_stock: [
      { warehouse_id: 'sultanganj', stock: 6 },
      { warehouse_id: 'bhagalpur', stock: 0 },
      { warehouse_id: 'khagaria', stock: 0 }
    ]
  },
  {
    id: 'chicken-5',
    name_en: 'Whole Chicken',
    name_hi: 'Pura Chicken',
    description: 'Fresh whole chicken. Cleaned and ready to cook.',
    brand: 'Local Farm',
    category_id: 'cat-5',
    mrp: 210,
    price: 189,
    stock_qty: 12,
    unit: 'piece',
    pack_size: '1.2-1.5 kg',
    is_veg: false,
    delivery_mode: 'quick',
    image: 'https://picsum.photos/seed/chicken-5/400/400',
    imageHint: 'Whole Chicken',
    tags: ['chicken', 'non-veg', 'whole', 'fresh'],
    rating: 4.4,
    rating_count: 110,
    warehouse_stock: [
      { warehouse_id: 'sultanganj', stock: 5 },
      { warehouse_id: 'bhagalpur', stock: 0 },
      { warehouse_id: 'khagaria', stock: 0 }
    ]
  },
  {
    id: 'chicken-6',
    name_en: 'Chicken Wings',
    name_hi: 'Chicken Daina',
    description: 'Fresh chicken wings. Perfect for starters and snacks.',
    brand: 'Local Farm',
    category_id: 'cat-5',
    mrp: 190,
    price: 175,
    stock_qty: 22,
    unit: 'kg',
    pack_size: '500 g',
    is_veg: false,
    delivery_mode: 'quick',
    image: 'https://picsum.photos/seed/chicken-6/400/400',
    imageHint: 'Chicken Wings',
    tags: ['chicken', 'non-veg', 'wings', 'starters', 'snacks'],
    rating: 4.3,
    rating_count: 85,
    warehouse_stock: [
      { warehouse_id: 'sultanganj', stock: 9 },
      { warehouse_id: 'bhagalpur', stock: 0 },
      { warehouse_id: 'khagaria', stock: 0 }
    ]
  },
  {
    id: 'chicken-7',
    name_en: 'Chicken Liver',
    name_hi: 'Chicken Liver',
    description: 'Fresh chicken liver. Rich in iron and nutrients.',
    brand: 'Local Farm',
    category_id: 'cat-5',
    mrp: 150,
    price: 135,
    stock_qty: 18,
    unit: 'kg',
    pack_size: '500 g',
    is_veg: false,
    delivery_mode: 'quick',
    image: 'https://picsum.photos/seed/chicken-7/400/400',
    imageHint: 'Chicken Liver',
    tags: ['chicken', 'non-veg', 'liver', 'nutritious'],
    rating: 4.1,
    rating_count: 70,
    warehouse_stock: [
      { warehouse_id: 'sultanganj', stock: 7 },
      { warehouse_id: 'bhagalpur', stock: 0 },
      { warehouse_id: 'khagaria', stock: 0 }
    ]
  },
  {
    id: 'chicken-8',
    name_en: 'Chicken Drumsticks',
    name_hi: 'Chicken Drumsticks',
    description: 'Fresh chicken drumsticks. Ideal for frying and curries.',
    brand: 'Local Farm',
    category_id: 'cat-5',
    mrp: 230,
    price: 209,
    stock_qty: 16,
    unit: 'kg',
    pack_size: '1 kg',
    is_veg: false,
    delivery_mode: 'quick',
    image: 'https://picsum.photos/seed/chicken-8/400/400',
    imageHint: 'Chicken Drumsticks',
    tags: ['chicken', 'non-veg', 'drumsticks', 'fresh'],
    rating: 4.4,
    rating_count: 100,
    warehouse_stock: [
      { warehouse_id: 'sultanganj', stock: 6 },
      { warehouse_id: 'bhagalpur', stock: 0 },
      { warehouse_id: 'khagaria', stock: 0 }
    ]
  },
  {
    id: 'chicken-9',
    name_en: 'Chicken Thighs',
    name_hi: 'Chicken Jangha',
    description: 'Fresh chicken thighs. Juicy and flavorful.',
    brand: 'Local Farm',
    category_id: 'cat-5',
    mrp: 225,
    price: 205,
    stock_qty: 14,
    unit: 'kg',
    pack_size: '1 kg',
    is_veg: false,
    delivery_mode: 'quick',
    image: 'https://picsum.photos/seed/chicken-9/400/400',
    imageHint: 'Chicken Thighs',
    tags: ['chicken', 'non-veg', 'thighs', 'fresh', 'juicy'],
    rating: 4.3,
    rating_count: 80,
    warehouse_stock: [
      { warehouse_id: 'sultanganj', stock: 5 },
      { warehouse_id: 'bhagalpur', stock: 0 },
      { warehouse_id: 'khagaria', stock: 0 }
    ]
  },
  {
    id: 'chicken-10',
    name_en: 'Chicken Sausages',
    name_hi: 'Chicken Lachhha',
    description: 'Ready to cook chicken sausages. Great for breakfast.',
    brand: 'Local Farm',
    category_id: 'cat-5',
    mrp: 180,
    price: 165,
    stock_qty: 20,
    unit: 'pack',
    pack_size: '400 g',
    is_veg: false,
    delivery_mode: 'quick',
    image: 'https://picsum.photos/seed/chicken-10/400/400',
    imageHint: 'Chicken Sausages',
    tags: ['chicken', 'non-veg', 'sausages', 'ready to cook', 'breakfast'],
    rating: 4.2,
    rating_count: 65,
    warehouse_stock: [
      { warehouse_id: 'sultanganj', stock: 8 },
      { warehouse_id: 'bhagalpur', stock: 0 },
      { warehouse_id: 'khagaria', stock: 0 }
    ]
  }
];