
import { Product } from '../../types';

export const EGGS_PRODUCTS: Product[] = [
  {
    id: 'egg-1',
    name_en: 'Fresh Farm Eggs',
    name_hi: 'Farm Anda',
    description: 'Fresh eggs from local farms',
    brand: 'Local Farm',
    category_id: 'cat-5',
    mrp: 60,
    price: 55,
    stock_qty: 200,
    unit: 'dozen',
    pack_size: '12 pieces',
    is_veg: false,
    delivery_mode: 'quick',
    image: 'https://firebasestorage.googleapis.com/v0/b/freshoz-fresh-fast.firebasestorage.app/o/categories%2Fnon-veg%2Fproducts%2Feggs.webp?alt=media&token=c19ac51c-4394-4361-9cde-607062402511',
    imageHint: 'Farm Eggs',
    tags: ['eggs', 'fresh', 'farm', 'protein'],
    rating: 4.5,
    rating_count: 180,
    warehouse_stock: [
      { warehouse_id: 'sultanganj', stock: 80 },
      { warehouse_id: 'bhagalpur', stock: 0 },
      { warehouse_id: 'khagaria', stock: 0 }
    ],
    variants: [
      { id: 'egg-1-1', pack_size: '6 pc', mrp: 30, price: 28, stock_qty: 100 },
      { id: 'egg-1-2', pack_size: '12 pc', mrp: 60, price: 55, stock_qty: 100 },
      { id: 'egg-1-3', pack_size: '30 pc', mrp: 150, price: 135, stock_qty: 50 },
    ]
  },
  {
    id: 'egg-2',
    name_en: 'Organic Brown Eggs',
    name_hi: 'Brown Anda',
    description: 'Organic brown eggs from free-range hens',
    brand: 'Organic Farm',
    category_id: 'cat-5',
    mrp: 80,
    price: 75,
    stock_qty: 150,
    unit: 'dozen',
    pack_size: '12 pieces',
    is_veg: false,
    delivery_mode: 'quick',
    image: 'https://picsum.photos/seed/egg-2/400/400',
    imageHint: 'Organic Eggs',
    tags: ['eggs', 'organic', 'brown', 'free-range'],
    rating: 4.6,
    rating_count: 120,
    warehouse_stock: [
      { warehouse_id: 'sultanganj', stock: 60 },
      { warehouse_id: 'bhagalpur', stock: 0 },
      { warehouse_id: 'khagaria', stock: 0 }
    ],
    variants: [
      { id: 'egg-2-1', pack_size: '6 pieces', mrp: 40, price: 38, stock_qty: 75 },
      { id: 'egg-2-2', pack_size: '12 pieces', mrp: 80, price: 75, stock_qty: 75 },
    ]
  },
  {
    id: 'egg-3',
    name_en: 'White Eggs',
    name_hi: 'Safed Anda',
    description: 'Fresh white eggs',
    brand: 'Local Farm',
    category_id: 'cat-5',
    mrp: 55,
    price: 50,
    stock_qty: 180,
    unit: 'dozen',
    pack_size: '12 pieces',
    is_veg: false,
    delivery_mode: 'quick',
    image: 'https://picsum.photos/seed/egg-3/400/400',
    imageHint: 'White Eggs',
    tags: ['eggs', 'white', 'fresh', 'protein'],
    rating: 4.4,
    rating_count: 150,
    warehouse_stock: [
      { warehouse_id: 'sultanganj', stock: 75 },
      { warehouse_id: 'bhagalpur', stock: 0 },
      { warehouse_id: 'khagaria', stock: 0 }
    ],
    variants: [
      { id: 'egg-3-1', pack_size: '12 pieces', mrp: 55, price: 50, stock_qty: 90 },
      { id: 'egg-3-2', pack_size: '30 pieces (Tray)', mrp: 135, price: 125, stock_qty: 90 },
    ]
  },
  {
    id: 'egg-4',
    name_en: 'Country Eggs',
    name_hi: 'Desi Anda',
    description: 'Desi country eggs from native hens',
    brand: 'Local Farm',
    category_id: 'cat-5',
    mrp: 70,
    price: 65,
    stock_qty: 120,
    unit: 'dozen',
    pack_size: '12 pieces',
    is_veg: false,
    delivery_mode: 'quick',
    image: 'https://picsum.photos/seed/egg-4/400/400',
    imageHint: 'Country Eggs',
    tags: ['eggs', 'country', 'desi', 'native'],
    rating: 4.7,
    rating_count: 100,
    warehouse_stock: [
      { warehouse_id: 'sultanganj', stock: 50 },
      { warehouse_id: 'bhagalpur', stock: 0 },
      { warehouse_id: 'khagaria', stock: 0 }
    ],
    variants: [
        { id: 'egg-4-1', pack_size: '12 pieces', mrp: 70, price: 65, stock_qty: 120 },
    ]
  },
  {
    id: 'egg-5',
    name_en: 'White Eggs',
    name_hi: 'Safed Anda',
    description: 'Fresh white eggs',
    brand: 'Local Farms',
    category_id: 'cat-5',
    mrp: 210,
    price: 200,
    stock_qty: 90,
    unit: 'dozen',
    pack_size: '30 pieces',
    is_veg: false,
    delivery_mode: 'quick',
    image: 'https://picsum.photos/seed/egg-5/400/400',
    imageHint: 'Omega Eggs',
    tags: ['eggs', 'omega-3', 'enriched', 'healthy'],
    rating: 4.8,
    rating_count: 85,
    warehouse_stock: [
      { warehouse_id: 'sultanganj', stock: 40 },
      { warehouse_id: 'bhagalpur', stock: 0 },
      { warehouse_id: 'khagaria', stock: 0 }
    ],
    variants: [
        { id: 'egg-5-1', pack_size: '30 pieces', mrp: 210, price: 200, stock_qty: 90 },
    ]
  },
  {
    id: 'egg-6',
    name_en: 'Medium Size Eggs',
    name_hi: 'Medium Size Anda',
    description: 'Medium size fresh eggs',
    brand: 'Local Farm',
    category_id: 'cat-5',
    mrp: 50,
    price: 45,
    stock_qty: 160,
    unit: 'dozen',
    pack_size: '12 pieces',
    is_veg: false,
    delivery_mode: 'quick',
    image: 'https://picsum.photos/seed/egg-6/400/400',
    imageHint: 'Medium Eggs',
    tags: ['eggs', 'medium', 'fresh', 'economy'],
    rating: 4.3,
    rating_count: 140,
    warehouse_stock: [
      { warehouse_id: 'sultanganj', stock: 70 },
      { warehouse_id: 'bhagalpur', stock: 0 },
      { warehouse_id: 'khagaria', stock: 0 }
    ],
    variants: [
      { id: 'egg-6-1', pack_size: '12 pieces', mrp: 50, price: 45, stock_qty: 160 },
    ]
  },
  {
    id: 'egg-7',
    name_en: 'Black Eggs',
    name_hi: 'Kala Anda',
    description: 'Small nutritious Black eggs',
    brand: 'Exotic Farms',
    category_id: 'cat-5',
    mrp: 390,
    price: 370,
    stock_qty: 10,
    unit: 'pack',
    pack_size: '12 pieces',
    is_veg: false,
    delivery_mode: 'quick',
    image: 'https://picsum.photos/seed/egg-7/400/400',
    imageHint: 'Quail Eggs',
    tags: ['eggs', 'black', 'exotic', 'nutritious'],
    rating: 4.7,
    rating_count: 70,
    warehouse_stock: [
      { warehouse_id: 'sultanganj', stock: 25 },
      { warehouse_id: 'bhagalpur', stock: 0 },
      { warehouse_id: 'khagaria', stock: 0 }
    ],
    variants: [
       { id: 'egg-7-1', pack_size: '12 pieces', mrp: 390, price: 370, stock_qty: 10 },
    ]
  },
  {
    id: 'egg-8',
    name_en: 'Duck Eggs',
    name_hi: 'Battakh Anda',
    description: 'Fresh duck eggs',
    brand: 'Local Farm',
    category_id: 'cat-5',
    mrp: 100,
    price: 90,
    stock_qty: 70,
    unit: 'dozen',
    pack_size: '12 pieces',
    is_veg: false,
    delivery_mode: 'quick',
    image: 'https://picsum.photos/seed/egg-8/400/400',
    imageHint: 'Duck Eggs',
    tags: ['eggs', 'duck', 'fresh', 'rich'],
    rating: 4.4,
    rating_count: 60,
    warehouse_stock: [
      { warehouse_id: 'sultanganj', stock: 30 },
      { warehouse_id: 'bhagalpur', stock: 0 },
      { warehouse_id: 'khagaria', stock: 0 }
    ],
    variants: [
       { id: 'egg-8-1', pack_size: '12 pieces', mrp: 100, price: 90, stock_qty: 70 },
    ]
  },
  {
    id: 'egg-9',
    name_en: 'Egg Tray - 30 Pieces',
    name_hi: 'Egg Tray - 30 Pieces',
    description: 'Economy pack of 30 eggs',
    brand: 'Local Farm',
    category_id: 'cat-5',
    mrp: 140,
    price: 130,
    stock_qty: 100,
    unit: 'tray',
    pack_size: '30 pieces',
    is_veg: false,
    delivery_mode: 'quick',
    image: 'https://picsum.photos/seed/egg-9/400/400',
    imageHint: 'Egg Tray',
    tags: ['eggs', 'tray', 'economy', 'bulk'],
    rating: 4.6,
    rating_count: 90,
    warehouse_stock: [
      { warehouse_id: 'sultanganj', stock: 40 },
      { warehouse_id: 'bhagalpur', stock: 0 },
      { warehouse_id: 'khagaria', stock: 0 }
    ],
    variants: [
       { id: 'egg-9-1', pack_size: '30 pieces', mrp: 140, price: 130, stock_qty: 100 },
    ]
  },
   {
    id: 'egg-10',
    name_en: 'chencke-whole',
    name_hi: 'chencke-whole',
    description: 'Fresh whole chicken',
    brand: 'Local Farms',
    category_id: 'cat-5',
    mrp: 210,
    price: 200,
    stock_qty: 90,
    unit: 'dozen',
    pack_size: '1 pc',
    is_veg: false,
    delivery_mode: 'quick',
    image: 'https://picsum.photos/seed/egg-10/400/400',
    imageHint: 'Omega Eggs',
    tags: ['eggs', 'omega-3', 'enriched', 'healthy'],
    rating: 4.8,
    rating_count: 85,
    warehouse_stock: [
      { warehouse_id: 'sultanganj', stock: 40 },
      { warehouse_id: 'bhagalpur', stock: 0 },
      { warehouse_id: 'khagaria', stock: 0 }
    ],
    variants: [
        { id: 'egg-10-1', pack_size: '1 pc', mrp: 210, price: 200, stock_qty: 90 },
    ]
  }
];
