import { Product } from '../../types';

export const FISH_PRODUCTS: Product[] = [
  {
    id: 'fish-1',
    name_en: 'Rohu Fish (Rui)',
    name_hi: 'Rohu Machhali',
    description: 'Fresh Rohu fish. Cleaned and ready to cook.',
    brand: 'Local Fishery',
    category_id: 'cat-5',
    mrp: 180,
    price: 165,
    stock_qty: 15,
    unit: 'kg',
    pack_size: '500 g',
    is_veg: false,
    delivery_mode: 'quick',
    image: 'https://picsum.photos/seed/fish-1/400/400',
    imageHint: 'Rohu Fish',
    tags: ['fish', 'non-veg', 'rohu', 'rui', 'fresh'],
    rating: 4.5,
    rating_count: 120,
    warehouse_stock: [
      { warehouse_id: 'sultanganj', stock: 6 },
      { warehouse_id: 'bhagalpur', stock: 0 },
      { warehouse_id: 'khagaria', stock: 0 }
    ]
  },
  {
    id: 'fish-2',
    name_en: 'Catla Fish (Bhakur)',
    name_hi: 'Katala Machhali (Bhakur)',
    description: 'Fresh Catla fish. Great for Bengali style cooking.',
    brand: 'Local Fishery',
    category_id: 'cat-5',
    mrp: 190,
    price: 175,
    stock_qty: 12,
    unit: 'kg',
    pack_size: '500 g',
    is_veg: false,
    delivery_mode: 'quick',
    image: 'https://picsum.photos/seed/fish-2/400/400',
    imageHint: 'Catla Fish',
    tags: ['fish', 'non-veg', 'catla', 'bhakur', 'fresh'],
    rating: 4.4,
    rating_count: 95,
    warehouse_stock: [
      { warehouse_id: 'sultanganj', stock: 5 },
      { warehouse_id: 'bhagalpur', stock: 0 },
      { warehouse_id: 'khagaria', stock: 0 }
    ]
  },
  {
    id: 'fish-3',
    name_en: 'Baby Fish',
    name_hi: 'Bachawa Machhali',
    description: 'Fresh white pomfret. Delicate and flavorful.',
    brand: 'Local Fishery',
    category_id: 'cat-5',
    mrp: 350,
    price: 325,
    stock_qty: 8,
    unit: 'kg',
    pack_size: '500 g',
    is_veg: false,
    delivery_mode: 'quick',
    image: 'https://picsum.photos/seed/fish-3/400/400',
    imageHint: 'Pomfret Fish',
    tags: ['fish', 'bachawa', 'non-veg', 'pomfret', 'premium', 'fresh'],
    rating: 4.6,
    rating_count: 80,
    warehouse_stock: [
      { warehouse_id: 'sultanganj', stock: 3 },
      { warehouse_id: 'bhagalpur', stock: 0 },
      { warehouse_id: 'khagaria', stock: 0 }
    ]
  },
  {
    id: 'fish-4',
    name_en: 'Hilsa Fish (Ilish)',
    name_hi: 'Hilsa Machhali (Ilish)',
    description: 'Fresh Hilsa fish. Bengali delicacy.',
    brand: 'Local Fishery',
    category_id: 'cat-5',
    mrp: 500,
    price: 475,
    stock_qty: 6,
    unit: 'kg',
    pack_size: '500 g',
    is_veg: false,
    delivery_mode: 'quick',
    image: 'https://picsum.photos/seed/fish-4/400/400',
    imageHint: 'Hilsa Fish',
    tags: ['fish', 'non-veg', 'hilsa', 'ilish', 'premium'],
    rating: 4.7,
    rating_count: 65,
    warehouse_stock: [
      { warehouse_id: 'sultanganj', stock: 2 },
      { warehouse_id: 'bhagalpur', stock: 0 },
      { warehouse_id: 'khagaria', stock: 0 }
    ]
  },
  {
    id: 'fish-5',
    name_en: 'Singhara Fish',
    name_hi: 'Singha Machhali',
    description: 'Fresh Singhara fish. Local favorite.',
    brand: 'Local Fishery',
    category_id: 'cat-5',
    mrp: 160,
    price: 145,
    stock_qty: 18,
    unit: 'kg',
    pack_size: '500 g',
    is_veg: false,
    delivery_mode: 'quick',
    image: 'https://picsum.photos/seed/fish-5/400/400',
    imageHint: 'Singhara Fish',
    tags: ['fish', 'non-veg', 'singhara', 'local', 'fresh'],
    rating: 4.3,
    rating_count: 110,
    warehouse_stock: [
      { warehouse_id: 'sultanganj', stock: 7 },
      { warehouse_id: 'bhagalpur', stock: 0 },
      { warehouse_id: 'khagaria', stock: 0 }
    ]
  },
  {
    id: 'fish-6',
    name_en: 'Prawns (Jhinga)',
    name_hi: 'Jhinga Machhali',
    description: 'Fresh medium sized prawns. Cleaned and deveined.',
    brand: 'Local Fishery',
    category_id: 'cat-5',
    mrp: 280,
    price: 255,
    stock_qty: 10,
    unit: 'kg',
    pack_size: '500 g',
    is_veg: false,
    delivery_mode: 'quick',
    image: 'https://picsum.photos/seed/fish-6/400/400',
    imageHint: 'Prawns Jhinga',
    tags: ['fish', 'non-veg', 'prawns', 'jhinga', 'seafood'],
    rating: 4.5,
    rating_count: 90,
    warehouse_stock: [
      { warehouse_id: 'sultanganj', stock: 4 },
      { warehouse_id: 'bhagalpur', stock: 0 },
      { warehouse_id: 'khagaria', stock: 0 }
    ]
  },
  {
    id: 'fish-7',
    name_en: 'Bhetki Fish',
    name_hi: 'Baramundi Khajura Machhali',
    description: 'Fresh Bhetki fish. Great for fillets and fries.',
    brand: 'Local Fishery',
    category_id: 'cat-5',
    mrp: 320,
    price: 295,
    stock_qty: 9,
    unit: 'kg',
    pack_size: '500 g',
    is_veg: false,
    delivery_mode: 'quick',
    image: 'https://picsum.photos/seed/fish-7/400/400',
    imageHint: 'Bhetki Fish',
    tags: ['fish', 'Baramundi', 'Khajura', 'non-veg', 'bhetki', 'premium', 'fresh'],
    rating: 4.6,
    rating_count: 75,
    warehouse_stock: [
      { warehouse_id: 'sultanganj', stock: 3 },
      { warehouse_id: 'bhagalpur', stock: 0 },
      { warehouse_id: 'khagaria', stock: 0 }
    ]
  },
  {
    id: 'fish-8',
    name_en: 'Mrigal Fish',
    name_hi: 'Naini Machhali',
    description: 'Fresh Mrigal fish. Good for curries.',
    brand: 'Local Fishery',
    category_id: 'cat-5',
    mrp: 170,
    price: 155,
    stock_qty: 14,
    unit: 'kg',
    pack_size: '500 g',
    is_veg: false,
    delivery_mode: 'quick',
    image: 'https://picsum.photos/seed/fish-8/400/400',
    imageHint: 'Mrigal Fish',
    tags: ['fish', 'Naini', 'non-veg', 'mrigal', 'fresh', 'curry'],
    rating: 4.3,
    rating_count: 85,
    warehouse_stock: [
      { warehouse_id: 'sultanganj', stock: 5 },
      { warehouse_id: 'bhagalpur', stock: 0 },
      { warehouse_id: 'khagaria', stock: 0 }
    ]
  },
  {
    id: 'fish-9',
    name_en: 'Small Fish (Putti)',
    name_hi: 'Chhota Machhali',
    description: 'Fresh small fish. Perfect for frying.',
    brand: 'Local Fishery',
    category_id: 'cat-5',
    mrp: 120,
    price: 105,
    stock_qty: 20,
    unit: 'kg',
    pack_size: '500 g',
    is_veg: false,
    delivery_mode: 'quick',
    image: 'https://picsum.photos/seed/fish-9/400/400',
    imageHint: 'Small Fish',
    tags: ['fish', 'non-veg', 'small fish', 'putti', 'fry'],
    rating: 4.2,
    rating_count: 100,
    warehouse_stock: [
      { warehouse_id: 'sultanganj', stock: 8 },
      { warehouse_id: 'bhagalpur', stock: 0 },
      { warehouse_id: 'khagaria', stock: 0 }
    ]
  },
];