import { Product } from '../../types';

export const MUTTON_PRODUCTS: Product[] = [
  {
    id: 'mutton-1',
    name_en: 'Mutton Curry Cut',
    name_hi: 'Mutton Curry Piece',
    description: 'Fresh mutton curry cuts with bone. Perfect for curries.',
    brand: 'Local Farm',
    category_id: 'cat-5',
    mrp: 650,
    price: 599,
    stock_qty: 12,
    unit: 'kg',
    pack_size: '500 g',
    is_veg: false,
    delivery_mode: 'quick',
    image: 'https://picsum.photos/seed/mutton-1/400/400',
    imageHint: 'Mutton Curry',
    tags: ['mutton', 'non-veg', 'curry cut', 'fresh', 'goat meat'],
    rating: 4.6,
    rating_count: 150,
    warehouse_stock: [
      { warehouse_id: 'sultanganj', stock: 5 },
      { warehouse_id: 'bhagalpur', stock: 0 },
      { warehouse_id: 'khagaria', stock: 0 }
    ]
  },
  {
    id: 'mutton-2',
    name_en: 'Mutton Boneless',
    name_hi: 'Mutton Boneless',
    description: 'Fresh boneless mutton. Perfect for kebabs and biryani.',
    brand: 'Local Farm',
    category_id: 'cat-5',
    mrp: 750,
    price: 699,
    stock_qty: 8,
    unit: 'kg',
    pack_size: '500 g',
    is_veg: false,
    delivery_mode: 'quick',
    image: 'https://picsum.photos/seed/mutton-2/400/400',
    imageHint: 'Boneless Mutton',
    tags: ['mutton', 'non-veg', 'boneless', 'fresh', 'premium'],
    rating: 4.7,
    rating_count: 120,
    warehouse_stock: [
      { warehouse_id: 'sultanganj', stock: 3 },
      { warehouse_id: 'bhagalpur', stock: 0 },
      { warehouse_id: 'khagaria', stock: 0 }
    ]
  },
  {
    id: 'mutton-3',
    name_en: 'Mutton Fresh',
    name_hi: 'Mutton Fresh',
    description: 'Fresh mutton leg pieces. Great for roasts and curries.',
    brand: 'Local Farm',
    category_id: 'cat-5',
    mrp: 680,
    price: 629,
    stock_qty: 10,
    unit: 'kg',
    pack_size: '500 g',
    is_veg: false,
    delivery_mode: 'quick',
    image: 'https://picsum.photos/seed/mutton-3/400/400',
    imageHint: 'Mutton Leg',
    tags: ['mutton', 'non-veg', 'leg piece', 'fresh', 'roast'],
    rating: 4.5,
    rating_count: 110,
    warehouse_stock: [
      { warehouse_id: 'sultanganj', stock: 4 },
      { warehouse_id: 'bhagalpur', stock: 0 },
      { warehouse_id: 'khagaria', stock: 0 }
    ]
  },
  {
    id: 'mutton-4',
    name_en: 'Mutton Keema',
    name_hi: 'Mutton Keema',
    description: 'Fresh minced mutton. Perfect for kebabs and keema curry.',
    brand: 'Local Farm',
    category_id: 'cat-5',
    mrp: 720,
    price: 669,
    stock_qty: 9,
    unit: 'kg',
    pack_size: '500 g',
    is_veg: false,
    delivery_mode: 'quick',
    image: 'https://picsum.photos/seed/mutton-4/400/400',
    imageHint: 'Mutton Keema',
    tags: ['mutton', 'non-veg', 'keema', 'minced', 'fresh'],
    rating: 4.6,
    rating_count: 95,
    warehouse_stock: [
      { warehouse_id: 'sultanganj', stock: 3 },
      { warehouse_id: 'bhagalpur', stock: 0 },
      { warehouse_id: 'khagaria', stock: 0 }
    ]
  },
  {
    id: 'mutton-5',
    name_en: 'Mutton Ribs',
    name_hi: 'Mutton Panjra',
    description: 'Fresh mutton ribs. Great for grilling and curries.',
    brand: 'Local Farm',
    category_id: 'cat-5',
    mrp: 600,
    price: 549,
    stock_qty: 11,
    unit: 'kg',
    pack_size: '500 g',
    is_veg: false,
    delivery_mode: 'quick',
    image: 'https://picsum.photos/seed/mutton-5/400/400',
    imageHint: 'Mutton Ribs',
    tags: ['mutton', 'non-veg', 'ribs', 'fresh', 'grill'],
    rating: 4.4,
    rating_count: 85,
    warehouse_stock: [
      { warehouse_id: 'sultanganj', stock: 4 },
      { warehouse_id: 'bhagalpur', stock: 0 },
      { warehouse_id: 'khagaria', stock: 0 }
    ]
  },
];