import { Product } from '../../types';

export const READY_TO_EAT_PRODUCTS: Product[] = [
  {
    id: 'rte-1',
    name_en: 'Chicken Biryani',
    name_hi: 'Chicken Biryani',
    brand: 'FreshKitchen',
    price: 299,
    mrp: 330,
    image: 'https://picsum.photos/seed/rte-1/400/400',
    imageHint: 'Chicken Biryani',
    category_id: 'cat-5',
    category: 'Non-Veg',
    tags: ['ready-to-eat', 'non-veg', 'biryani', 'chicken'],
    stock_qty: 50,
    inStock: true,
    pack_size: '500g pack',
    is_veg: false,
    warehouse_stock: [{ warehouse_id: 'sultanganj', stock: 50 }],
  },
  {
    id: 'rte-2',
    name_en: 'Butter Chicken',
    name_hi: 'Butter Chicken',
    brand: 'FreshKitchen',
    price: 349,
    mrp: 410,
    image: 'https://picsum.photos/seed/rte-2/400/400',
    imageHint: 'Butter Chicken',
    category_id: 'cat-5',
    category: 'Non-Veg',
    tags: ['ready-to-eat', 'non-veg', 'butter-chicken'],
    stock_qty: 35,
    inStock: true,
    pack_size: '450g pack',
    is_veg: false,
    warehouse_stock: [{ warehouse_id: 'sultanganj', stock: 35 }],
  },
];
