import { Product } from '../../types';

export const BEVERAGES_PRODUCTS: Product[] = [
  {
    id: 'bev-1',
    name_en: 'Coca-Cola Can',
    name_hi: 'Coca-Cola Can',
    description: 'Refreshing Coca-Cola soft drink for any time',
    brand: 'Coca-Cola',
    category_id: 'cat-3',
    mrp: 50,
    price: 45,
    stock_qty: 500,
    unit: '330 ml',
    pack_size: '1 Can',
    is_veg: true,
    delivery_mode: 'standard',
    image: 'https://picsum.photos/seed/bev-1/400/400',
    imageHint: 'Coca-Cola can',
    tags: ['cola', 'soft drink', 'beverage'],
    rating: 4.6,
    rating_count: 250,
    warehouse_stock: [
      { warehouse_id: 'sultanganj', stock: 150 },
      { warehouse_id: 'bhagalpur', stock: 200 },
      { warehouse_id: 'khagaria', stock: 150 }
    ]
  },
  {
    id: 'bev-2',
    name_en: 'Pepsi Can',
    name_hi: 'Pepsi Can',
    description: 'Popular Pepsi soft drink for refreshment',
    brand: 'Pepsi',
    category_id: 'cat-3',
    mrp: 50,
    price: 45,
    stock_qty: 500,
    unit: '330 ml',
    pack_size: '1 Can',
    is_veg: true,
    delivery_mode: 'standard',
    image: 'https://picsum.photos/seed/bev-2/400/400',
    imageHint: 'Pepsi can',
    tags: ['cola', 'soft drink', 'beverage'],
    rating: 4.5,
    rating_count: 230,
    warehouse_stock: [
      { warehouse_id: 'sultanganj', stock: 150 },
      { warehouse_id: 'bhagalpur', stock: 200 },
      { warehouse_id: 'khagaria', stock: 150 }
    ]
  },
  {
    id: 'bev-3',
    name_en: 'Tropicana Orange Juice',
    name_hi: 'Tropicana Orange Juice',
    description: 'Fresh Tropicana orange juice packed with vitamin C',
    brand: 'Tropicana',
    category_id: 'cat-3',
    mrp: 80,
    price: 75,
    stock_qty: 300,
    unit: '200 ml',
    pack_size: '1 Bottle',
    is_veg: true,
    delivery_mode: 'standard',
    image: 'https://picsum.photos/seed/bev-3/400/400',
    imageHint: 'orange juice',
    tags: ['juice', 'orange', 'beverage'],
    rating: 4.7,
    rating_count: 180,
    warehouse_stock: [
      { warehouse_id: 'sultanganj', stock: 100 },
      { warehouse_id: 'bhagalpur', stock: 120 },
      { warehouse_id: 'khagaria', stock: 80 }
    ]
  },
  {
    id: 'bev-4',
    name_en: 'Maaza Mango Drink',
    name_hi: 'Maaza Mango Drink',
    description: 'Sweet and tasty Maaza mango drink',
    brand: 'Maaza',
    category_id: 'cat-3',
    mrp: 60,
    price: 55,
    stock_qty: 400,
    unit: '200 ml',
    pack_size: '1 Bottle',
    is_veg: true,
    delivery_mode: 'standard',
    image: 'https://picsum.photos/seed/bev-4/400/400',
    imageHint: 'mango drink',
    tags: ['mango', 'juice', 'beverage'],
    rating: 4.6,
    rating_count: 190,
    warehouse_stock: [
      { warehouse_id: 'sultanganj', stock: 130 },
      { warehouse_id: 'bhagalpur', stock: 150 },
      { warehouse_id: 'khagaria', stock: 120 }
    ]
  },
  {
    id: 'bev-5',
    name_en: 'Frooti Mango Drink',
    name_hi: 'Frooti Mango Drink',
    description: 'Refreshing Frooti mango beverage',
    brand: 'Frooti',
    category_id: 'cat-3',
    mrp: 60,
    price: 55,
    stock_qty: 400,
    unit: '200 ml',
    pack_size: '1 Bottle',
    is_veg: true,
    delivery_mode: 'standard',
    image: 'https://picsum.photos/seed/bev-5/400/400',
    imageHint: 'mango drink',
    tags: ['mango', 'juice', 'beverage'],
    rating: 4.5,
    rating_count: 180,
    warehouse_stock: [
      { warehouse_id: 'sultanganj', stock: 130 },
      { warehouse_id: 'bhagalpur', stock: 150 },
      { warehouse_id: 'khagaria', stock: 120 }
    ]
  },
  {
    id: 'bev-6',
    name_en: 'Red Bull Energy Drink',
    name_hi: 'Red Bull Energy Drink',
    description: 'Boost your energy with Red Bull',
    brand: 'Red Bull',
    category_id: 'cat-3',
    mrp: 120,
    price: 110,
    stock_qty: 250,
    unit: '250 ml',
    pack_size: '1 Can',
    is_veg: true,
    delivery_mode: 'standard',
    image: 'https://picsum.photos/seed/bev-6/400/400',
    imageHint: 'energy drink',
    tags: ['energy', 'drink', 'beverage'],
    rating: 4.7,
    rating_count: 140,
    warehouse_stock: [
      { warehouse_id: 'sultanganj', stock: 80 },
      { warehouse_id: 'bhagalpur', stock: 100 },
      { warehouse_id: 'khagaria', stock: 70 }
    ]
  },
  {
    id: 'bev-7',
    name_en: 'Limca Lemon Drink',
    name_hi: 'Limca Lemon Drink',
    description: 'Refreshing lemon soda from Limca',
    brand: 'Limca',
    category_id: 'cat-3',
    mrp: 40,
    price: 35,
    stock_qty: 500,
    unit: '300 ml',
    pack_size: '1 Bottle',
    is_veg: true,
    delivery_mode: 'standard',
    image: 'https://picsum.photos/seed/bev-7/400/400',
    imageHint: 'lemon soda',
    tags: ['lemon', 'soda', 'beverage'],
    rating: 4.6,
    rating_count: 150,
    warehouse_stock: [
      { warehouse_id: 'sultanganj', stock: 160 },
      { warehouse_id: 'bhagalpur', stock: 180 },
      { warehouse_id: 'khagaria', stock: 160 }
    ]
  },
  {
    id: 'bev-8',
    name_en: 'Kinley Water Bottle',
    name_hi: 'Kinley Paani Bottle',
    description: 'Pure and safe drinking water from Kinley',
    brand: 'Kinley',
    category_id: 'cat-3',
    mrp: 20,
    price: 18,
    stock_qty: 1000,
    unit: '500 ml',
    pack_size: '1 Bottle',
    is_veg: true,
    delivery_mode: 'standard',
    image: 'https://picsum.photos/seed/bev-8/400/400',
    imageHint: 'water bottle',
    tags: ['water', 'bottle', 'beverage'],
    rating: 4.8,
    rating_count: 300,
    warehouse_stock: [
      { warehouse_id: 'sultanganj', stock: 350 },
      { warehouse_id: 'bhagalpur', stock: 400 },
      { warehouse_id: 'khagaria', stock: 250 }
    ]
  },
  {
    id: 'bev-9',
    name_en: 'Sprite Can',
    name_hi: 'Sprite Can',
    description: 'Lemon-lime flavored refreshing soda from Sprite',
    brand: 'Sprite',
    category_id: 'cat-3',
    mrp: 50,
    price: 45,
    stock_qty: 500,
    unit: '330 ml',
    pack_size: '1 Can',
    is_veg: true,
    delivery_mode: 'standard',
    image: 'https://picsum.photos/seed/bev-9/400/400',
    imageHint: 'lemon-lime soda',
    tags: ['lemon', 'lime', 'soda', 'beverage'],
    rating: 4.6,
    rating_count: 200,
    warehouse_stock: [
      { warehouse_id: 'sultanganj', stock: 150 },
      { warehouse_id: 'bhagalpur', stock: 200 },
      { warehouse_id: 'khagaria', stock: 150 }
    ]
  }
];
