import type { Product } from '@/lib/types';

export const SNACKS_PRODUCTS: Product[] = [
  {
    id: 'snack-1',
    name_en: 'Lay\'s Classic Salted Chips',
    name_hi: 'Lays Namkeen Chips',
    description: 'Crispy potato chips with classic salted flavour.',
    brand: 'Lay\'s',
    category_id: 'cat-3',
    mrp: 40,
    price: 35,
    stock_qty: 120,
    unit: '1 pack',
    pack_size: '40 g',
    is_veg: true,
    delivery_mode: 'standard',
    image: 'https://picsum.photos/seed/snack-1/400/400',
    imageHint: 'potato chips',
    tags: ['chips', 'snack', 'crunchy'],
    rating: 4.3,
    rating_count: 420,
    warehouse_stock: [
      { warehouse_id: 'sultanganj', stock: 40 },
      { warehouse_id: 'bhagalpur', stock: 50 },
      { warehouse_id: 'khagaria', stock: 30 }
    ]
  },
  {
    id: 'snack-2',
    name_en: 'Parle Monaco Salted',
    name_hi: 'Parle Monaco Namkeen',
    description: 'Light and crispy salted biscuits, ideal with tea.',
    brand: 'Parle',
    category_id: 'cat-3',
    mrp: 20,
    price: 18,
    stock_qty: 200,
    unit: '1 pack',
    pack_size: '50 g',
    is_veg: true,
    delivery_mode: 'standard',
    image: 'https://picsum.photos/seed/snack-2/400/400',
    imageHint: 'salted biscuits',
    tags: ['biscuit', 'snack'],
    rating: 4.1,
    rating_count: 310,
    warehouse_stock: [
      { warehouse_id: 'sultanganj', stock: 70 },
      { warehouse_id: 'bhagalpur', stock: 80 },
      { warehouse_id: 'khagaria', stock: 50 }
    ]
  },
  {
    id: 'snack-3',
    name_en: 'Haldiram\'s Aloo Bhujia',
    name_hi: 'Haldiram Aloo Bhujia',
    description: 'Spicy aloo bhujia for your tea-time cravings.',
    brand: 'Haldiram',
    category_id: 'cat-3',
    mrp: 60,
    price: 54,
    stock_qty: 140,
    unit: '1 pack',
    pack_size: '150 g',
    is_veg: true,
    delivery_mode: 'standard',
    image: 'https://picsum.photos/seed/snack-3/400/400',
    imageHint: 'aloo bhujia',
    tags: ['namkeen', 'bhujia', 'spicy'],
    rating: 4.5,
    rating_count: 520,
    warehouse_stock: [
      { warehouse_id: 'sultanganj', stock: 40 },
      { warehouse_id: 'bhagalpur', stock: 60 },
      { warehouse_id: 'khagaria', stock: 40 }
    ]
  },
  {
    id: 'snack-4',
    name_en: 'Britannia NutriChoice Digestive',
    name_hi: 'Britannia Digestive',
    description: 'Healthy digestive biscuits with whole wheat.',
    brand: 'Britannia',
    category_id: 'cat-3',
    mrp: 45,
    price: 40,
    stock_qty: 110,
    unit: '1 pack',
    pack_size: '100 g',
    is_veg: true,
    delivery_mode: 'standard',
    image: 'https://picsum.photos/seed/snack-4/400/400',
    imageHint: 'digestive biscuits',
    tags: ['biscuit', 'healthy'],
    rating: 4.2,
    rating_count: 210,
    warehouse_stock: [
      { warehouse_id: 'sultanganj', stock: 30 },
      { warehouse_id: 'bhagalpur', stock: 50 },
      { warehouse_id: 'khagaria', stock: 30 }
    ]
  },
  {
    id: 'snack-5',
    name_en: 'Kurkure Masala Munch',
    name_hi: 'Kurkure Masala',
    description: 'Crunchy masala snack with tangy taste.',
    brand: 'Kurkure',
    category_id: 'cat-3',
    mrp: 10,
    price: 9,
    stock_qty: 300,
    unit: '1 pack',
    pack_size: '20 g',
    is_veg: true,
    delivery_mode: 'standard',
    image: 'https://picsum.photos/seed/snack-5/400/400',
    imageHint: 'masala snacks',
    tags: ['namkeen', 'crunchy'],
    rating: 4.0,
    rating_count: 900,
    warehouse_stock: [
      { warehouse_id: 'sultanganj', stock: 100 },
      { warehouse_id: 'bhagalpur', stock: 120 },
      { warehouse_id: 'khagaria', stock: 80 }
    ]
  },
  {
    id: 'snack-6',
    name_en: 'Bikaji Bhel Mix',
    name_hi: 'Bikaji Bhel',
    description: 'Tangy and crunchy bhelpuri mix.',
    brand: 'Bikaji',
    category_id: 'cat-3',
    mrp: 55,
    price: 50,
    stock_qty: 90,
    unit: '1 pack',
    pack_size: '150 g',
    is_veg: true,
    delivery_mode: 'standard',
    image: 'https://picsum.photos/seed/snack-6/400/400',
    imageHint: 'bhel mix',
    tags: ['namkeen', 'bhel'],
    rating: 4.4,
    rating_count: 260,
    warehouse_stock: [
      { warehouse_id: 'sultanganj', stock: 20 },
      { warehouse_id: 'bhagalpur', stock: 50 },
      { warehouse_id: 'khagaria', stock: 20 }
    ]
  },
  {
    id: 'snack-7',
    name_en: 'Pringles Original',
    name_hi: 'Pringles Original',
    description: 'Stackable potato crisps in a can.',
    brand: 'Pringles',
    category_id: 'cat-3',
    mrp: 150,
    price: 135,
    stock_qty: 60,
    unit: '1 can',
    pack_size: '120 g',
    is_veg: true,
    delivery_mode: 'standard',
    image: 'https://picsum.photos/seed/snack-7/400/400',
    imageHint: 'potato crisps',
    tags: ['chips', 'premium'],
    rating: 4.6,
    rating_count: 180,
    warehouse_stock: [
      { warehouse_id: 'sultanganj', stock: 20 },
      { warehouse_id: 'bhagalpur', stock: 30 },
      { warehouse_id: 'khagaria', stock: 10 }
    ]
  },
  {
    id: 'snack-8',
    name_en: 'Too Yumm Multigrain Chips',
    name_hi: 'Too Yumm Chips',
    description: 'Multigrain chips for a lighter snack option.',
    brand: 'Too Yumm',
    category_id: 'cat-3',
    mrp: 45,
    price: 40,
    stock_qty: 140,
    unit: '1 pack',
    pack_size: '60 g',
    is_veg: true,
    delivery_mode: 'standard',
    image: 'https://picsum.photos/seed/snack-8/400/400',
    imageHint: 'multigrain chips',
    tags: ['chips', 'multigrain', 'healthy'],
    rating: 4.1,
    rating_count: 120,
    warehouse_stock: [
      { warehouse_id: 'sultanganj', stock: 40 },
      { warehouse_id: 'bhagalpur', stock: 60 },
      { warehouse_id: 'khagaria', stock: 40 }
    ]
  },
  {
    id: 'snack-9',
    name_en: 'Sunfeast Dark Fantasy Choco Fills',
    name_hi: 'Sunfeast Choco Fills',
    description: 'Chocolate-filled cookies for sweet cravings.',
    brand: 'Sunfeast',
    category_id: 'cat-3',
    mrp: 35,
    price: 30,
    stock_qty: 130,
    unit: '1 pack',
    pack_size: '75 g',
    is_veg: true,
    delivery_mode: 'standard',
    image: 'https://picsum.photos/seed/snack-9/400/400',
    imageHint: 'choco cookies',
    tags: ['cookies', 'sweet'],
    rating: 4.4,
    rating_count: 320,
    warehouse_stock: [
      { warehouse_id: 'sultanganj', stock: 40 },
      { warehouse_id: 'bhagalpur', stock: 60 },
      { warehouse_id: 'khagaria', stock: 30 }
    ]
  },
  {
    id: 'snack-10',
    name_en: 'Aashirvaad Namkeen Mix',
    name_hi: 'Aashirvaad Namkeen',
    description: 'Assorted namkeen mix for tea-time.',
    brand: 'Aashirvaad',
    category_id: 'cat-3',
    mrp: 70,
    price: 65,
    stock_qty: 80,
    unit: '1 pack',
    pack_size: '200 g',
    is_veg: true,
    delivery_mode: 'standard',
    image: 'https://picsum.photos/seed/snack-10/400/400',
    imageHint: 'namkeen mix',
    tags: ['namkeen', 'mix'],
    rating: 4.0,
    rating_count: 95,
    warehouse_stock: [
      { warehouse_id: 'sultanganj', stock: 20 },
      { warehouse_id: 'bhagalpur', stock: 40 },
      { warehouse_id: 'khagaria', stock: 20 }
    ]
  },
  {
    id: 'snack-11',
    name_en: 'Haldiram\'s Soan Papdi (mini)',
    name_hi: 'Haldiram Soan Papdi',
    description: 'Sweet, flaky soan papdi in mini pack.',
    brand: 'Haldiram',
    category_id: 'cat-3',
    mrp: 120,
    price: 110,
    stock_qty: 50,
    unit: '1 box',
    pack_size: '200 g',
    is_veg: true,
    delivery_mode: 'standard',
    image: 'https://picsum.photos/seed/snack-11/400/400',
    imageHint: 'soan papdi',
    tags: ['sweet', 'mithai'],
    rating: 4.5,
    rating_count: 70,
    warehouse_stock: [
      { warehouse_id: 'sultanganj', stock: 10 },
      { warehouse_id: 'bhagalpur', stock: 30 },
      { warehouse_id: 'khagaria', stock: 10 }
    ]
  },
  {
    id: 'snack-12',
    name_en: 'Bingo Mad Angles Chilli',
    name_hi: 'Bingo Mad Angles',
    description: 'Triangle crisps with spicy chilli kick.',
    brand: 'Bingo',
    category_id: 'cat-3',
    mrp: 15,
    price: 13,
    stock_qty: 220,
    unit: '1 pack',
    pack_size: '40 g',
    is_veg: true,
    delivery_mode: 'standard',
    image: 'https://picsum.photos/seed/snack-12/400/400',
    imageHint: 'chilli crisps',
    tags: ['chips', 'spicy'],
    rating: 4.0,
    rating_count: 400,
    warehouse_stock: [
      { warehouse_id: 'sultanganj', stock: 80 },
      { warehouse_id: 'bhagalpur', stock: 90 },
      { warehouse_id: 'khagaria', stock: 50 }
    ]
  },
  {
    id: 'snack-13',
    name_en: 'Balaji Wafers Pudina',
    name_hi: 'Balaji Pudina Chips',
    description: 'Minty flavoured potato chips.',
    brand: 'Balaji',
    category_id: 'cat-3',
    mrp: 20,
    price: 18,
    stock_qty: 160,
    unit: '1 pack',
    pack_size: '50 g',
    is_veg: true,
    delivery_mode: 'standard',
    image: 'https://picsum.photos/seed/snack-13/400/400',
    imageHint: 'mint chips',
    tags: ['chips', 'mint'],
    rating: 4.1,
    rating_count: 150,
    warehouse_stock: [
      { warehouse_id: 'sultanganj', stock: 50 },
      { warehouse_id: 'bhagalpur', stock: 70 },
      { warehouse_id: 'khagaria', stock: 40 }
    ]
  },
  {
    id: 'snack-14',
    name_en: 'Peppy Popcorn Butter',
    name_hi: 'Peppy Popcorn',
    description: 'Light buttery popcorn, ready-to-eat.',
    brand: 'Peppy',
    category_id: 'cat-3',
    mrp: 35,
    price: 30,
    stock_qty: 90,
    unit: '1 pack',
    pack_size: '60 g',
    is_veg: true,
    delivery_mode: 'standard',
    image: 'https://picsum.photos/seed/snack-14/400/400',
    imageHint: 'buttered popcorn',
    tags: ['popcorn', 'snack'],
    rating: 4.2,
    rating_count: 60,
    warehouse_stock: [
      { warehouse_id: 'sultanganj', stock: 30 },
      { warehouse_id: 'bhagalpur', stock: 40 },
      { warehouse_id: 'khagaria', stock: 20 }
    ]
  },
  {
    id: 'snack-15',
    name_en: 'MTR Ready to Eat Chana Masala (Snack)',
    name_hi: 'MTR Chana Snack',
    description: 'Spicy roasted chana for a protein-rich snack.',
    brand: 'MTR',
    category_id: 'cat-3',
    mrp: 50,
    price: 45,
    stock_qty: 70,
    unit: '1 pack',
    pack_size: '120 g',
    is_veg: true,
    delivery_mode: 'standard',
    image: 'https://picsum.photos/seed/snack-15/400/400',
    imageHint: 'roasted chana',
    tags: ['protein', 'healthy'],
    rating: 4.3,
    rating_count: 40,
    warehouse_stock: [
      { warehouse_id: 'sultanganj', stock: 20 },
      { warehouse_id: 'bhagalpur', stock: 30 },
      { warehouse_id: 'khagaria', stock: 20 }
    ]
  },
  {
    id: 'snack-16',
    name_en: 'Peanut Chikki (Local)',
    name_hi: 'Local Peanut Chikki',
    description: 'Crunchy jaggery peanut chikki made locally.',
    brand: 'Local Mill',
    category_id: 'cat-3',
    mrp: 80,
    price: 70,
    stock_qty: 40,
    unit: '1 piece',
    pack_size: '100 g',
    is_veg: true,
    delivery_mode: 'standard',
    image: 'https://picsum.photos/seed/snack-16/400/400',
    imageHint: 'peanut chikki',
    tags: ['sweet', 'local'],
    rating: 4.4,
    rating_count: 18,
    warehouse_stock: [
      { warehouse_id: 'sultanganj', stock: 15 },
      { warehouse_id: 'bhagalpur', stock: 15 },
      { warehouse_id: 'khagaria', stock: 10 }
    ]
  },
  {
    id: 'snack-17',
    name_en: 'Instant Noodles Masala (Small)',
    name_hi: 'Maggi Masala',
    description: 'Quick masala noodles for instant hunger relief.',
    brand: 'Nestle',
    category_id: 'cat-3',
    mrp: 12,
    price: 10,
    stock_qty: 300,
    unit: '1 pack',
    pack_size: '70 g',
    is_veg: true,
    delivery_mode: 'standard',
    image: 'https://picsum.photos/seed/snack-17/400/400',
    imageHint: 'instant noodles',
    tags: ['instant', 'noodles'],
    rating: 4.0,
    rating_count: 1000,
    warehouse_stock: [
      { warehouse_id: 'sultanganj', stock: 120 },
      { warehouse_id: 'bhagalpur', stock: 120 },
      { warehouse_id: 'khagaria', stock: 60 }
    ]
  },
  {
    id: 'snack-18',
    name_en: 'Roasted Almonds (Local pack)',
    name_hi: 'Roasted Almonds',
    description: 'Dry roasted almonds, healthy snack.',
    brand: 'Local Dryfruits',
    category_id: 'cat-3',
    mrp: 220,
    price: 200,
    stock_qty: 50,
    unit: '100 g',
    pack_size: '100 g',
    is_veg: true,
    delivery_mode: 'standard',
    image: 'https://picsum.photos/seed/snack-18/400/400',
    imageHint: 'roasted almonds',
    tags: ['dryfruits', 'healthy'],
    rating: 4.6,
    rating_count: 45,
    warehouse_stock: [
      { warehouse_id: 'sultanganj', stock: 20 },
      { warehouse_id: 'bhagalpur', stock: 20 },
      { warehouse_id: 'khagaria', stock: 10 }
    ]
  },
  {
    id: 'snack-19',
    name_en: 'Savoury Mixture (Local)',
    name_hi: 'Mixture',
    description: 'House-made savoury mixture (loose pack) for snacking.',
    brand: 'Local Pack',
    category_id: 'cat-3',
    mrp: 90,
    price: 80,
    stock_qty: 75,
    unit: '250 g',
    pack_size: '250 g',
    is_veg: true,
    delivery_mode: 'standard',
    image: 'https://picsum.photos/seed/snack-19/400/400',
    imageHint: 'savoury mixture',
    tags: ['namkeen', 'loose'],
    rating: 4.2,
    rating_count: 30,
    warehouse_stock: [
      { warehouse_id: 'sultanganj', stock: 25 },
      { warehouse_id: 'bhagalpur', stock: 30 },
      { warehouse_id: 'khagaria', stock: 20 }
    ]
  },
  {
    id: 'snack-20',
    name_en: 'Mixed Nuts (Roasted) - Small',
    name_hi: 'Mixed Nuts',
    description: 'Small pack of roasted mixed nuts - cashew, almond, raisin.',
    brand: 'NutHouse',
    category_id: 'cat-3',
    mrp: 180,
    price: 165,
    stock_qty: 40,
    unit: '100 g',
    pack_size: '100 g',
    is_veg: true,
    delivery_mode: 'standard',
    image: 'https://picsum.photos/seed/snack-20/400/400',
    imageHint: 'mixed nuts',
    tags: ['nuts', 'healthy', 'premium'],
    rating: 4.7,
    rating_count: 28,
    warehouse_stock: [
      { warehouse_id: 'sultanganj', stock: 10 },
      { warehouse_id: 'bhagalpur', stock: 20 },
      { warehouse_id: 'khagaria', stock: 10 }
    ]
  }
];
