import { Product } from '../../types';

export const WATER_JUICE_PRODUCTS: Product[] = [
  {
    id: 'water-1',
    name_en: 'Bisleri Mineral Water',
    name_hi: 'Bisleri Mineral Paani',
    description: 'Pure mineral water for daily hydration',
    brand: 'Bisleri',
    category_id: 'cat-3',
    mrp: 20,
    price: 18,
    stock_qty: 500,
    unit: 'bottle',
    pack_size: '1 L',
    is_veg: true,
    delivery_mode: 'standard',
    image: 'https://picsum.photos/seed/water-1/400/400',
    imageHint: 'mineral water',
    tags: ['water', 'mineral', 'pure', 'hydration'],
    rating: 4.7,
    rating_count: 350,
    warehouse_stock: [
      { warehouse_id: 'sultanganj', stock: 200 },
      { warehouse_id: 'bhagalpur', stock: 200 },
      { warehouse_id: 'khagaria', stock: 100 }
    ]
  },
  {
    id: 'water-2',
    name_en: 'Kinley Mineral Water',
    name_hi: 'Kinley Mineral Paani',
    description: 'Refreshing mineral water from Coca-Cola',
    brand: 'Kinley',
    category_id: 'cat-3',
    mrp: 20,
    price: 18,
    stock_qty: 450,
    unit: 'bottle',
    pack_size: '1 L',
    is_veg: true,
    delivery_mode: 'standard',
    image: 'https://picsum.photos/seed/water-2/400/400',
    imageHint: 'mineral water',
    tags: ['water', 'mineral', 'refreshing', 'hydration'],
    rating: 4.6,
    rating_count: 300,
    warehouse_stock: [
      { warehouse_id: 'sultanganj', stock: 180 },
      { warehouse_id: 'bhagalpur', stock: 180 },
      { warehouse_id: 'khagaria', stock: 90 }
    ]
  },
  {
    id: 'water-3',
    name_en: 'Aquafina Mineral Water',
    name_hi: 'Aquafina Mineral Paani',
    description: 'Pure drinking water from PepsiCo',
    brand: 'Aquafina',
    category_id: 'cat-3',
    mrp: 20,
    price: 18,
    stock_qty: 400,
    unit: 'bottle',
    pack_size: '1 L',
    is_veg: true,
    delivery_mode: 'standard',
    image: 'https://picsum.photos/seed/water-3/400/400',
    imageHint: 'drinking water',
    tags: ['water', 'mineral', 'pure', 'hydration'],
    rating: 4.5,
    rating_count: 280,
    warehouse_stock: [
      { warehouse_id: 'sultanganj', stock: 160 },
      { warehouse_id: 'bhagalpur', stock: 160 },
      { warehouse_id: 'khagaria', stock: 80 }
    ]
  },
  {
    id: 'water-4',
    name_en: 'Himalayan Mineral Water',
    name_hi: 'Himalayan Mineral Paani',
    description: 'Natural mineral water from Himalayas',
    brand: 'Himalayan',
    category_id: 'cat-3',
    mrp: 30,
    price: 27,
    stock_qty: 300,
    unit: 'bottle',
    pack_size: '1 L',
    is_veg: true,
    delivery_mode: 'standard',
    image: 'https://picsum.photos/seed/water-4/400/400',
    imageHint: 'himalayan water',
    tags: ['water', 'mineral', 'natural', 'premium'],
    rating: 4.8,
    rating_count: 200,
    warehouse_stock: [
      { warehouse_id: 'sultanganj', stock: 120 },
      { warehouse_id: 'bhagalpur', stock: 120 },
      { warehouse_id: 'khagaria', stock: 60 }
    ]
  },
  {
    id: 'water-5',
    name_en: 'Bailley Mineral Water',
    name_hi: 'Bailley Mineral paani',
    description: 'Natural mineral water',
    brand: 'Bailley',
    category_id: 'cat-3',
    mrp: 25,
    price: 22,
    stock_qty: 350,
    unit: 'bottle',
    pack_size: '1 L',
    is_veg: true,
    delivery_mode: 'standard',
    image: 'https://picsum.photos/seed/water-5/400/400',
    imageHint: 'mineral water',
    tags: ['water', 'mineral', 'natural', 'hydration'],
    rating: 4.6,
    rating_count: 240,
    warehouse_stock: [
      { warehouse_id: 'sultanganj', stock: 140 },
      { warehouse_id: 'bhagalpur', stock: 140 },
      { warehouse_id: 'khagaria', stock: 70 }
    ]
  },
  {
    id: 'juice-6',
    name_en: 'Real Fruit Juice - Orange',
    name_hi: 'Real Fruit Juice - Narangi',
    description: '100% pure orange juice with pulp',
    brand: 'Real',
    category_id: 'cat-3',
    mrp: 100,
    price: 90,
    stock_qty: 200,
    unit: 'tetra',
    pack_size: '1 L',
    is_veg: true,
    delivery_mode: 'standard',
    image: 'https://picsum.photos/seed/juice-6/400/400',
    imageHint: 'orange juice',
    tags: ['juice', 'orange', 'fruit', 'pulp'],
    rating: 4.7,
    rating_count: 180,
    warehouse_stock: [
      { warehouse_id: 'sultanganj', stock: 80 },
      { warehouse_id: 'bhagalpur', stock: 80 },
      { warehouse_id: 'khagaria', stock: 40 }
    ]
  },
  {
    id: 'juice-7',
    name_en: 'Real Fruit Juice - Apple',
    name_hi: 'Real Fruit Juice - Seb',
    description: '100% pure apple juice',
    brand: 'Real',
    category_id: 'cat-3',
    mrp: 110,
    price: 99,
    stock_qty: 180,
    unit: 'tetra',
    pack_size: '1 L',
    is_veg: true,
    delivery_mode: 'standard',
    image: 'https://picsum.photos/seed/juice-7/400/400',
    imageHint: 'apple juice',
    tags: ['juice', 'apple', 'fruit', 'pure'],
    rating: 4.6,
    rating_count: 160,
    warehouse_stock: [
      { warehouse_id: 'sultanganj', stock: 70 },
      { warehouse_id: 'bhagalpur', stock: 70 },
      { warehouse_id: 'khagaria', stock: 40 }
    ]
  },
  {
    id: 'juice-8',
    name_en: 'Real Fruit Juice - Mixed Fruit',
    name_hi: 'Real Fruit Juice - Mixed Fal',
    description: 'Blend of multiple fruit juices',
    brand: 'Real',
    category_id: 'cat-3',
    mrp: 120,
    price: 108,
    stock_qty: 160,
    unit: 'tetra',
    pack_size: '1 L',
    is_veg: true,
    delivery_mode: 'standard',
    image: 'https://picsum.photos/seed/juice-8/400/400',
    imageHint: 'mixed fruit',
    tags: ['juice', 'mixed fruit', 'blend', 'fruit'],
    rating: 4.8,
    rating_count: 170,
    warehouse_stock: [
      { warehouse_id: 'sultanganj', stock: 65 },
      { warehouse_id: 'bhagalpur', stock: 65 },
      { warehouse_id: 'khagaria', stock: 30 }
    ]
  },
  {
    id: 'juice-9',
    name_en: 'Real Fruit Juice - Mango',
    name_hi: 'Real Fruit Juice - Aam',
    description: '100% pure mango juice',
    brand: 'Real',
    category_id: 'cat-3',
    mrp: 130,
    price: 117,
    stock_qty: 220,
    unit: 'tetra',
    pack_size: '1 L',
    is_veg: true,
    delivery_mode: 'standard',
    image: 'https://picsum.photos/seed/juice-9/400/400',
    imageHint: 'mango juice',
    tags: ['juice', 'mango', 'fruit', 'pure'],
    rating: 4.9,
    rating_count: 250,
    warehouse_stock: [
      { warehouse_id: 'sultanganj', stock: 90 },
      { warehouse_id: 'bhagalpur', stock: 90 },
      { warehouse_id: 'khagaria', stock: 40 }
    ]
  },
  {
    id: 'juice-10',
    name_en: 'Real Fruit Juice - Pineapple',
    name_hi: 'Real Fruit Juice - Ananas',
    description: '100% pure pineapple juice',
    brand: 'Real',
    category_id: 'cat-3',
    mrp: 115,
    price: 104,
    stock_qty: 150,
    unit: 'tetra',
    pack_size: '1 L',
    is_veg: true,
    delivery_mode: 'standard',
    image: 'https://picsum.photos/seed/juice-10/400/400',
    imageHint: 'pineapple juice',
    tags: ['juice', 'pineapple', 'fruit', 'pure'],
    rating: 4.5,
    rating_count: 130,
    warehouse_stock: [
      { warehouse_id: 'sultanganj', stock: 60 },
      { warehouse_id: 'bhagalpur', stock: 60 },
      { warehouse_id: 'khagaria', stock: 30 }
    ]
  },
  {
    id: 'juice-11',
    name_en: 'Tropicana Juice - Orange',
    name_hi: 'Tropicana Juice - Narangi',
    description: '100% pure orange juice',
    brand: 'Tropicana',
    category_id: 'cat-3',
    mrp: 105,
    price: 95,
    stock_qty: 190,
    unit: 'tetra',
    pack_size: '1 L',
    is_veg: true,
    delivery_mode: 'standard',
    image: 'https://picsum.photos/seed/juice-11/400/400',
    imageHint: 'orange juice',
    tags: ['juice', 'orange', 'fruit', 'pure'],
    rating: 4.7,
    rating_count: 200,
    warehouse_stock: [
      { warehouse_id: 'sultanganj', stock: 80 },
      { warehouse_id: 'bhagalpur', stock: 80 },
      { warehouse_id: 'khagaria', stock: 30 }
    ]
  },
  {
    id: 'juice-12',
    name_en: 'Tropicana Juice - Apple',
    name_hi: 'Tropicana Juice - Seb',
    description: '100% pure apple juice',
    brand: 'Tropicana',
    category_id: 'cat-3',
    mrp: 115,
    price: 105,
    stock_qty: 170,
    unit: 'tetra',
    pack_size: '1 L',
    is_veg: true,
    delivery_mode: 'standard',
    image: 'https://picsum.photos/seed/juice-12/400/400',
    imageHint: 'apple juice',
    tags: ['juice', 'apple', 'fruit', 'pure'],
    rating: 4.6,
    rating_count: 150,
    warehouse_stock: [
      { warehouse_id: 'sultanganj', stock: 70 },
      { warehouse_id: 'bhagalpur', stock: 70 },
      { warehouse_id: 'khagaria', stock: 30 }
    ]
  },
  {
    id: 'juice-13',
    name_en: 'Tropicana Juice - Mixed Fruit',
    name_hi: 'Tropicana Juice - Mixed Fal',
    description: 'Blend of multiple fruit juices',
    brand: 'Tropicana',
    category_id: 'cat-3',
    mrp: 125,
    price: 115,
    stock_qty: 140,
    unit: 'tetra',
    pack_size: '1 L',
    is_veg: true,
    delivery_mode: 'standard',
    image: 'https://picsum.photos/seed/juice-13/400/400',
    imageHint: 'mixed fruit',
    tags: ['juice', 'mixed fruit', 'blend', 'fruit'],
    rating: 4.8,
    rating_count: 160,
    warehouse_stock: [
      { warehouse_id: 'sultanganj', stock: 60 },
      { warehouse_id: 'bhagalpur', stock: 60 },
      { warehouse_id: 'khagaria', stock: 20 }
    ]
  },
  {
    id: 'juice-14',
    name_en: 'Tropicana Juice - Mango',
    name_hi: 'Tropicana Juice - Aam',
    description: '100% pure mango juice',
    brand: 'Tropicana',
    category_id: 'cat-3',
    mrp: 135,
    price: 125,
    stock_qty: 210,
    unit: 'tetra',
    pack_size: '1 L',
    is_veg: true,
    delivery_mode: 'standard',
    image: 'https://picsum.photos/seed/juice-14/400/400',
    imageHint: 'mango juice',
    tags: ['juice', 'mango', 'fruit', 'pure'],
    rating: 4.9,
    rating_count: 230,
    warehouse_stock: [
      { warehouse_id: 'sultanganj', stock: 85 },
      { warehouse_id: 'bhagalpur', stock: 85 },
      { warehouse_id: 'khagaria', stock: 40 }
    ]
  },
  {
    id: 'juice-15',
    name_en: 'Slice Juice - Mango',
    name_hi: 'Slice Juice - Aam',
    description: 'Mango drink with pulp',
    brand: 'Slice',
    category_id: 'cat-3',
    mrp: 40,
    price: 35,
    stock_qty: 300,
    unit: 'tetra',
    pack_size: '250 ml',
    is_veg: true,
    delivery_mode: 'standard',
    image: 'https://picsum.photos/seed/juice-15/400/400',
    imageHint: 'mango pulp',
    tags: ['juice', 'mango', 'pulp', 'drink'],
    rating: 4.6,
    rating_count: 280,
    warehouse_stock: [
      { warehouse_id: 'sultanganj', stock: 120 },
      { warehouse_id: 'bhagalpur', stock: 120 },
      { warehouse_id: 'khagaria', stock: 60 }
    ]
  },
  {
    id: 'juice-16',
    name_en: 'Maaza Juice - Mango',
    name_hi: 'Maaza Juice - Aam',
    description: 'Thick mango drink',
    brand: 'Maaza',
    category_id: 'cat-3',
    mrp: 35,
    price: 30,
    stock_qty: 320,
    unit: 'tetra',
    pack_size: '250 ml',
    is_veg: true,
    delivery_mode: 'standard',
    image: 'https://picsum.photos/seed/juice-16/400/400',
    imageHint: 'mango drink',
    tags: ['juice', 'mango', 'thick', 'drink'],
    rating: 4.7,
    rating_count: 300,
    warehouse_stock: [
      { warehouse_id: 'sultanganj', stock: 130 },
      { warehouse_id: 'bhagalpur', stock: 130 },
      { warehouse_id: 'khagaria', stock: 60 }
    ]
  },
  {
    id: 'juice-17',
    name_en: 'Frooti Juice - Mango',
    name_hi: 'Frooti Juice - Aam',
    description: 'Mango flavored drink',
    brand: 'Frooti',
    category_id: 'cat-3',
    mrp: 30,
    price: 25,
    stock_qty: 350,
    unit: 'tetra',
    pack_size: '250 ml',
    is_veg: true,
    delivery_mode: 'standard',
    image: 'https://picsum.photos/seed/juice-17/400/400',
    imageHint: 'mango drink',
    tags: ['juice', 'mango', 'flavored', 'drink'],
    rating: 4.5,
    rating_count: 250,
    warehouse_stock: [
      { warehouse_id: 'sultanganj', stock: 140 },
      { warehouse_id: 'bhagalpur', stock: 140 },
      { warehouse_id: 'khagaria', stock: 70 }
    ]
  },
  {
    id: 'juice-18',
    name_en: 'Appy Fizz Juice',
    name_hi: 'Appy Fizz Juice',
    description: 'Sparkling apple drink',
    brand: 'Appy',
    category_id: 'cat-3',
    mrp: 45,
    price: 40,
    stock_qty: 180,
    unit: 'bottle',
    pack_size: '250 ml',
    is_veg: true,
    delivery_mode: 'standard',
    image: 'https://picsum.photos/seed/juice-18/400/400',
    imageHint: 'sparkling apple',
    tags: ['juice', 'apple', 'sparkling', 'fizz'],
    rating: 4.4,
    rating_count: 160,
    warehouse_stock: [
      { warehouse_id: 'sultanganj', stock: 70 },
      { warehouse_id: 'bhagalpur', stock: 70 },
      { warehouse_id: 'khagaria', stock: 40 }
    ]
  },
  {
    id: 'juice-19',
    name_en: 'Paper Boat Juice - Kokum',
    name_hi: 'Paper Boat Juice - Kokum',
    description: 'Traditional kokum drink',
    brand: 'Paper Boat',
    category_id: 'cat-3',
    mrp: 50,
    price: 45,
    stock_qty: 120,
    unit: 'tetra',
    pack_size: '250 ml',
    is_veg: true,
    delivery_mode: 'standard',
    image: 'https://picsum.photos/seed/juice-19/400/400',
    imageHint: 'kokum drink',
    tags: ['juice', 'kokum', 'traditional', 'drink'],
    rating: 4.6,
    rating_count: 100,
    warehouse_stock: [
      { warehouse_id: 'sultanganj', stock: 50 },
      { warehouse_id: 'bhagalpur', stock: 50 },
      { warehouse_id: 'khagaria', stock: 20 }
    ]
  },
  {
    id: 'juice-20',
    name_en: 'Paper Boat Juice - Aamras',
    name_hi: 'Paper Boat Juice - Aamras',
    description: 'Traditional mango pulp drink',
    brand: 'Paper Boat',
    category_id: 'cat-3',
    mrp: 55,
    price: 50,
    stock_qty: 150,
    unit: 'tetra',
    pack_size: '250 ml',
    is_veg: true,
    delivery_mode: 'standard',
    image: 'https://picsum.photos/seed/juice-20/400/400',
    imageHint: 'aamras drink',
    tags: ['juice', 'mango', 'aamras', 'traditional'],
    rating: 4.8,
    rating_count: 130,
    warehouse_stock: [
      { warehouse_id: 'sultanganj', stock: 60 },
      { warehouse_id: 'bhagalpur', stock: 60 },
      { warehouse_id: 'khagaria', stock: 30 }
    ]
  },
  {
    id: 'juice-21',
    name_en: 'Paper Boat Juice - Jamun',
    name_hi: 'Paper Boat Juice - Jamun',
    description: 'Black plum juice drink',
    brand: 'Paper Boat',
    category_id: 'cat-3',
    mrp: 60,
    price: 55,
    stock_qty: 100,
    unit: 'tetra',
    pack_size: '250 ml',
    is_veg: true,
    delivery_mode: 'standard',
    image: 'https://picsum.photos/seed/juice-21/400/400',
    imageHint: 'jamun juice',
    tags: ['juice', 'jamun', 'black plum', 'drink'],
    rating: 4.7,
    rating_count: 90,
    warehouse_stock: [
      { warehouse_id: 'sultanganj', stock: 40 },
      { warehouse_id: 'bhagalpur', stock: 40 },
      { warehouse_id: 'khagaria', stock: 20 }
    ]
  },
  {
    id: 'juice-22',
    name_en: 'Real Active Juice - Orange',
    name_hi: 'Real Active Juice - Narangi',
    description: 'Orange juice with no added sugar',
    brand: 'Real',
    category_id: 'cat-3',
    mrp: 130,
    price: 120,
    stock_qty: 140,
    unit: 'tetra',
    pack_size: '1 L',
    is_veg: true,
    delivery_mode: 'standard',
    image: 'https://picsum.photos/seed/juice-22/400/400',
    imageHint: 'healthy orange',
    tags: ['juice', 'orange', 'no sugar', 'healthy'],
    rating: 4.8,
    rating_count: 120,
    warehouse_stock: [
      { warehouse_id: 'sultanganj', stock: 60 },
      { warehouse_id: 'bhagalpur', stock: 60 },
      { warehouse_id: 'khagaria', stock: 20 }
    ]
  },
  {
    id: 'juice-23',
    name_en: 'Real Active Juice - Apple',
    name_hi: 'Real Active Juice - Seb',
    description: 'Apple juice with no added sugar',
    brand: 'Real',
    category_id: 'cat-3',
    mrp: 140,
    price: 130,
    stock_qty: 130,
    unit: 'tetra',
    pack_size: '1 L',
    is_veg: true,
    delivery_mode: 'standard',
    image: 'https://picsum.photos/seed/juice-23/400/400',
    imageHint: 'healthy apple',
    tags: ['juice', 'apple', 'no sugar', 'healthy'],
    rating: 4.7,
    rating_count: 110,
    warehouse_stock: [
      { warehouse_id: 'sultanganj', stock: 55 },
      { warehouse_id: 'bhagalpur', stock: 55 },
      { warehouse_id: 'khagaria', stock: 20 }
    ]
  },
  {
    id: 'juice-24',
    name_en: 'Tropicana Essentials - Orange',
    name_hi: 'Tropicana Essentials - Narangi',
    description: 'Orange juice with vitamins',
    brand: 'Tropicana',
    category_id: 'cat-3',
    mrp: 150,
    price: 140,
    stock_qty: 120,
    unit: 'tetra',
    pack_size: '1 L',
    is_veg: true,
    delivery_mode: 'standard',
    image: 'https://picsum.photos/seed/juice-24/400/400',
    imageHint: 'vitamin orange',
    tags: ['juice', 'orange', 'vitamins', 'healthy'],
    rating: 4.6,
    rating_count: 100,
    warehouse_stock: [
      { warehouse_id: 'sultanganj', stock: 50 },
      { warehouse_id: 'bhagalpur', stock: 50 },
      { warehouse_id: 'khagaria', stock: 20 }
    ]
  },
  {
    id: 'juice-25',
    name_en: 'Tropicana Essentials - Apple',
    name_hi: 'Tropicana Essentials - Seb',
    description: 'Apple juice with vitamins',
    brand: 'Tropicana',
    category_id: 'cat-3',
    mrp: 160,
    price: 150,
    stock_qty: 110,
    unit: 'tetra',
    pack_size: '1 L',
    is_veg: true,
    delivery_mode: 'standard',
    image: 'https://picsum.photos/seed/juice-25/400/400',
    imageHint: 'vitamin apple',
    tags: ['juice', 'apple', 'vitamins', 'healthy'],
    rating: 4.7,
    rating_count: 95,
    warehouse_stock: [
      { warehouse_id: 'sultanganj', stock: 45 },
      { warehouse_id: 'bhagalpur', stock: 45 },
      { warehouse_id: 'khagaria', stock: 20 }
    ]
  }
];
