import { Product } from '../../types';

export const FLOUR_PRODUCTS: Product[] = [
  {
    id: 'flour-1',
    name_en: 'Bajra Flour',
    name_hi: 'Bajre ka Atta',
    description: 'Pearl millet flour for rotis',
    brand: 'Organic Tattva',
    category_id: 'cat-4',
    mrp: 75,
    price: 70,
    stock_qty: 55,
    unit: 'kg',
    pack_size: '1 kg',
    is_veg: true,
    delivery_mode: 'standard',
    image: 'https://picsum.photos/seed/flour-1/400/400',
    imageHint: 'bajra flour',
    tags: ['flour', 'bajra', 'millet', 'healthy'],
    rating: 4.3,
    rating_count: 95,
    warehouse_stock: [
      { warehouse_id: 'sultanganj', stock: 25 },
      { warehouse_id: 'bhagalpur', stock: 18 },
      { warehouse_id: 'khagaria', stock: 12 }
    ],
    variants: [
      { id: 'flour-1-1', pack_size: '1 kg', mrp: 75, price: 70, stock_qty: 55 },
    ]
  },
  {
    id: 'flour-2',
    name_en: 'Wheat Flour',
    name_hi: 'Gehu ka Atta',
    description: 'Stone-ground whole wheat flour',
    brand: 'Bhagalpur Mills',
    category_id: 'cat-4',
    mrp: 45,
    price: 42,
    stock_qty: 120,
    unit: 'kg',
    pack_size: '5 kg',
    is_veg: true,
    delivery_mode: 'standard',
    image: 'https://picsum.photos/seed/flour-2/400/400',
    imageHint: 'wheat flour',
    tags: ['flour', 'wheat', 'atta'],
    rating: 4.5,
    rating_count: 210,
    warehouse_stock: [
      { warehouse_id: 'sultanganj', stock: 50 },
      { warehouse_id: 'bhagalpur', stock: 40 },
      { warehouse_id: 'khagaria', stock: 30 }
    ],
    variants: [
      { id: 'flour-2-1', pack_size: '1 kg', mrp: 50, price: 45, stock_qty: 60 },
      { id: 'flour-2-2', pack_size: '5 kg', mrp: 240, price: 220, stock_qty: 40 },
      { id: 'flour-2-3', pack_size: '10 kg', mrp: 450, price: 430, stock_qty: 20 },
    ]
  },
  {
    id: 'flour-3',
    name_en: 'Maize Flour',
    name_hi: 'Makke ka Atta',
    description: 'Corn flour ideal for rotis and pakoras',
    brand: 'Local Farm Fresh',
    category_id: 'cat-4',
    mrp: 60,
    price: 55,
    stock_qty: 80,
    unit: 'kg',
    pack_size: '2 kg',
    is_veg: true,
    delivery_mode: 'standard',
    image: 'https://picsum.photos/seed/flour-3/400/400',
    imageHint: 'maize flour',
    tags: ['flour', 'makka', 'corn'],
    rating: 4.2,
    rating_count: 75,
    warehouse_stock: [
      { warehouse_id: 'sultanganj', stock: 35 },
      { warehouse_id: 'bhagalpur', stock: 30 },
      { warehouse_id: 'khagaria', stock: 15 }
    ],
    variants: [
      { id: 'flour-3-1', pack_size: '1 kg', mrp: 35, price: 30, stock_qty: 40 },
      { id: 'flour-3-2', pack_size: '2 kg', mrp: 60, price: 55, stock_qty: 40 },
    ]
  },
  {
    id: 'flour-4',
    name_en: 'Rice Flour',
    name_hi: 'Chawal ka Atta',
    description: 'Fine ground rice flour',
    brand: 'Annapurna Agro',
    category_id: 'cat-4',
    mrp: 55,
    price: 50,
    stock_qty: 65,
    unit: 'kg',
    pack_size: '1 kg',
    is_veg: true,
    delivery_mode: 'standard',
    image: 'https://picsum.photos/seed/flour-4/400/400',
    imageHint: 'rice flour',
    tags: ['flour', 'rice', 'glutenfree'],
    rating: 4.1,
    rating_count: 68,
    warehouse_stock: [
      { warehouse_id: 'sultanganj', stock: 20 },
      { warehouse_id: 'bhagalpur', stock: 25 },
      { warehouse_id: 'khagaria', stock: 20 }
    ],
    variants: [
        { id: 'flour-4-1', pack_size: '1 kg', mrp: 55, price: 50, stock_qty: 65 },
    ]
  },
  {
    id: 'flour-5',
    name_en: 'Multigrain Flour',
    name_hi: 'MultiGrain Atta',
    description: 'Mix of wheat, ragi, soya and maize',
    brand: 'Organic India',
    category_id: 'cat-4',
    mrp: 85,
    price: 80,
    stock_qty: 45,
    unit: 'kg',
    pack_size: '2 kg',
    is_veg: true,
    delivery_mode: 'standard',
    image: 'https://picsum.photos/seed/flour-5/400/400',
    imageHint: 'multigrain flour',
    tags: ['flour', 'multigrain', 'healthy'],
    rating: 4.6,
    rating_count: 120,
    warehouse_stock: [
      { warehouse_id: 'sultanganj', stock: 15 },
      { warehouse_id: 'bhagalpur', stock: 20 },
      { warehouse_id: 'khagaria', stock: 10 }
    ],
    variants: [
      { id: 'flour-5-1', pack_size: '1 kg', mrp: 45, price: 42, stock_qty: 25 },
      { id: 'flour-5-2', pack_size: '2 kg', mrp: 85, price: 80, stock_qty: 20 },
    ]
  },
  {
    id: 'flour-6',
    name_en: 'Ragi Flour',
    name_hi: 'Ragi ka Atta',
    description: 'Finger millet flour rich in calcium',
    brand: 'Desi Organics',
    category_id: 'cat-4',
    mrp: 95,
    price: 90,
    stock_qty: 40,
    unit: 'kg',
    pack_size: '500 g',
    is_veg: true,
    delivery_mode: 'standard',
    image: 'https://picsum.photos/seed/flour-6/400/400',
    imageHint: 'ragi flour',
    tags: ['flour', 'ragi', 'millet'],
    rating: 4.4,
    rating_count: 85,
    warehouse_stock: [
      { warehouse_id: 'sultanganj', stock: 12 },
      { warehouse_id: 'bhagalpur', stock: 18 },
      { warehouse_id: 'khagaria', stock: 10 }
    ],
    variants: [
      { id: 'flour-6-1', pack_size: '500 g', mrp: 95, price: 90, stock_qty: 40 },
    ]
  },
  {
    id: 'flour-7',
    name_en: 'Roasted Gram Flour',
    name_hi: 'Chana ka Sattu',
    description: 'Roasted gram flour for drinks and parathas',
    brand: 'Bhagalpur Local',
    category_id: 'cat-4',
    mrp: 65,
    price: 60,
    stock_qty: 100,
    unit: 'kg',
    pack_size: '1 kg',
    is_veg: true,
    delivery_mode: 'standard',
    image: 'https://picsum.photos/seed/flour-7/400/400',
    imageHint: 'sattu flour',
    tags: ['flour', 'sattu', 'protein'],
    rating: 4.7,
    rating_count: 300,
    warehouse_stock: [
      { warehouse_id: 'sultanganj', stock: 40 },
      { warehouse_id: 'bhagalpur', stock: 35 },
      { warehouse_id: 'khagaria', stock: 25 }
    ],
    variants: [
      { id: 'flour-7-1', pack_size: '500 g', mrp: 35, price: 32, stock_qty: 50 },
      { id: 'flour-7-2', pack_size: '1 kg', mrp: 65, price: 60, stock_qty: 50 },
    ]
  },
  {
    id: 'flour-8',
    name_en: 'Besan',
    name_hi: 'Chane ka Besan',
    description: 'Gram flour for snacks and sweets',
    brand: 'Rajdhani',
    category_id: 'cat-4',
    mrp: 90,
    price: 85,
    stock_qty: 70,
    unit: 'kg',
    pack_size: '500 g',
    is_veg: true,
    delivery_mode: 'standard',
    image: 'https://picsum.photos/seed/flour-8/400/400',
    imageHint: 'besan flour',
    tags: ['flour', 'besan', 'gram'],
    rating: 4.5,
    rating_count: 150,
    warehouse_stock: [
      { warehouse_id: 'sultanganj', stock: 20 },
      { warehouse_id: 'bhagalpur', stock: 25 },
      { warehouse_id: 'khagaria', stock: 25 }
    ],
    variants: [
      { id: 'flour-8-1', pack_size: '500 g', mrp: 90, price: 85, stock_qty: 40 },
      { id: 'flour-8-2', pack_size: '1 kg', mrp: 170, price: 160, stock_qty: 30 },
    ]
  },
  {
    id: 'flour-9',
    name_en: 'Ashirwad Flour',
    name_hi: 'Ashirwad Atta',
    description: 'Flour made from Ashirwad',
    brand: 'Ashirwad',
    category_id: 'cat-4',
    mrp: 110,
    price: 105,
    stock_qty: 35,
    unit: 'kg',
    pack_size: '1 kg',
    is_veg: true,
    delivery_mode: 'standard',
    image: 'https://picsum.photos/seed/flour-9/400/400',
    imageHint: 'soybean flour',
    tags: ['flour', 'soybean', 'protein'],
    rating: 4.3,
    rating_count: 65,
    warehouse_stock: [
      { warehouse_id: 'sultanganj', stock: 10 },
      { warehouse_id: 'bhagalpur', stock: 15 },
      { warehouse_id: 'khagaria', stock: 10 }
    ],
    variants: [
      { id: 'flour-9-1', pack_size: '1 kg', mrp: 110, price: 105, stock_qty: 35 },
    ]
  },
  {
    id: 'flour-10',
    name_en: 'Jowar Flour',
    name_hi: 'Jowar ka Atta',
    description: 'Sorghum flour for rotis',
    brand: 'Organic Desi',
    category_id: 'cat-4',
    mrp: 70,
    price: 65,
    stock_qty: 60,
    unit: 'kg',
    pack_size: '1 kg',
    is_veg: true,
    delivery_mode: 'standard',
    image: 'https://picsum.photos/seed/flour-10/400/400',
    imageHint: 'jowar flour',
    tags: ['flour', 'jowar', 'millet'],
    rating: 4.2,
    rating_count: 90,
    warehouse_stock: [
      { warehouse_id: 'sultanganj', stock: 20 },
      { warehouse_id: 'bhagalpur', stock: 25 },
      { warehouse_id: 'khagaria', stock: 15 }
    ],
    variants: [
       { id: 'flour-10-1', pack_size: '1 kg', mrp: 70, price: 65, stock_qty: 60 },
    ]
  },
  {
    id: 'flour-11',
    name_en: 'Barley Flour',
    name_hi: 'Jau ka Atta',
    description: 'Barley flour for rotis and soups',
    brand: 'Organic Desi',
    category_id: 'cat-4',
    mrp: 80,
    price: 75,
    stock_qty: 50,
    unit: 'kg',
    pack_size: '1 kg',
    is_veg: true,
    delivery_mode: 'standard',
    image: 'https://picsum.photos/seed/flour-11/400/400',
    imageHint: 'barley flour',
    tags: ['flour', 'jau', 'barley'],
    rating: 4.3,
    rating_count: 60,
    warehouse_stock: [
      { warehouse_id: 'sultanganj', stock: 15 },
      { warehouse_id: 'bhagalpur', stock: 20 },
      { warehouse_id: 'khagaria', stock: 15 }
    ],
    variants: [
       { id: 'flour-11-1', pack_size: '1 kg', mrp: 80, price: 75, stock_qty: 50 },
    ]
  },
  {
    id: 'flour-12',
    name_en: 'Kuttu Flour',
    name_hi: 'Kuttu ka Atta',
    description: 'Buckwheat flour used in fasting',
    brand: 'Shudh Desi',
    category_id: 'cat-4',
    mrp: 95,
    price: 90,
    stock_qty: 30,
    unit: 'kg',
    pack_size: '500 g',
    is_veg: true,
    delivery_mode: 'standard',
    image: 'https://picsum.photos/seed/flour-12/400/400',
    imageHint: 'kuttu flour',
    tags: ['flour', 'kuttu', 'buckwheat'],
    rating: 4.2,
    rating_count: 48,
    warehouse_stock: [
      { warehouse_id: 'sultanganj', stock: 10 },
      { warehouse_id: 'bhagalpur', stock: 10 },
      { warehouse_id: 'khagaria', stock: 10 }
    ],
    variants: [
       { id: 'flour-12-1', pack_size: '500 g', mrp: 95, price: 90, stock_qty: 30 },
    ]
  },
  {
    id: 'flour-13',
    name_en: 'Singhara Flour',
    name_hi: 'Singhare ka Atta',
    description: 'Water chestnut flour, fasting special',
    brand: 'Desi Farms',
    category_id: 'cat-4',
    mrp: 105,
    price: 100,
    stock_qty: 40,
    unit: 'kg',
    pack_size: '500 g',
    is_veg: true,
    delivery_mode: 'standard',
    image: 'https://picsum.photos/seed/flour-13/400/400',
    imageHint: 'singhara flour',
    tags: ['flour', 'singhara', 'fasting'],
    rating: 4.1,
    rating_count: 42,
    warehouse_stock: [
      { warehouse_id: 'sultanganj', stock: 15 },
      { warehouse_id: 'bhagalpur', stock: 15 },
      { warehouse_id: 'khagaria', stock: 10 }
    ],
    variants: [
       { id: 'flour-13-1', pack_size: '500 g', mrp: 105, price: 100, stock_qty: 40 },
    ]
  },
  {
    id: 'flour-14',
    name_en: 'Chana Dal Flour',
    name_hi: 'Chane ka Atta',
    description: 'Flour made from split Bengal gram',
    brand: 'AgroFresh',
    category_id: 'cat-4',
    mrp: 85,
    price: 80,
    stock_qty: 55,
    unit: 'kg',
    pack_size: '1 kg',
    is_veg: true,
    delivery_mode: 'standard',
    image: 'https://picsum.photos/seed/flour-14/400/400',
    imageHint: 'chana dal flour',
    tags: ['flour', 'chana', 'protein'],
    rating: 4.3,
    rating_count: 70,
    warehouse_stock: [
      { warehouse_id: 'sultanganj', stock: 20 },
      { warehouse_id: 'bhagalpur', stock: 20 },
      { warehouse_id: 'khagaria', stock: 15 }
    ],
    variants: [
       { id: 'flour-14-1', pack_size: '1 kg', mrp: 85, price: 80, stock_qty: 55 },
    ]
  },
  {
    id: 'flour-15',
    name_en: 'Urad Dal Flour',
    name_hi: 'Urad Dal ka Atta',
    description: 'Flour from split urad dal',
    brand: 'Shakti Bhog',
    category_id: 'cat-4',
    mrp: 95,
    price: 90,
    stock_qty: 35,
    unit: 'kg',
    pack_size: '500 g',
    is_veg: true,
    delivery_mode: 'standard',
    image: 'https://picsum.photos/seed/flour-15/400/400',
    imageHint: 'urad dal flour',
    tags: ['flour', 'urad', 'protein'],
    rating: 4.0,
    rating_count: 38,
    warehouse_stock: [
      { warehouse_id: 'sultanganj', stock: 10 },
      { warehouse_id: 'bhagalpur', stock: 15 },
      { warehouse_id: 'khagaria', stock: 10 }
    ],
    variants: [
       { id: 'flour-15-1', pack_size: '500 g', mrp: 95, price: 90, stock_qty: 35 },
    ]
  },
  {
    id: 'flour-17',
    name_en: 'Moong Dal Flour',
    name_hi: 'Moong Dal ka Atta',
    description: 'Protein rich flour from moong dal',
    brand: 'Healthy Choice',
    category_id: 'cat-4',
    mrp: 100,
    price: 95,
    stock_qty: 28,
    unit: 'kg',
    pack_size: '500 g',
    is_veg: true,
    delivery_mode: 'standard',
    image: 'https://picsum.photos/seed/flour-17/400/400',
    imageHint: 'moong dal flour',
    tags: ['flour', 'moong', 'protein'],
    rating: 4.2,
    rating_count: 40,
    warehouse_stock: [
      { warehouse_id: 'sultanganj', stock: 8 },
      { warehouse_id: 'bhagalpur', stock: 10 },
      { warehouse_id: 'khagaria', stock: 10 }
    ],
    variants: [
       { id: 'flour-17-1', pack_size: '500 g', mrp: 100, price: 95, stock_qty: 28 },
    ]
  },
  {
    id: 'flour-18',
    name_en: 'Quinoa Flour',
    name_hi: 'Quinoa ka Atta',
    description: 'Gluten free quinoa flour',
    brand: 'Organic Harvest',
    category_id: 'cat-4',
    mrp: 150,
    price: 140,
    stock_qty: 20,
    unit: 'kg',
    pack_size: '500 g',
    is_veg: true,
    delivery_mode: 'standard',
    image: 'https://picsum.photos/seed/flour-18/400/400',
    imageHint: 'quinoa flour',
    tags: ['flour', 'quinoa', 'healthy'],
    rating: 4.5,
    rating_count: 30,
    warehouse_stock: [
      { warehouse_id: 'sultanganj', stock: 5 },
      { warehouse_id: 'bhagalpur', stock: 8 },
      { warehouse_id: 'khagaria', stock: 7 }
    ],
    variants: [
       { id: 'flour-18-1', pack_size: '500 g', mrp: 150, price: 140, stock_qty: 20 },
    ]
  }
];
