import { Product } from '../../types';

export const GRAINS_PRODUCTS: Product[] = [
  {
    id: 'pistachio-1',
    name_en: 'Pistachio',
    name_hi: 'Pista',
    description: 'High quality roasted and salted pistachios.',
    brand: 'Dry Fruit Hub',
    category_id: 'cat-4',
    mrp: 350,
    price: 320,
    stock_qty: 50,
    unit: 'grams',
    is_veg: true,
    delivery_mode: 'standard',
    image: 'https://firebasestorage.googleapis.com/v0/b/freshoz-fresh-fast.firebasestorage.app/o/categories%2Fstaples%2Fproducts%2Fpistachio.webp?alt=media&token=59230554-9556-429a-8a5e-b2d2a4506c28',
    imageHint: 'pistachio nuts',
    tags: ['dry fruit', 'nuts', 'pistachio', 'pista'],
    rating: 4.8,
    rating_count: 150,
    warehouse_stock: [{ warehouse_id: 'sultanganj', stock: 50 }],
    variants: [
      { id: 'pistachio-1-1', pack_size: '100g', mrp: 350, price: 320, stock_qty: 20 },
      { id: 'pistachio-1-2', pack_size: '200g', mrp: 680, price: 620, stock_qty: 20 },
      { id: 'pistachio-1-3', pack_size: '250g', mrp: 850, price: 770, stock_qty: 10 },
    ]
  },
  {
    id: 'rice-loose-1',
    name_en: 'Loose Rice',
    name_hi: 'Khula Chawal',
    description: 'Good quality loose rice for daily consumption.',
    brand: 'Local Mill',
    category_id: 'cat-4',
    mrp: 50,
    price: 45,
    stock_qty: 100,
    unit: 'kg',
    is_veg: true,
    delivery_mode: 'standard',
    image: 'https://firebasestorage.googleapis.com/v0/b/freshoz-fresh-fast.firebasestorage.app/o/categories%2Fstaples%2Fproducts%2Frice-loose.webp?alt=media&token=8d2e85a6-f283-42e7-9d7a-7c917ab8e90e',
    imageHint: 'loose rice',
    tags: ['rice', 'staple', 'loose', 'daily'],
    rating: 4.2,
    rating_count: 200,
    warehouse_stock: [{ warehouse_id: 'sultanganj', stock: 100 }],
    variants: [
      { id: 'rice-loose-1-1', pack_size: '1kg', mrp: 50, price: 45, stock_qty: 50 },
      { id: 'rice-loose-1-2', pack_size: '5kg', mrp: 240, price: 220, stock_qty: 30 },
      { id: 'rice-loose-1-3', pack_size: '10kg', mrp: 470, price: 430, stock_qty: 20 },
    ]
  },
  {
    id: 'cashew-1',
    name_en: 'Cashew Nuts',
    name_hi: 'Kaju',
    description: 'Premium quality whole cashew nuts.',
    brand: 'Dry Fruit Hub',
    category_id: 'cat-4',
    mrp: 250,
    price: 230,
    stock_qty: 60,
    unit: 'grams',
    is_veg: true,
    delivery_mode: 'standard',
    image: 'https://firebasestorage.googleapis.com/v0/b/freshoz-fresh-fast.firebasestorage.app/o/categories%2Fstaples%2Fproducts%2Fcashew.webp?alt=media&token=f0312521-1c39-4444-a10c-15796b27d422',
    imageHint: 'cashew nuts',
    tags: ['dry fruit', 'nuts', 'cashew', 'kaju'],
    rating: 4.9,
    rating_count: 180,
    warehouse_stock: [{ warehouse_id: 'sultanganj', stock: 60 }],
    variants: [
      { id: 'cashew-1-1', pack_size: '100g', mrp: 250, price: 230, stock_qty: 30 },
      { id: 'cashew-1-2', pack_size: '200g', mrp: 480, price: 450, stock_qty: 20 },
      { id: 'cashew-1-3', pack_size: '250g', mrp: 600, price: 550, stock_qty: 10 },
    ]
  },
  {
    id: 'grains-1',
    name_en: 'Assorted Grains',
    name_hi: 'Mishrit Anaaj',
    description: 'A mix of healthy whole grains.',
    brand: 'Healthy Harvest',
    category_id: 'cat-4',
    mrp: 100,
    price: 90,
    stock_qty: 80,
    unit: 'kg',
    is_veg: true,
    delivery_mode: 'standard',
    image: 'https://firebasestorage.googleapis.com/v0/b/freshoz-fresh-fast.firebasestorage.app/o/categories%2Fstaples%2Fproducts%2Fgrains.webp?alt=media&token=09c48b8c-5793-455b-b9d1-37d40e1b2123',
    imageHint: 'assorted grains',
    tags: ['grains', 'healthy', 'staple', 'anaaj'],
    rating: 4.5,
    rating_count: 120,
    warehouse_stock: [{ warehouse_id: 'sultanganj', stock: 80 }],
    variants: [
      { id: 'grains-1-1', pack_size: '500g', mrp: 55, price: 50, stock_qty: 40 },
      { id: 'grains-1-2', pack_size: '1kg', mrp: 100, price: 90, stock_qty: 30 },
      { id: 'grains-1-3', pack_size: '5kg', mrp: 480, price: 440, stock_qty: 10 },
    ]
  }
];
