import { Product } from '../../types';

export const GRAINS_PRODUCTS: Product[] = [
  {
    id: 'pistachio-1',
    name_en: 'Pistachio',
    name_hi: 'Pista',
    description: 'High quality roasted and salted pistachios.',
    brand: 'Dry Fruit Hub',
    category_id: 'cat-4',
    mrp: 350,
    price: 320,
    stock_qty: 50,
    unit: 'grams',
    is_veg: true,
    delivery_mode: 'standard',
    image: 'https://firebasestorage.googleapis.com/v0/b/freshoz-fresh-fast.firebasestorage.app/o/categories%2Fstaples%2Fproducts%2Fpistachio.webp?alt=media&token=59230554-9556-429a-8a5e-b2d2a4506c28',
    imageHint: 'pistachio nuts',
    tags: ['dry fruit', 'nuts', 'pistachio', 'pista'],
    rating: 4.8,
    rating_count: 150,
    warehouse_stock: [{ warehouse_id: 'sultanganj', stock: 50 }],
    variants: [
      { id: 'pistachio-1-1', pack_size: '100g', mrp: 350, price: 320, stock_qty: 20 },
      { id: 'pistachio-1-2', pack_size: '200g', mrp: 680, price: 620, stock_qty: 20 },
      { id: 'pistachio-1-3', pack_size: '250g', mrp: 850, price: 770, stock_qty: 10 },
    ]
  },
  {
    id: 'rice-loose-1',
    name_en: 'Loose Rice',
    name_hi: 'Khula Chawal',
    description: 'Good quality loose rice for daily consumption.',
    brand: 'Local Mill',
    category_id: 'cat-4',
    mrp: 50,
    price: 45,
    stock_qty: 100,
    unit: 'kg',
    is_veg: true,
    delivery_mode: 'standard',
    image: 'https://firebasestorage.googleapis.com/v0/b/freshoz-fresh-fast.firebasestorage.app/o/categories%2Fstaples%2Fproducts%2Frice-loose.webp?alt=media&token=8d2e85a6-f283-42e7-9d7a-7c917ab8e90e',
    imageHint: 'loose rice',
    tags: ['rice', 'staple', 'loose', 'daily'],
    rating: 4.2,
    rating_count: 200,
    warehouse_stock: [{ warehouse_id: 'sultanganj', stock: 100 }],
    variants: [
      { id: 'rice-loose-1-1', pack_size: '1kg', mrp: 50, price: 45, stock_qty: 50 },
      { id: 'rice-loose-1-2', pack_size: '5kg', mrp: 240, price: 220, stock_qty: 30 },
      { id: 'rice-loose-1-3', pack_size: '10kg', mrp: 470, price: 430, stock_qty: 20 },
    ]
  },
  {
    id: 'cashew-1',
    name_en: 'Cashew Nuts',
    name_hi: 'Kaju',
    description: 'Premium quality whole cashew nuts.',
    brand: 'Dry Fruit Hub',
    category_id: 'cat-4',
    mrp: 250,
    price: 230,
    stock_qty: 60,
    unit: 'grams',
    is_veg: true,
    delivery_mode: 'standard',
    image: 'https://firebasestorage.googleapis.com/v0/b/freshoz-fresh-fast.firebasestorage.app/o/categories%2Fstaples%2Fproducts%2Fcashew.webp?alt=media&token=f0312521-1c39-4444-a10c-15796b27d422',
    imageHint: 'cashew nuts',
    tags: ['dry fruit', 'nuts', 'cashew', 'kaju'],
    rating: 4.9,
    rating_count: 180,
    warehouse_stock: [{ warehouse_id: 'sultanganj', stock: 60 }],
    variants: [
      { id: 'cashew-1-1', pack_size: '100g', mrp: 250, price: 230, stock_qty: 30 },
      { id: 'cashew-1-2', pack_size: '200g', mrp: 480, price: 450, stock_qty: 20 },
      { id: 'cashew-1-3', pack_size: '250g', mrp: 600, price: 550, stock_qty: 10 },
    ]
  },
  {
    id: 'grains-1',
    name_en: 'Assorted Grains',
    name_hi: 'Mishrit Anaaj',
    description: 'A mix of healthy whole grains.',
    brand: 'Healthy Harvest',
    category_id: 'cat-4',
    mrp: 100,
    price: 90,
    stock_qty: 80,
    unit: 'kg',
    is_veg: true,
    delivery_mode: 'standard',
    image: 'https://firebasestorage.googleapis.com/v0/b/freshoz-fresh-fast.firebasestorage.app/o/categories%2Fstaples%2Fproducts%2Fgrains.webp?alt=media&token=09c48b8c-5793-455b-b9d1-37d40e1b2123',
    imageHint: 'assorted grains',
    tags: ['grains', 'healthy', 'staple', 'anaaj'],
    rating: 4.5,
    rating_count: 120,
    warehouse_stock: [{ warehouse_id: 'sultanganj', stock: 80 }],
    variants: [
      { id: 'grains-1-1', pack_size: '500g', mrp: 55, price: 50, stock_qty: 40 },
      { id: 'grains-1-2', pack_size: '1kg', mrp: 100, price: 90, stock_qty: 30 },
      { id: 'grains-1-3', pack_size: '5kg', mrp: 480, price: 440, stock_qty: 10 },
    ]
  },
  {
    id: 'grain-1',
    name_en: 'Basmati Rice',
    name_hi: 'बासमती चावल',
    description: 'Premium long-grain Basmati rice with aromatic flavor',
    brand: 'Indian Harvest',
    category_id: 'cat-4',
    mrp: 120,
    price: 100,
    stock_qty: 500,
    unit: '1 kg',
    pack_size: '1 kg',
    is_veg: true,
    delivery_mode: 'standard',
    image: 'https://picsum.photos/seed/grain-1/400/400',
    imageHint: 'basmati rice',
    tags: ['rice', 'basmati', 'grain', 'staple'],
    rating: 4.7,
    rating_count: 220,
    warehouse_stock: [
      { warehouse_id: 'sultanganj', stock: 200 },
      { warehouse_id: 'bhagalpur', stock: 150 },
      { warehouse_id: 'khagaria', stock: 150 }
    ],
    variants: [
      { id: 'grain-1-1', pack_size: '1 kg', mrp: 120, price: 100, stock_qty: 500 },
      { id: 'grain-1-2', pack_size: '5 kg', mrp: 580, price: 500, stock_qty: 200 }
    ]
  },
  {
    id: 'grain-2',
    name_en: 'Brown Rice',
    name_hi: 'ब्राउन राइस',
    description: 'Healthy brown rice, rich in fiber and nutrients',
    brand: 'Nature Foods',
    category_id: 'cat-4',
    mrp: 140,
    price: 125,
    stock_qty: 300,
    unit: '1 kg',
    pack_size: '1 kg',
    is_veg: true,
    delivery_mode: 'standard',
    image: 'https://picsum.photos/seed/grain-2/400/400',
    imageHint: 'brown rice',
    tags: ['rice', 'brown', 'healthy', 'staple'],
    rating: 4.6,
    rating_count: 150,
    warehouse_stock: [
      { warehouse_id: 'sultanganj', stock: 100 },
      { warehouse_id: 'bhagalpur', stock: 100 },
      { warehouse_id: 'khagaria', stock: 100 }
    ],
    variants: [{ id: 'grain-2-1', pack_size: '1 kg', mrp: 140, price: 125, stock_qty: 300 }]
  },
  {
    id: 'grain-3',
    name_en: 'Wheat Flour',
    name_hi: 'गेहूं का आटा',
    description: 'Fine wheat flour for daily baking and cooking',
    brand: 'Golden Wheat',
    category_id: 'cat-4',
    mrp: 50,
    price: 45,
    stock_qty: 400,
    unit: '1 kg',
    pack_size: '1 kg',
    is_veg: true,
    delivery_mode: 'standard',
    image: 'https://picsum.photos/seed/grain-3/400/400',
    imageHint: 'wheat flour',
    tags: ['flour', 'wheat', 'staple'],
    rating: 4.5,
    rating_count: 180,
    warehouse_stock: [
      { warehouse_id: 'sultanganj', stock: 200 },
      { warehouse_id: 'bhagalpur', stock: 100 },
      { warehouse_id: 'khagaria', stock: 100 }
    ],
    variants: [
      { id: 'grain-3-1', pack_size: '1 kg', mrp: 50, price: 45, stock_qty: 400 },
      { id: 'grain-3-2', pack_size: '5 kg', mrp: 240, price: 220, stock_qty: 150 }
    ]
  },
  {
    id: 'grain-4',
    name_en: 'Ragi Flour',
    name_hi: 'रागी का आटा',
    description: 'Nutritious finger millet flour for healthy meals',
    brand: 'Health Harvest',
    category_id: 'cat-4',
    mrp: 60,
    price: 55,
    stock_qty: 250,
    unit: '1 kg',
    pack_size: '1 kg',
    is_veg: true,
    delivery_mode: 'standard',
    image: 'https://picsum.photos/seed/grain-4/400/400',
    imageHint: 'ragi flour',
    tags: ['ragi', 'millet', 'flour', 'healthy'],
    rating: 4.6,
    rating_count: 120,
    warehouse_stock: [
      { warehouse_id: 'sultanganj', stock: 100 },
      { warehouse_id: 'bhagalpur', stock: 100 },
      { warehouse_id: 'khagaria', stock: 50 }
    ],
    variants: [{ id: 'grain-4-1', pack_size: '1 kg', mrp: 60, price: 55, stock_qty: 250 }]
  },
  {
    id: 'grain-5',
    name_en: 'Maize Flour',
    name_hi: 'मक्का का आटा',
    description: 'Finely ground maize flour for cooking and baking',
    brand: 'Cornfield',
    category_id: 'cat-4',
    mrp: 55,
    price: 50,
    stock_qty: 200,
    unit: '1 kg',
    pack_size: '1 kg',
    is_veg: true,
    delivery_mode: 'standard',
    image: 'https://picsum.photos/seed/grain-5/400/400',
    imageHint: 'maize flour',
    tags: ['maize', 'flour', 'staple'],
    rating: 4.4,
    rating_count: 90,
    warehouse_stock: [
      { warehouse_id: 'sultanganj', stock: 80 },
      { warehouse_id: 'bhagalpur', stock: 60 },
      { warehouse_id: 'khagaria', stock: 60 }
    ],
    variants: [{ id: 'grain-5-1', pack_size: '1 kg', mrp: 55, price: 50, stock_qty: 200 }]
  },
  {
    id: 'grain-6',
    name_en: 'Oats',
    name_hi: 'ओट्स',
    description: 'Whole rolled oats for healthy breakfast',
    brand: 'Healthy Start',
    category_id: 'cat-4',
    mrp: 100,
    price: 90,
    stock_qty: 300,
    unit: '500 g',
    pack_size: '500 g',
    is_veg: true,
    delivery_mode: 'standard',
    image: 'https://picsum.photos/seed/grain-6/400/400',
    imageHint: 'oats',
    tags: ['oats', 'healthy', 'breakfast', 'grain'],
    rating: 4.5,
    rating_count: 100,
    warehouse_stock: [
      { warehouse_id: 'sultanganj', stock: 100 },
      { warehouse_id: 'bhagalpur', stock: 100 },
      { warehouse_id: 'khagaria', stock: 100 }
    ],
    variants: [{ id: 'grain-6-1', pack_size: '500 g', mrp: 100, price: 90, stock_qty: 300 }]
  },
  {
    id: 'grain-7',
    name_en: 'Barley',
    name_hi: 'जौ',
    description: 'High-quality barley for soups and porridge',
    brand: 'Grain House',
    category_id: 'cat-4',
    mrp: 80,
    price: 70,
    stock_qty: 200,
    unit: '500 g',
    pack_size: '500 g',
    is_veg: true,
    delivery_mode: 'standard',
    image: 'https://picsum.photos/seed/grain-7/400/400',
    imageHint: 'barley',
    tags: ['barley', 'grain', 'healthy'],
    rating: 4.4,
    rating_count: 80,
    warehouse_stock: [
      { warehouse_id: 'sultanganj', stock: 70 },
      { warehouse_id: 'bhagalpur', stock: 70 },
      { warehouse_id: 'khagaria', stock: 60 }
    ],
    variants: [{ id: 'grain-7-1', pack_size: '500 g', mrp: 80, price: 70, stock_qty: 200 }]
  },
  {
    id: 'grain-8',
    name_en: 'Millet Mix',
    name_hi: 'मिलेट मिक्स',
    description: 'Healthy mix of multiple millet grains',
    brand: 'Nature Farm',
    category_id: 'cat-4',
    mrp: 90,
    price: 80,
    stock_qty: 150,
    unit: '500 g',
    pack_size: '500 g',
    is_veg: true,
    delivery_mode: 'standard',
    image: 'https://picsum.photos/seed/grain-8/400/400',
    imageHint: 'millet mix',
    tags: ['millet', 'mix', 'healthy', 'grain'],
    rating: 4.6,
    rating_count: 60,
    warehouse_stock: [
      { warehouse_id: 'sultanganj', stock: 50 },
      { warehouse_id: 'bhagalpur', stock: 50 },
      { warehouse_id: 'khagaria', stock: 50 }
    ],
    variants: [{ id: 'grain-8-1', pack_size: '500 g', mrp: 90, price: 80, stock_qty: 150 }]
  },
  {
    id: 'grain-9',
    name_en: 'Corn Kernels',
    name_hi: 'मक्का के दाने',
    description: 'Sweet corn kernels for cooking or snacking',
    brand: 'Sweet Corn Co.',
    category_id: 'cat-4',
    mrp: 60,
    price: 50,
    stock_qty: 200,
    unit: '500 g',
    pack_size: '500 g',
    is_veg: true,
    delivery_mode: 'standard',
    image: 'https://picsum.photos/seed/grain-9/400/400',
    imageHint: 'corn kernels',
    tags: ['corn', 'kernels', 'grain', 'staple'],
    rating: 4.5,
    rating_count: 70,
    warehouse_stock: [
      { warehouse_id: 'sultanganj', stock: 70 },
      { warehouse_id: 'bhagalpur', stock: 60 },
      { warehouse_id: 'khagaria', stock: 70 }
    ],
    variants: [{ id: 'grain-9-1', pack_size: '500 g', mrp: 60, price: 50, stock_qty: 200 }]
  },
  {
    id: 'grain-10',
    name_en: 'Quinoa',
    name_hi: 'क्विनोआ',
    description: 'High-protein quinoa for healthy meals',
    brand: 'SuperGrain',
    category_id: 'cat-4',
    mrp: 200,
    price: 180,
    stock_qty: 100,
    unit: '250 g',
    pack_size: '250 g',
    is_veg: true,
    delivery_mode: 'standard',
    image: 'https://picsum.photos/seed/grain-10/400/400',
    imageHint: 'quinoa',
    tags: ['quinoa', 'grain', 'protein', 'healthy'],
    rating: 4.7,
    rating_count: 50,
    warehouse_stock: [
      { warehouse_id: 'sultanganj', stock: 40 },
      { warehouse_id: 'bhagalpur', stock: 30 },
      { warehouse_id: 'khagaria', stock: 30 }
    ],
    variants: [{ id: 'grain-10-1', pack_size: '250 g', mrp: 200, price: 180, stock_qty: 100 }]
  },
 
];
