import { Product } from '../../types';

export const PULSES_PRODUCTS: Product[] = [
  {
    id: 'pulse-1',
    name_en: 'Toor Dal',
    name_hi: 'Arhar Dal',
    description: 'Premium quality toor dal for everyday cooking',
    brand: 'Tata Sampann',
    category_id: 'cat-4',
    mrp: 140,
    price: 130,
    stock_qty: 100,
    unit: 'kg',
    pack_size: '1 kg',
    is_veg: true,
    delivery_mode: 'standard',
    image: 'https://picsum.photos/seed/pulse-1/400/400',
    imageHint: 'toor dal',
    tags: ['pulses', 'toor dal', 'arhar'],
    rating: 4.5,
    rating_count: 220,
    warehouse_stock: [
      { warehouse_id: 'sultanganj', stock: 35 },
      { warehouse_id: 'bhagalpur', stock: 0 },
      { warehouse_id: 'khagaria', stock: 0 }
    ],
    variants: [
      { id: 'pulse-1-1', pack_size: '500 g', mrp: 70, price: 65, stock_qty: 50 },
      { id: 'pulse-1-2', pack_size: '1 kg', mrp: 140, price: 130, stock_qty: 50 },
    ]
  },
  {
    id: 'pulse-2',
    name_en: 'Chana Dal',
    name_hi: 'Chana Dal',
    description: 'Rich in protein and fiber, best for curries',
    brand: 'Fortune',
    category_id: 'cat-4',
    mrp: 110,
    price: 100,
    stock_qty: 90,
    unit: 'kg',
    pack_size: '1 kg',
    is_veg: true,
    delivery_mode: 'standard',
    image: 'https://picsum.photos/seed/pulse-2/400/400',
    imageHint: 'chana dal',
    tags: ['pulses', 'chana dal'],
    rating: 4.3,
    rating_count: 180,
    warehouse_stock: [
      { warehouse_id: 'sultanganj', stock: 30 },
      { warehouse_id: 'bhagalpur', stock: 0 },
      { warehouse_id: 'khagaria', stock: 0 }
    ],
    variants: [
        { id: 'pulse-2-1', pack_size: '1 kg', mrp: 110, price: 100, stock_qty: 90 },
    ]
  },
  {
    id: 'pulse-3',
    name_en: 'Moong Dal',
    name_hi: 'Moong Dal',
    description: 'Yellow split moong dal, easy to digest',
    brand: 'Organic Tattva',
    category_id: 'cat-4',
    mrp: 120,
    price: 115,
    stock_qty: 85,
    unit: 'kg',
    pack_size: '1 kg',
    is_veg: true,
    delivery_mode: 'standard',
    image: 'https://picsum.photos/seed/pulse-3/400/400',
    imageHint: 'moong dal',
    tags: ['pulses', 'moong dal'],
    rating: 4.6,
    rating_count: 200,
    warehouse_stock: [
      { warehouse_id: 'sultanganj', stock: 25 },
      { warehouse_id: 'bhagalpur', stock: 0 },
      { warehouse_id: 'khagaria', stock: 0 }
    ],
    variants: [
        { id: 'pulse-3-1', pack_size: '1 kg', mrp: 120, price: 115, stock_qty: 85 },
    ]
  },
  {
    id: 'pulse-4',
    name_en: 'Masoor Dal',
    name_hi: 'Masoor Dal',
    description: 'Whole red lentils, rich in nutrients',
    brand: 'Local Farm',
    category_id: 'cat-4',
    mrp: 100,
    price: 95,
    stock_qty: 80,
    unit: 'kg',
    pack_size: '1 kg',
    is_veg: true,
    delivery_mode: 'standard',
    image: 'https://picsum.photos/seed/pulse-4/400/400',
    imageHint: 'masoor dal',
    tags: ['pulses', 'masoor dal'],
    rating: 4.2,
    rating_count: 150,
    warehouse_stock: [
      { warehouse_id: 'sultanganj', stock: 25 },
      { warehouse_id: 'bhagalpur', stock: 0 },
      { warehouse_id: 'khagaria', stock: 0 }
    ],
    variants: [
        { id: 'pulse-4-1', pack_size: '1 kg', mrp: 100, price: 95, stock_qty: 80 },
    ]
  },
  {
    id: 'pulse-5',
    name_en: 'Urad Dal',
    name_hi: 'Urad Dal',
    description: 'Split urad dal for dal makhani and dosas',
    brand: 'Fortune',
    category_id: 'cat-4',
    mrp: 130,
    price: 120,
    stock_qty: 70,
    unit: 'kg',
    pack_size: '1 kg',
    is_veg: true,
    delivery_mode: 'standard',
    image: 'https://picsum.photos/seed/pulse-5/400/400',
    imageHint: 'urad dal',
    tags: ['pulses', 'urad dal'],
    rating: 4.4,
    rating_count: 160,
    warehouse_stock: [
      { warehouse_id: 'sultanganj', stock: 20 },
      { warehouse_id: 'bhagalpur', stock: 0 },
      { warehouse_id: 'khagaria', stock: 0 }
    ],
    variants: [
        { id: 'pulse-5-1', pack_size: '1 kg', mrp: 130, price: 120, stock_qty: 70 },
    ]
  },
  {
    id: 'pulse-6',
    name_en: 'Kabuli Chana',
    name_hi: 'Kabuli Chana',
    description: 'White chickpeas, rich in protein',
    brand: 'Natureland',
    category_id: 'cat-4',
    mrp: 150,
    price: 140,
    stock_qty: 65,
    unit: 'kg',
    pack_size: '1 kg',
    is_veg: true,
    delivery_mode: 'standard',
    image: 'https://picsum.photos/seed/pulse-6/400/400',
    imageHint: 'kabuli chana',
    tags: ['pulses', 'kabuli chana', 'chickpeas'],
    rating: 4.5,
    rating_count: 140,
    warehouse_stock: [
      { warehouse_id: 'sultanganj', stock: 20 },
      { warehouse_id: 'bhagalpur', stock: 0 },
      { warehouse_id: 'khagaria', stock: 0 }
    ],
    variants: [
        { id: 'pulse-6-1', pack_size: '1 kg', mrp: 150, price: 140, stock_qty: 65 },
    ]
  },
  {
    id: 'pulse-7',
    name_en: 'Kala Chana',
    name_hi: 'Kala Chana',
    description: 'Black chickpeas, high in fiber',
    brand: 'Local Mill',
    category_id: 'cat-4',
    mrp: 95,
    price: 90,
    stock_qty: 75,
    unit: 'kg',
    pack_size: '1 kg',
    is_veg: true,
    delivery_mode: 'standard',
    image: 'https://picsum.photos/seed/pulse-7/400/400',
    imageHint: 'kala chana',
    tags: ['pulses', 'kala chana'],
    rating: 4.1,
    rating_count: 120,
    warehouse_stock: [
      { warehouse_id: 'sultanganj', stock: 25 },
      { warehouse_id: 'bhagalpur', stock: 0 },
      { warehouse_id: 'khagaria', stock: 0 }
    ],
    variants: [
        { id: 'pulse-7-1', pack_size: '1 kg', mrp: 95, price: 90, stock_qty: 75 },
    ]
  },
  {
    id: 'pulse-8',
    name_en: 'Green Moong',
    name_hi: 'Sabut Moong',
    description: 'Whole green gram, sprouting quality',
    brand: 'Organic India',
    category_id: 'cat-4',
    mrp: 110,
    price: 105,
    stock_qty: 60,
    unit: 'kg',
    pack_size: '1 kg',
    is_veg: true,
    delivery_mode: 'standard',
    image: 'https://picsum.photos/seed/pulse-8/400/400',
    imageHint: 'green moong',
    tags: ['pulses', 'sabut moong'],
    rating: 4.3,
    rating_count: 100,
    warehouse_stock: [
      { warehouse_id: 'sultanganj', stock: 20 },
      { warehouse_id: 'bhagalpur', stock: 0 },
      { warehouse_id: 'khagaria', stock: 0 }
    ],
    variants: [
        { id: 'pulse-8-1', pack_size: '1 kg', mrp: 110, price: 105, stock_qty: 60 },
    ]
  },
  {
    id: 'pulse-9',
    name_en: 'Rajma Chitra',
    name_hi: 'Rajma Chitra',
    description: 'Chitra rajma beans, perfect for curries',
    brand: 'Rajdhani',
    category_id: 'cat-4',
    mrp: 160,
    price: 150,
    stock_qty: 70,
    unit: 'kg',
    pack_size: '1 kg',
    is_veg: true,
    delivery_mode: 'standard',
    image: 'https://picsum.photos/seed/pulse-9/400/400',
    imageHint: 'rajma chitra',
    tags: ['pulses', 'rajma'],
    rating: 4.5,
    rating_count: 150,
    warehouse_stock: [
      { warehouse_id: 'sultanganj', stock: 25 },
      { warehouse_id: 'bhagalpur', stock: 0 },
      { warehouse_id: 'khagaria', stock: 0 }
    ],
    variants: [
        { id: 'pulse-9-1', pack_size: '1 kg', mrp: 160, price: 150, stock_qty: 70 },
    ]
  },
  {
    id: 'pulse-10',
    name_en: 'Rajma Red',
    name_hi: 'Rajma Lal',
    description: 'Small red kidney beans, rich in taste',
    brand: 'Local Farm',
    category_id: 'cat-4',
    mrp: 140,
    price: 130,
    stock_qty: 55,
    unit: 'kg',
    pack_size: '1 kg',
    is_veg: true,
    delivery_mode: 'standard',
    image: 'https://picsum.photos/seed/pulse-10/400/400',
    imageHint: 'rajma red',
    tags: ['pulses', 'rajma lal'],
    rating: 4.2,
    rating_count: 100,
    warehouse_stock: [
      { warehouse_id: 'sultanganj', stock: 20 },
      { warehouse_id: 'bhagalpur', stock: 0 },
      { warehouse_id: 'khagaria', stock: 0 }
    ],
    variants: [
        { id: 'pulse-10-1', pack_size: '1 kg', mrp: 140, price: 130, stock_qty: 55 },
    ]
  },
  {
    id: 'pulse-11',
    name_en: 'Lobia',
    name_hi: 'Lobia',
    description: 'Black-eyed peas for curries and salads',
    brand: 'Fortune',
    category_id: 'cat-4',
    mrp: 120,
    price: 115,
    stock_qty: 65,
    unit: 'kg',
    pack_size: '1 kg',
    is_veg: true,
    delivery_mode: 'standard',
    image: 'https://picsum.photos/seed/pulse-11/400/400',
    imageHint: 'lobia beans',
    tags: ['pulses', 'lobia'],
    rating: 4.1,
    rating_count: 95,
    warehouse_stock: [
      { warehouse_id: 'sultanganj', stock: 20 },
      { warehouse_id: 'bhagalpur', stock: 0 },
      { warehouse_id: 'khagaria', stock: 0 }
    ],
    variants: [
        { id: 'pulse-11-1', pack_size: '1 kg', mrp: 120, price: 115, stock_qty: 65 },
    ]
  },
  {
    id: 'pulse-12',
    name_en: 'Green Peas Dry',
    name_hi: 'Sukhi Matar',
    description: 'Dried green peas for snacks and curries',
    brand: 'Local Mill',
    category_id: 'cat-4',
    mrp: 90,
    price: 85,
    stock_qty: 70,
    unit: 'kg',
    pack_size: '1 kg',
    is_veg: true,
    delivery_mode: 'standard',
    image: 'https://picsum.photos/seed/pulse-12/400/400',
    imageHint: 'dry green peas',
    tags: ['pulses', 'matar'],
    rating: 4.0,
    rating_count: 85,
    warehouse_stock: [
      { warehouse_id: 'sultanganj', stock: 25 },
      { warehouse_id: 'bhagalpur', stock: 0 },
      { warehouse_id: 'khagaria', stock: 0 }
    ],
    variants: [
        { id: 'pulse-12-1', pack_size: '1 kg', mrp: 90, price: 85, stock_qty: 70 },
    ]
  },
  {
    id: 'pulse-13',
    name_en: 'Horse Gram',
    name_hi: 'Kulthi (Kurthi) Dal',
    description: 'Traditional kulthi dal with medicinal value',
    brand: 'Organic India',
    category_id: 'cat-4',
    mrp: 80,
    price: 75,
    stock_qty: 50,
    unit: 'kg',
    pack_size: '1 kg',
    is_veg: true,
    delivery_mode: 'standard',
    image: 'https://picsum.photos/seed/pulse-13/400/400',
    imageHint: 'horse gram',
    tags: ['pulses', 'kulthi dal'],
    rating: 4.0,
    rating_count: 70,
    warehouse_stock: [
      { warehouse_id: 'sultanganj', stock: 15 },
      { warehouse_id: 'bhagalpur', stock: 0 },
      { warehouse_id: 'khagaria', stock: 0 }
    ],
    variants: [
        { id: 'pulse-13-1', pack_size: '1 kg', mrp: 80, price: 75, stock_qty: 50 },
    ]
  },
  {
    id: 'pulse-14',
    name_en: 'Moth Beans',
    name_hi: 'Matki',
    description: 'Nutritious matki beans used in sprouts',
    brand: 'Local Farm',
    category_id: 'cat-4',
    mrp: 85,
    price: 80,
    stock_qty: 60,
    unit: 'kg',
    pack_size: '1 kg',
    is_veg: true,
    delivery_mode: 'standard',
    image: 'https://picsum.photos/seed/pulse-14/400/400',
    imageHint: 'moth beans',
    tags: ['pulses', 'matki'],
    rating: 4.2,
    rating_count: 90,
    warehouse_stock: [
      { warehouse_id: 'sultanganj', stock: 20 },
      { warehouse_id: 'bhagalpur', stock: 0 },
      { warehouse_id: 'khagaria', stock: 0 }
    ],
    variants: [
        { id: 'pulse-14-1', pack_size: '1 kg', mrp: 85, price: 80, stock_qty: 60 },
    ]
  },
  {
    id: 'pulse-15',
    name_en: 'Masoor Malka Dal',
    name_hi: 'Masoor Dal',
    description: 'Polished masoor dal for quick cooking',
    brand: 'Rajdhani',
    category_id: 'cat-4',
    mrp: 95,
    price: 90,
    stock_qty: 65,
    unit: 'kg',
    pack_size: '1 kg',
    is_veg: true,
    delivery_mode: 'standard',
    image: 'https://picsum.photos/seed/pulse-15/400/400',
    imageHint: 'masoor malka',
    tags: ['pulses', 'malka dal'],
    rating: 4.3,
    rating_count: 120,
    warehouse_stock: [
      { warehouse_id: 'sultanganj', stock: 20 },
      { warehouse_id: 'bhagalpur', stock: 0 },
      { warehouse_id: 'khagaria', stock: 0 }
    ],
    variants: [
        { id: 'pulse-15-1', pack_size: '1 kg', mrp: 95, price: 90, stock_qty: 65 },
    ]
  },
  {
    id: 'pulse-16',
    name_en: 'Moong Chilka',
    name_hi: 'Moong Chilka',
    description: 'Split moong with green skin intact',
    brand: 'Organic Tattva',
    category_id: 'cat-4',
    mrp: 125,
    price: 120,
    stock_qty: 60,
    unit: 'kg',
    pack_size: '1 kg',
    is_veg: true,
    delivery_mode: 'standard',
    image: 'https://picsum.photos/seed/pulse-16/400/400',
    imageHint: 'moong chilka',
    tags: ['pulses', 'moong chilka'],
    rating: 4.2,
    rating_count: 110,
    warehouse_stock: [
      { warehouse_id: 'sultanganj', stock: 20 },
      { warehouse_id: 'bhagalpur', stock: 0 },
      { warehouse_id: 'khagaria', stock: 0 }
    ],
    variants: [
        { id: 'pulse-16-1', pack_size: '1 kg', mrp: 125, price: 120, stock_qty: 60 },
    ]
  },
  {
    id: 'pulse-17',
    name_en: 'Local Gram',
    name_hi: 'Desi Chana',
    description: 'Small brown gram, rich in protein',
    brand: 'Local Mill',
    category_id: 'cat-4',
    mrp: 90,
    price: 85,
    stock_qty: 70,
    unit: 'kg',
    pack_size: '1 kg',
    is_veg: true,
    delivery_mode: 'standard',
    image: 'https://picsum.photos/seed/pulse-17/400/400',
    imageHint: 'desi chana',
    tags: ['pulses', 'desi chana'],
    rating: 4.1,
    rating_count: 95,
    warehouse_stock: [
      { warehouse_id: 'sultanganj', stock: 25 },
      { warehouse_id: 'bhagalpur', stock: 0 },
      { warehouse_id: 'khagaria', stock: 0 }
    ],
    variants: [
        { id: 'pulse-17-1', pack_size: '1 kg', mrp: 90, price: 85, stock_qty: 70 },
    ]
  },
  {
    id: 'pulse-18',
    name_en: 'Yellow Peas Dry',
    name_hi: 'Sukhi Peeli Matar',
    description: 'Dried yellow peas, used in Bengal recipes',
    brand: 'Local Farm',
    category_id: 'cat-4',
    mrp: 80,
    price: 75,
    stock_qty: 55,
    unit: 'kg',
    pack_size: '1 kg',
    is_veg: true,
    delivery_mode: 'standard',
    image: 'https://picsum.photos/seed/pulse-18/400/400',
    imageHint: 'yellow peas',
    tags: ['pulses', 'yellow peas'],
    rating: 4.0,
    rating_count: 80,
    warehouse_stock: [
      { warehouse_id: 'sultanganj', stock: 20 },
      { warehouse_id: 'bhagalpur', stock: 0 },
      { warehouse_id: 'khagaria', stock: 0 }
    ],
    variants: [
        { id: 'pulse-18-1', pack_size: '1 kg', mrp: 80, price: 75, stock_qty: 55 },
    ]
  },
  {
    id: 'pulse-19',
    name_en: 'Fortune Soybean',
    name_hi: 'Fortune Soyabean',
    description: 'Protein-rich soybean for curries and flour',
    brand: 'Fortune',
    category_id: 'cat-4',
    mrp: 85,
    price: 80,
    stock_qty: 60,
    unit: 'kg',
    pack_size: '1 kg',
    is_veg: true,
    delivery_mode: 'standard',
    image: 'https://picsum.photos/seed/pulse-19/400/400',
    imageHint: 'soybean',
    tags: ['pulses', 'soybean'],
    rating: 4.2,
    rating_count: 100,
    warehouse_stock: [
      { warehouse_id: 'sultanganj', stock: 20 },
      { warehouse_id: 'bhagalpur', stock: 0 },
      { warehouse_id: 'khagaria', stock: 0 }
    ],
    variants: [
        { id: 'pulse-19-1', pack_size: '1 kg', mrp: 85, price: 80, stock_qty: 60 },
    ]
  }
];
