import { Product } from '../../types';

export const READY_TO_EAT_PRODUCTS: Product[] = [
  {
    id: 'rte-1',
    name_en: 'Veg Biryani Ready Mix',
    name_hi: 'Veg Biryani Ready Mix',
    description: 'Instant ready-to-eat veg biryani mix with rich aroma and flavor',
    brand: 'Kitchen King',
    category_id: 'cat-7',
    mrp: 160,
    price: 140,
    stock_qty: 200,
    unit: '250 g',
    pack_size: '250 g',
    is_veg: true,
    delivery_mode: 'standard',
    image: 'https://picsum.photos/seed/rte-1/400/400',
    imageHint: 'veg biryani ready mix',
    tags: ['biryani', 'ready mix', 'instant', 'meal'],
    rating: 4.6,
    rating_count: 200,
    warehouse_stock: [
      { warehouse_id: 'sultanganj', stock: 100 },
      { warehouse_id: 'bhagalpur', stock: 60 },
      { warehouse_id: 'khagaria', stock: 40 }
    ],
    variants: [{ id: 'rte-1-1', pack_size: '250 g', mrp: 160, price: 140, stock_qty: 200 }]
  },
  {
    id: 'rte-2',
    name_en: 'Paneer Butter Masala',
    name_hi: 'Paneer Butter Masala',
    description: 'Delicious ready-to-eat paneer butter masala in rich gravy',
    brand: 'MTR Foods',
    category_id: 'cat-7',
    mrp: 120,
    price: 110,
    stock_qty: 250,
    unit: '300 g',
    pack_size: '300 g',
    is_veg: true,
    delivery_mode: 'standard',
    image: 'https://picsum.photos/seed/rte-2/400/400',
    imageHint: 'paneer butter masala ready meal',
    tags: ['paneer', 'ready meal', 'masala', 'gravy'],
    rating: 4.7,
    rating_count: 180,
    warehouse_stock: [
      { warehouse_id: 'sultanganj', stock: 120 },
      { warehouse_id: 'bhagalpur', stock: 80 },
      { warehouse_id: 'khagaria', stock: 50 }
    ],
    variants: [{ id: 'rte-2-1', pack_size: '300 g', mrp: 120, price: 110, stock_qty: 250 }]
  },
  {
    id: 'rte-3',
    name_en: 'Dal Makhani',
    name_hi: 'Dal Makhani',
    description: 'Creamy ready-to-eat dal makhani made with authentic spices',
    brand: 'Haldiram’s',
    category_id: 'cat-7',
    mrp: 110,
    price: 95,
    stock_qty: 300,
    unit: '300 g',
    pack_size: '300 g',
    is_veg: true,
    delivery_mode: 'standard',
    image: 'https://picsum.photos/seed/rte-3/400/400',
    imageHint: 'dal makhani ready meal',
    tags: ['dal', 'makhani', 'ready meal', 'north indian'],
    rating: 4.5,
    rating_count: 160,
    warehouse_stock: [
      { warehouse_id: 'sultanganj', stock: 100 },
      { warehouse_id: 'bhagalpur', stock: 100 },
      { warehouse_id: 'khagaria', stock: 100 }
    ],
    variants: [{ id: 'rte-3-1', pack_size: '300 g', mrp: 110, price: 95, stock_qty: 300 }]
  },
  {
    id: 'rte-4',
    name_en: 'Poha Cup',
    name_hi: 'Poha Cup',
    description: 'Instant poha cup, just add hot water and enjoy within minutes',
    brand: 'Gits',
    category_id: 'cat-7',
    mrp: 60,
    price: 55,
    stock_qty: 400,
    unit: '80 g',
    pack_size: '80 g',
    is_veg: true,
    delivery_mode: 'standard',
    image: 'https://picsum.photos/seed/rte-4/400/400',
    imageHint: 'instant poha cup',
    tags: ['poha', 'instant', 'cup', 'breakfast'],
    rating: 4.4,
    rating_count: 130,
    warehouse_stock: [
      { warehouse_id: 'sultanganj', stock: 150 },
      { warehouse_id: 'bhagalpur', stock: 150 },
      { warehouse_id: 'khagaria', stock: 100 }
    ],
    variants: [{ id: 'rte-4-1', pack_size: '80 g', mrp: 60, price: 55, stock_qty: 400 }]
  },
  {
    id: 'rte-5',
    name_en: 'Upma Cup',
    name_hi: 'Upma Cup',
    description: 'Quick South Indian upma in ready-to-eat form',
    brand: 'MTR',
    category_id: 'cat-7',
    mrp: 65,
    price: 60,
    stock_qty: 300,
    unit: '80 g',
    pack_size: '80 g',
    is_veg: true,
    delivery_mode: 'standard',
    image: 'https://picsum.photos/seed/rte-5/400/400',
    imageHint: 'upma cup',
    tags: ['upma', 'south indian', 'instant'],
    rating: 4.5,
    rating_count: 110,
    warehouse_stock: [
      { warehouse_id: 'sultanganj', stock: 120 },
      { warehouse_id: 'bhagalpur', stock: 100 },
      { warehouse_id: 'khagaria', stock: 80 }
    ],
    variants: [{ id: 'rte-5-1', pack_size: '80 g', mrp: 65, price: 60, stock_qty: 300 }]
  },
  {
    id: 'rte-6',
    name_en: 'Rajma Chawal Pack',
    name_hi: 'Rajma Chawal Pack',
    description: 'Ready-to-eat North Indian meal of Rajma and rice',
    brand: 'Haldiram’s',
    category_id: 'cat-7',
    mrp: 130,
    price: 120,
    stock_qty: 200,
    unit: '300 g',
    pack_size: '300 g',
    is_veg: true,
    delivery_mode: 'standard',
    image: 'https://picsum.photos/seed/rte-6/400/400',
    imageHint: 'rajma chawal ready meal',
    tags: ['rajma', 'chawal', 'ready meal'],
    rating: 4.6,
    rating_count: 140,
    warehouse_stock: [
      { warehouse_id: 'sultanganj', stock: 80 },
      { warehouse_id: 'bhagalpur', stock: 60 },
      { warehouse_id: 'khagaria', stock: 60 }
    ],
    variants: [{ id: 'rte-6-1', pack_size: '300 g', mrp: 130, price: 120, stock_qty: 200 }]
  },
  {
    id: 'rte-7',
    name_en: 'Maggi 2-Minute Noodles',
    name_hi: 'Maggi Noodles',
    description: 'Instant noodles with masala taste loved by everyone',
    brand: 'Maggi',
    category_id: 'cat-7',
    mrp: 15,
    price: 14,
    stock_qty: 1000,
    unit: '70 g',
    pack_size: '70 g',
    is_veg: true,
    delivery_mode: 'standard',
    image: 'https://picsum.photos/seed/rte-7/400/400',
    imageHint: 'maggi noodles',
    tags: ['noodles', 'instant', 'maggi'],
    rating: 4.9,
    rating_count: 1000,
    warehouse_stock: [
      { warehouse_id: 'sultanganj', stock: 400 },
      { warehouse_id: 'bhagalpur', stock: 300 },
      { warehouse_id: 'khagaria', stock: 300 }
    ],
    variants: [{ id: 'rte-7-1', pack_size: '70 g', mrp: 15, price: 14, stock_qty: 1000 }]
  },
  {
    id: 'rte-8',
    name_en: 'Instant Pasta Cup',
    name_hi: 'Instant Pasta Cup',
    description: 'Creamy cheese pasta cup, ready in minutes',
    brand: 'Knorr',
    category_id: 'cat-7',
    mrp: 80,
    price: 70,
    stock_qty: 250,
    unit: '90 g',
    pack_size: '90 g',
    is_veg: true,
    delivery_mode: 'standard',
    image: 'https://picsum.photos/seed/rte-8/400/400',
    imageHint: 'instant pasta cup',
    tags: ['pasta', 'instant', 'cup', 'snack'],
    rating: 4.6,
    rating_count: 200,
    warehouse_stock: [
      { warehouse_id: 'sultanganj', stock: 100 },
      { warehouse_id: 'bhagalpur', stock: 80 },
      { warehouse_id: 'khagaria', stock: 70 }
    ],
    variants: [{ id: 'rte-8-1', pack_size: '90 g', mrp: 80, price: 70, stock_qty: 250 }]
  },
  {
    id: 'rte-9',
    name_en: 'Kadhi Chawal Bowl',
    name_hi: 'Kadhi Chawal Bowl',
    description: 'Traditional kadhi chawal in ready-to-eat bowl pack',
    brand: 'Gits',
    category_id: 'cat-7',
    mrp: 120,
    price: 110,
    stock_qty: 150,
    unit: '300 g',
    pack_size: '300 g',
    is_veg: true,
    delivery_mode: 'standard',
    image: 'https://picsum.photos/seed/rte-9/400/400',
    imageHint: 'kadhi chawal ready meal',
    tags: ['kadhi', 'chawal', 'ready meal'],
    rating: 4.5,
    rating_count: 130,
    warehouse_stock: [
      { warehouse_id: 'sultanganj', stock: 50 },
      { warehouse_id: 'bhagalpur', stock: 50 },
      { warehouse_id: 'khagaria', stock: 50 }
    ],
    variants: [{ id: 'rte-9-1', pack_size: '300 g', mrp: 120, price: 110, stock_qty: 150 }]
  },
  {
    id: 'rte-10',
    name_en: 'Pulao Bowl',
    name_hi: 'Pulao Bowl',
    description: 'Flavored ready-to-eat vegetable pulao in bowl pack',
    brand: 'Haldiram’s',
    category_id: 'cat-7',
    mrp: 125,
    price: 115,
    stock_qty: 150,
    unit: '300 g',
    pack_size: '300 g',
    is_veg: true,
    delivery_mode: 'standard',
    image: 'https://picsum.photos/seed/rte-10/400/400',
    imageHint: 'pulao bowl',
    tags: ['pulao', 'rice', 'ready meal'],
    rating: 4.6,
    rating_count: 150,
    warehouse_stock: [
      { warehouse_id: 'sultanganj', stock: 50 },
      { warehouse_id: 'bhagalpur', stock: 50 },
      { warehouse_id: 'khagaria', stock: 50 }
    ],
    variants: [{ id: 'rte-10-1', pack_size: '300 g', mrp: 125, price: 115, stock_qty: 150 }]
  },
  // 5 more items can be simple snacks, wraps, soups etc.
  {
    id: 'rte-11',
    name_en: 'Instant Soup - Tomato',
    name_hi: 'Tamatar Soup',
    description: 'Hot and tasty tomato soup, ready in 2 minutes',
    brand: 'Knorr',
    category_id: 'cat-7',
    mrp: 30,
    price: 25,
    stock_qty: 400,
    unit: '20 g',
    pack_size: '20 g',
    is_veg: true,
    delivery_mode: 'standard',
    image: 'https://picsum.photos/seed/rte-11/400/400',
    imageHint: 'tomato soup packet',
    tags: ['soup', 'instant', 'tomato'],
    rating: 4.4,
    rating_count: 200,
    warehouse_stock: [
      { warehouse_id: 'sultanganj', stock: 150 },
      { warehouse_id: 'bhagalpur', stock: 150 },
      { warehouse_id: 'khagaria', stock: 100 }
    ],
    variants: [{ id: 'rte-11-1', pack_size: '20 g', mrp: 30, price: 25, stock_qty: 400 }]
  },
  {
    id: 'rte-12',
    name_en: 'Cup Noodles - Chicken Flavor',
    name_hi: 'Cup Noodles - Chicken Flavor',
    description: 'Ready-to-eat chicken flavor cup noodles',
    brand: 'Yippee',
    category_id: 'cat-7',
    mrp: 60,
    price: 55,
    stock_qty: 300,
    unit: '70 g',
    pack_size: '70 g',
    is_veg: false,
    delivery_mode: 'standard',
    image: 'https://picsum.photos/seed/rte-12/400/400',
    imageHint: 'cup noodles chicken flavor',
    tags: ['noodles', 'cup', 'instant'],
    rating: 4.7,
    rating_count: 180,
    warehouse_stock: [
      { warehouse_id: 'sultanganj', stock: 100 },
      { warehouse_id: 'bhagalpur', stock: 100 },
      { warehouse_id: 'khagaria', stock: 100 }
    ],
    variants: [{ id: 'rte-12-1', pack_size: '70 g', mrp: 60, price: 55, stock_qty: 300 }]
  },
  {
    id: 'rte-13',
    name_en: 'Pav Bhaji Bowl',
    name_hi: 'Pav Bhaji Bowl',
    description: 'Mumbai style pav bhaji in ready-to-eat pack',
    brand: 'Gits',
    category_id: 'cat-7',
    mrp: 110,
    price: 100,
    stock_qty: 180,
    unit: '300 g',
    pack_size: '300 g',
    is_veg: true,
    delivery_mode: 'standard',
    image: 'https://picsum.photos/seed/rte-13/400/400',
    imageHint: 'pav bhaji ready meal',
    tags: ['pav bhaji', 'ready meal', 'snack'],
    rating: 4.6,
    rating_count: 150,
    warehouse_stock: [
      { warehouse_id: 'sultanganj', stock: 60 },
      { warehouse_id: 'bhagalpur', stock: 60 },
      { warehouse_id: 'khagaria', stock: 60 }
    ],
    variants: [{ id: 'rte-13-1', pack_size: '300 g', mrp: 110, price: 100, stock_qty: 180 }]
  },
  {
    id: 'rte-14',
    name_en: 'Veg Manchurian Bowl',
    name_hi: 'Veg Manchurian Bowl',
    description: 'Ready-to-eat Chinese style veg manchurian meal',
    brand: 'FreshFeast',
    category_id: 'cat-7',
    mrp: 130,
    price: 120,
    stock_qty: 150,
    unit: '300 g',
    pack_size: '300 g',
    is_veg: true,
    delivery_mode: 'standard',
    image: 'https://picsum.photos/seed/rte-14/400/400',
    imageHint: 'veg manchurian bowl',
    tags: ['manchurian', 'chinese', 'ready meal'],
    rating: 4.5,
    rating_count: 100,
    warehouse_stock: [
      { warehouse_id: 'sultanganj', stock: 50 },
      { warehouse_id: 'bhagalpur', stock: 50 },
      { warehouse_id: 'khagaria', stock: 50 }
    ],
    variants: [{ id: 'rte-14-1', pack_size: '300 g', mrp: 130, price: 120, stock_qty: 150 }]
  },
  {
    id: 'rte-15',
    name_en: 'Idli Sambar Ready Meal',
    name_hi: 'Idli Sambar Ready Meal',
    description: 'South Indian style idli with sambar ready to heat and eat',
    brand: 'MTR',
    category_id: 'cat-7',
    mrp: 100,
    price: 90,
    stock_qty: 200,
    unit: '250 g',
    pack_size: '250 g',
    is_veg: true,
    delivery_mode: 'standard',
    image: 'https://picsum.photos/seed/rte-15/400/400',
    imageHint: 'idli sambar ready meal',
    tags: ['idli', 'sambar', 'south indian', 'ready meal'],
    rating: 4.7,
    rating_count: 180,
    warehouse_stock: [
      { warehouse_id: 'sultanganj', stock: 70 },
      { warehouse_id: 'bhagalpur', stock: 70 },
      { warehouse_id: 'khagaria', stock: 60 }
    ],
    variants: [{ id: 'rte-15-1', pack_size: '250 g', mrp: 100, price: 90, stock_qty: 200 }]
  }
];
