import { Product } from '../../types';

export const RICE_PRODUCTS: Product[] = [
  {
    id: 'rice-1',
    name_en: 'India Gate Basmati Rice',
    name_hi: 'India Gate Basmati Rice',
    description: 'Premium long grain basmati rice',
    brand: 'India Gate',
    category_id: 'cat-4',
    mrp: 120,
    price: 110,
    stock_qty: 100,
    unit: 'kg',
    pack_size: '5 kg',
    is_veg: true,
    delivery_mode: 'standard',
    image: 'https://picsum.photos/seed/rice-1/400/400',
    imageHint: 'basmati rice',
    tags: ['rice', 'basmati', 'premium', 'long grain'],
    rating: 4.6,
    rating_count: 200,
    warehouse_stock: [
      { warehouse_id: 'sultanganj', stock: 40 },
      { warehouse_id: 'bhagalpur', stock: 0 },
      { warehouse_id: 'khagaria', stock: 0 }
    ],
    variants: [
      { id: 'rice-1-1', pack_size: '1 kg', mrp: 130, price: 120, stock_qty: 50 },
      { id: 'rice-1-2', pack_size: '5 kg', mrp: 640, price: 590, stock_qty: 50 },
    ]
  },
  {
    id: 'rice-2',
    name_en: 'Sona Masoori Rice',
    name_hi: 'Sona Masoori Rice',
    description: 'Medium grain sona masoori rice',
    brand: 'Local Mill',
    category_id: 'cat-4',
    mrp: 60,
    price: 55,
    stock_qty: 150,
    unit: 'kg',
    pack_size: '5 kg',
    is_veg: true,
    delivery_mode: 'standard',
    image: 'https://picsum.photos/seed/rice-2/400/400',
    imageHint: 'sona masoori',
    tags: ['rice', 'sona masoori', 'medium grain'],
    rating: 4.4,
    rating_count: 180,
    warehouse_stock: [
      { warehouse_id: 'sultanganj', stock: 60 },
      { warehouse_id: 'bhagalpur', stock: 0 },
      { warehouse_id: 'khagaria', stock: 0 }
    ],
    variants: [
        { id: 'rice-2-1', pack_size: '5 kg', mrp: 300, price: 275, stock_qty: 80 },
        { id: 'rice-2-2', pack_size: '10 kg', mrp: 580, price: 540, stock_qty: 70 },
    ]
  },
  {
    id: 'rice-3',
    name_en: 'Organic Harvest Brown Rice',
    name_hi: 'Organic Harvest Brown Rice',
    description: 'Healthy brown rice with bran',
    brand: 'Organic Harvest',
    category_id: 'cat-4',
    mrp: 90,
    price: 85,
    stock_qty: 80,
    unit: 'kg',
    pack_size: '2 kg',
    is_veg: true,
    delivery_mode: 'standard',
    image: 'https://picsum.photos/seed/rice-3/400/400',
    imageHint: 'brown rice',
    tags: ['rice', 'brown', 'healthy', 'organic'],
    rating: 4.3,
    rating_count: 120,
    warehouse_stock: [
      { warehouse_id: 'sultanganj', stock: 35 },
      { warehouse_id: 'bhagalpur', stock: 0 },
      { warehouse_id: 'khagaria', stock: 0 }
    ],
    variants: [
      { id: 'rice-3-1', pack_size: '1 kg', mrp: 90, price: 85, stock_qty: 40 },
      { id: 'rice-3-2', pack_size: '2 kg', mrp: 175, price: 165, stock_qty: 40 },
    ]
  },
  {
    id: 'rice-4',
    name_en: 'Daawat Rice',
    name_hi: 'Daawat Rice',
    description: 'Basmati rice with cumin seeds',
    brand: 'Daawat',
    category_id: 'cat-4',
    mrp: 130,
    price: 120,
    stock_qty: 60,
    unit: 'kg',
    pack_size: '1 kg',
    is_veg: true,
    delivery_mode: 'standard',
    image: 'https://picsum.photos/seed/rice-4/400/400',
    imageHint: 'jeera rice',
    tags: ['rice', 'basmati', 'jeera', 'cumin'],
    rating: 4.5,
    rating_count: 150,
    warehouse_stock: [
      { warehouse_id: 'sultanganj', stock: 25 },
      { warehouse_id: 'bhagalpur', stock: 20 },
      { warehouse_id: 'khagaria', stock: 15 }
    ],
    variants: [
        { id: 'rice-4-1', pack_size: '1 kg', mrp: 130, price: 120, stock_qty: 60 },
    ]
  },
  {
    id: 'rice-5',
    name_en: 'Katarni Rice',
    name_hi: 'Katarni Chawal',
    description: 'Special rice for pulao',
    brand: 'Local Mill',
    category_id: 'cat-4',
    mrp: 70,
    price: 65,
    stock_qty: 90,
    unit: 'kg',
    pack_size: '5 kg',
    is_veg: true,
    delivery_mode: 'standard',
    image: 'https://picsum.photos/seed/rice-5/400/400',
    imageHint: 'pulao rice',
    tags: ['rice', 'pulao', 'special'],
    rating: 4.2,
    rating_count: 110,
    warehouse_stock: [
      { warehouse_id: 'sultanganj', stock: 40 },
      { warehouse_id: 'bhagalpur', stock: 0 },
      { warehouse_id: 'khagaria', stock: 0 }
    ],
    variants: [
        { id: 'rice-5-1', pack_size: '5 kg', mrp: 350, price: 325, stock_qty: 90 },
    ]
  },
  {
    id: 'rice-6',
    name_en: 'Katarni Rice 10kg',
    name_hi: 'Katarni Chawal 10kg',
    description: 'Premium Katarni rice, famous in Bhagalpur region',
    brand: 'Local Mill',
    category_id: 'cat-4',
    mrp: 700,
    price: 660,
    stock_qty: 60,
    unit: 'kg',
    pack_size: '10 kg',
    is_veg: true,
    delivery_mode: 'standard',
    image: 'https://picsum.photos/seed/rice-6/400/400',
    imageHint: 'katarni rice',
    tags: ['rice', 'katarni', 'premium'],
    rating: 4.5,
    rating_count: 140,
    warehouse_stock: [
      { warehouse_id: 'sultanganj', stock: 60 },
      { warehouse_id: 'bhagalpur', stock: 0 },
      { warehouse_id: 'khagaria', stock: 0 }
    ],
    variants: [
        { id: 'rice-6-1', pack_size: '10 kg', mrp: 700, price: 660, stock_qty: 60 },
    ]
  },
  {
    id: 'rice-7',
    name_en: 'Basmati Rice 5kg',
    name_hi: 'Basmati Chawal 5kg',
    description: 'Long grain aromatic basmati rice',
    brand: 'Local Mill',
    category_id: 'cat-4',
    mrp: 500,
    price: 470,
    stock_qty: 80,
    unit: 'kg',
    pack_size: '5 kg',
    is_veg: true,
    delivery_mode: 'standard',
    image: 'https://picsum.photos/seed/rice-7/400/400',
    imageHint: 'basmati rice',
    tags: ['rice', 'basmati', 'aromatic'],
    rating: 4.6,
    rating_count: 200,
    warehouse_stock: [
      { warehouse_id: 'sultanganj', stock: 80 },
      { warehouse_id: 'bhagalpur', stock: 0 },
      { warehouse_id: 'khagaria', stock: 0 }
    ],
    variants: [
        { id: 'rice-7-1', pack_size: '5 kg', mrp: 500, price: 470, stock_qty: 80 },
    ]
  },
  {
    id: 'rice-8',
    name_en: 'Basmati Rice 25kg',
    name_hi: 'Basmati Chawal 25kg',
    description: 'Premium basmati rice bulk pack',
    brand: 'Local Mill',
    category_id: 'cat-4',
    mrp: 2500,
    price: 2350,
    stock_qty: 40,
    unit: 'kg',
    pack_size: '25 kg',
    is_veg: true,
    delivery_mode: 'standard',
    image: 'https://picsum.photos/seed/rice-8/400/400',
    imageHint: 'basmati rice bulk',
    tags: ['rice', 'basmati', 'bulk'],
    rating: 4.7,
    rating_count: 320,
    warehouse_stock: [
      { warehouse_id: 'sultanganj', stock: 40 },
      { warehouse_id: 'bhagalpur', stock: 0 },
      { warehouse_id: 'khagaria', stock: 0 }
    ],
    variants: [
        { id: 'rice-8-1', pack_size: '25 kg', mrp: 2500, price: 2350, stock_qty: 40 },
    ]
  },
  {
    id: 'rice-9',
    name_en: 'Sonachur Rice 10kg',
    name_hi: 'Sonachur Chawal 10kg',
    description: 'Fine grain Sonachur rice, soft texture',
    brand: 'Local Mill',
    category_id: 'cat-4',
    mrp: 550,
    price: 510,
    stock_qty: 75,
    unit: 'kg',
    pack_size: '10 kg',
    is_veg: true,
    delivery_mode: 'standard',
    image: 'https://picsum.photos/seed/rice-9/400/400',
    imageHint: 'sonachur rice',
    tags: ['rice', 'sonachur', 'fine grain'],
    rating: 4.3,
    rating_count: 100,
    warehouse_stock: [
      { warehouse_id: 'sultanganj', stock: 75 },
      { warehouse_id: 'bhagalpur', stock: 0 },
      { warehouse_id: 'khagaria', stock: 0 }
    ],
    variants: [
        { id: 'rice-9-1', pack_size: '10 kg', mrp: 550, price: 510, stock_qty: 75 },
    ]
  },
  {
    id: 'rice-10',
    name_en: 'Swarna Rice 25kg',
    name_hi: 'Swarna Chawal 25kg',
    description: 'Affordable Swarna rice for daily use',
    brand: 'Local Mill',
    category_id: 'cat-4',
    mrp: 1250,
    price: 1180,
    stock_qty: 100,
    unit: 'kg',
    pack_size: '25 kg',
    is_veg: true,
    delivery_mode: 'standard',
    image: 'https://picsum.photos/seed/rice-10/400/400',
    imageHint: 'swarna rice',
    tags: ['rice', 'swarna', 'daily use'],
    rating: 4.1,
    rating_count: 80,
    warehouse_stock: [
      { warehouse_id: 'sultanganj', stock: 100 },
      { warehouse_id: 'bhagalpur', stock: 0 },
      { warehouse_id: 'khagaria', stock: 0 }
    ],
    variants: [
        { id: 'rice-10-1', pack_size: '25 kg', mrp: 1250, price: 1180, stock_qty: 100 },
    ]
  },
  {
    id: 'rice-11',
    name_en: 'Miniket Rice 10kg',
    name_hi: 'Miniket Chawal 10kg',
    description: 'Light Miniket rice, soft texture',
    brand: 'Local Mill',
    category_id: 'cat-4',
    mrp: 600,
    price: 560,
    stock_qty: 70,
    unit: 'kg',
    pack_size: '10 kg',
    is_veg: true,
    delivery_mode: 'standard',
    image: 'https://picsum.photos/seed/rice-11/400/400',
    imageHint: 'miniket rice',
    tags: ['rice', 'miniket', 'soft'],
    rating: 4.2,
    rating_count: 95,
    warehouse_stock: [
      { warehouse_id: 'sultanganj', stock: 70 },
      { warehouse_id: 'bhagalpur', stock: 0 },
      { warehouse_id: 'khagaria', stock: 0 }
    ],
    variants: [
        { id: 'rice-11-1', pack_size: '10 kg', mrp: 600, price: 560, stock_qty: 70 },
    ]
  },
  {
    id: 'rice-12',
    name_en: 'Sita Rice 5kg',
    name_hi: 'Sita Chawal 5kg',
    description: 'Local Sita rice, perfect for daily meals',
    brand: 'Local Mill',
    category_id: 'cat-4',
    mrp: 300,
    price: 280,
    stock_qty: 85,
    unit: 'kg',
    pack_size: '5 kg',
    is_veg: true,
    delivery_mode: 'standard',
    image: 'https://picsum.photos/seed/rice-12/400/400',
    imageHint: 'sita rice',
    tags: ['rice', 'sita', 'daily use'],
    rating: 4.0,
    rating_count: 70,
    warehouse_stock: [
      { warehouse_id: 'sultanganj', stock: 85 },
      { warehouse_id: 'bhagalpur', stock: 0 },
      { warehouse_id: 'khagaria', stock: 0 }
    ],
    variants: [
        { id: 'rice-12-1', pack_size: '5 kg', mrp: 300, price: 280, stock_qty: 85 },
    ]
  },
  {
    id: 'rice-13',
    name_en: 'Katarni Rice 25kg',
    name_hi: 'Katarni Chawal 25kg',
    description: 'Premium Katarni rice bulk pack',
    brand: 'Local Mill',
    category_id: 'cat-4',
    mrp: 1750,
    price: 1650,
    stock_qty: 30,
    unit: 'kg',
    pack_size: '25 kg',
    is_veg: true,
    delivery_mode: 'standard',
    image: 'https://picsum.photos/seed/rice-13/400/400',
    imageHint: 'katarni rice bulk',
    tags: ['rice', 'katarni', 'bulk'],
    rating: 4.6,
    rating_count: 90,
    warehouse_stock: [
      { warehouse_id: 'sultanganj', stock: 30 },
      { warehouse_id: 'bhagalpur', stock: 0 },
      { warehouse_id: 'khagaria', stock: 0 }
    ],
    variants: [
        { id: 'rice-13-1', pack_size: '25 kg', mrp: 1750, price: 1650, stock_qty: 30 },
    ]
  },
  {
    id: 'rice-14',
    name_en: 'Swarna Rice 10kg',
    name_hi: 'Swarna Chawal 10kg',
    description: 'Affordable Swarna rice for regular meals',
    brand: 'Local Mill',
    category_id: 'cat-4',
    mrp: 500,
    price: 470,
    stock_qty: 95,
    unit: 'kg',
    pack_size: '10 kg',
    is_veg: true,
    delivery_mode: 'standard',
    image: 'https://picsum.photos/seed/rice-14/400/400',
    imageHint: 'swarna rice',
    tags: ['rice', 'swarna', 'affordable'],
    rating: 4.2,
    rating_count: 85,
    warehouse_stock: [
      { warehouse_id: 'sultanganj', stock: 95 },
      { warehouse_id: 'bhagalpur', stock: 0 },
      { warehouse_id: 'khagaria', stock: 0 }
    ],
    variants: [
        { id: 'rice-14-1', pack_size: '10 kg', mrp: 500, price: 470, stock_qty: 95 },
    ]
  },
  {
    id: 'rice-15',
    name_en: 'Sonachur Rice 5kg',
    name_hi: 'Sonachur Chawal 5kg',
    description: 'Fine grain Sonachur rice small pack',
    brand: 'Local Mill',
    category_id: 'cat-4',
    mrp: 280,
    price: 260,
    stock_qty: 60,
    unit: 'kg',
    pack_size: '5 kg',
    is_veg: true,
    delivery_mode: 'standard',
    image: 'https://picsum.photos/seed/rice-15/400/400',
    imageHint: 'sonachur rice',
    tags: ['rice', 'sonachur', 'fine grain'],
    rating: 4.1,
    rating_count: 60,
    warehouse_stock: [
      { warehouse_id: 'sultanganj', stock: 60 },
      { warehouse_id: 'bhagalpur', stock: 0 },
      { warehouse_id: 'khagaria', stock: 0 }
    ],
    variants: [
        { id: 'rice-15-1', pack_size: '5 kg', mrp: 280, price: 260, stock_qty: 60 },
    ]
  }
];
