
import { Product } from '../../types';

export const SPICES_PRODUCTS: Product[] = [
  {
    id: 'spice-1',
    name_en: 'Turmeric Powder',
    name_hi: 'Haldi Powder',
    description: 'Pure turmeric powder with strong aroma and natural color',
    brand: 'Local Farm',
    category_id: 'cat-4',
    mrp: 70,
    price: 60,
    stock_qty: 200,
    unit: '100 g',
    pack_size: '100 g',
    is_veg: true,
    delivery_mode: 'standard',
    image: 'https://picsum.photos/seed/spice-1/400/400',
    imageHint: 'turmeric powder',
    tags: ['spice', 'haldi', 'turmeric', 'powder'],
    rating: 4.5,
    rating_count: 180,
    warehouse_stock: [
      { warehouse_id: 'sultanganj', stock: 70 },
      { warehouse_id: 'bhagalpur', stock: 0 },
      { warehouse_id: 'khagaria', stock: 0 }
    ]
  },
  {
    id: 'spice-2',
    name_en: 'Red Chilli Powder',
    name_hi: 'Lal Mirch Powder',
    description: 'Hot and fresh red chilli powder for daily cooking',
    brand: 'Bhagalpur Masala',
    category_id: 'cat-4',
    mrp: 90,
    price: 80,
    stock_qty: 180,
    unit: '100 g',
    pack_size: '100 g',
    is_veg: true,
    delivery_mode: 'standard',
    image: 'https://picsum.photos/seed/spice-2/400/400',
    imageHint: 'red chilli powder',
    tags: ['spice', 'lal mirch', 'chilli'],
    rating: 4.4,
    rating_count: 160,
    warehouse_stock: [
      { warehouse_id: 'sultanganj', stock: 60 },
      { warehouse_id: 'bhagalpur', stock: 0 },
      { warehouse_id: 'khagaria', stock: 0 }
    ]
  },
  {
    id: 'spice-3',
    name_en: 'Coriander Powder',
    name_hi: 'Dhania Powder',
    description: 'Aromatic coriander powder for authentic flavor',
    brand: 'Desi Masale',
    category_id: 'cat-4',
    mrp: 75,
    price: 68,
    stock_qty: 150,
    unit: '100 g',
    pack_size: '100 g',
    is_veg: true,
    delivery_mode: 'standard',
    image: 'https://picsum.photos/seed/spice-3/400/400',
    imageHint: 'coriander powder',
    tags: ['spice', 'dhania', 'coriander'],
    rating: 4.3,
    rating_count: 120,
    warehouse_stock: [
      { warehouse_id: 'sultanganj', stock: 45 },
      { warehouse_id: 'bhagalpur', stock: 0 },
      { warehouse_id: 'khagaria', stock: 0 }
    ]
  },
  {
    id: 'spice-4',
    name_en: 'Cumin Seeds',
    name_hi: 'Jeera',
    description: 'Whole cumin seeds, aromatic and fresh',
    brand: 'Local Farm',
    category_id: 'cat-4',
    mrp: 110,
    price: 100,
    stock_qty: 140,
    unit: '100 g',
    pack_size: '100 g',
    is_veg: true,
    delivery_mode: 'standard',
    image: 'https://picsum.photos/seed/spice-4/400/400',
    imageHint: 'cumin seeds',
    tags: ['spice', 'jeera', 'cumin'],
    rating: 4.4,
    rating_count: 130,
    warehouse_stock: [
      { warehouse_id: 'sultanganj', stock: 40 },
      { warehouse_id: 'bhagalpur', stock: 0 },
      { warehouse_id: 'khagaria', stock: 0 }
    ]
  },
  {
    id: 'spice-5',
    name_en: 'Black Pepper (Whole)',
    name_hi: 'Kali Mirch',
    description: 'Premium whole black pepper for grinding fresh',
    brand: 'Everest',
    category_id: 'cat-4',
    mrp: 180,
    price: 160,
    stock_qty: 90,
    unit: '100 g',
    pack_size: '100 g',
    is_veg: true,
    delivery_mode: 'standard',
    image: 'https://picsum.photos/seed/spice-5/400/400',
    imageHint: 'black pepper',
    tags: ['spice', 'kali mirch', 'pepper'],
    rating: 4.6,
    rating_count: 140,
    warehouse_stock: [
      { warehouse_id: 'sultanganj', stock: 25 },
      { warehouse_id: 'bhagalpur', stock: 0 },
      { warehouse_id: 'khagaria', stock: 0 }
    ]
  },
  {
    id: 'spice-6',
    name_en: 'Mustard Seeds',
    name_hi: 'Sarson Dana',
    description: 'Yellow mustard seeds for tadka and pickles',
    brand: 'Bhagalpur Oil Mills',
    category_id: 'cat-4',
    mrp: 85,
    price: 78,
    stock_qty: 160,
    unit: '100 g',
    pack_size: '100 g',
    is_veg: true,
    delivery_mode: 'standard',
    image: 'https://picsum.photos/seed/spice-6/400/400',
    imageHint: 'mustard seeds',
    tags: ['spice', 'sarson', 'mustard'],
    rating: 4.2,
    rating_count: 100,
    warehouse_stock: [
      { warehouse_id: 'sultanganj', stock: 50 },
      { warehouse_id: 'bhagalpur', stock: 0 },
      { warehouse_id: 'khagaria', stock: 0 }
    ]
  },
  {
    id: 'spice-7',
    name_en: 'Garam Masala',
    name_hi: 'Garam Masala',
    description: 'Household garam masala blend for rich aroma',
    brand: 'Rajdhani',
    category_id: 'cat-4',
    mrp: 120,
    price: 110,
    stock_qty: 130,
    unit: '100 g',
    pack_size: '100 g',
    is_veg: true,
    delivery_mode: 'standard',
    image: 'https://picsum.photos/seed/spice-7/400/400',
    imageHint: 'garam masala',
    tags: ['spice', 'garam masala', 'blend'],
    rating: 4.5,
    rating_count: 170,
    warehouse_stock: [
      { warehouse_id: 'sultanganj', stock: 40 },
      { warehouse_id: 'bhagalpur', stock: 0 },
      { warehouse_id: 'khagaria', stock: 0 }
    ]
  },
  {
    id: 'spice-8',
    name_en: 'Coriander Seeds (Whole)',
    name_hi: 'Dhania Dana',
    description: 'Whole coriander seeds for roasting and grinding',
    brand: 'Desi Grains',
    category_id: 'cat-4',
    mrp: 95,
    price: 88,
    stock_qty: 120,
    unit: '100 g',
    pack_size: '100 g',
    is_veg: true,
    delivery_mode: 'standard',
    image: 'https://picsum.photos/seed/spice-8/400/400',
    imageHint: 'coriander seeds',
    tags: ['spice', 'dhania dana', 'whole seeds'],
    rating: 4.3,
    rating_count: 90,
    warehouse_stock: [
      { warehouse_id: 'sultanganj', stock: 35 },
      { warehouse_id: 'bhagalpur', stock: 0 },
      { warehouse_id: 'khagaria', stock: 0 }
    ]
  },
  {
    id: 'spice-9',
    name_en: 'Fennel Seeds',
    name_hi: 'Saunf',
    description: 'Sweet fennel seeds for digestion and flavor',
    brand: 'Local Farm',
    category_id: 'cat-4',
    mrp: 100,
    price: 92,
    stock_qty: 110,
    unit: '100 g',
    pack_size: '100 g',
    is_veg: true,
    delivery_mode: 'standard',
    image: 'https://picsum.photos/seed/spice-9/400/400',
    imageHint: 'fennel seeds',
    tags: ['spice', 'saunf', 'fennel'],
    rating: 4.4,
    rating_count: 95,
    warehouse_stock: [
      { warehouse_id: 'sultanganj', stock: 30 },
      { warehouse_id: 'bhagalpur', stock: 0 },
      { warehouse_id: 'khagaria', stock: 0 }
    ]
  },
  {
    id: 'spice-10',
    name_en: 'Fenugreek Seeds',
    name_hi: 'Methi Dana',
    description: 'Bitter-sweet fenugreek seeds for masalas and pickles',
    brand: 'AgroFresh',
    category_id: 'cat-4',
    mrp: 95,
    price: 88,
    stock_qty: 100,
    unit: '100 g',
    pack_size: '100 g',
    is_veg: true,
    delivery_mode: 'standard',
    image: 'https://picsum.photos/seed/spice-10/400/400',
    imageHint: 'fenugreek seeds',
    tags: ['spice', 'methi', 'fenugreek'],
    rating: 4.1,
    rating_count: 75,
    warehouse_stock: [
      { warehouse_id: 'sultanganj', stock: 25 },
      { warehouse_id: 'bhagalpur', stock: 0 },
      { warehouse_id: 'khagaria', stock: 0 }
    ]
  },
  {
    id: 'spice-11',
    name_en: 'Asafoetida (Hing)',
    name_hi: 'Hing Powder',
    description: 'Pure hing powder for authentic tadka flavor',
    brand: 'Desi Spices',
    category_id: 'cat-4',
    mrp: 140,
    price: 130,
    stock_qty: 80,
    unit: '50 g',
    pack_size: '50 g',
    is_veg: true,
    delivery_mode: 'standard',
    image: 'https://picsum.photos/seed/spice-11/400/400',
    imageHint: 'hing powder',
    tags: ['spice', 'hing', 'asafoetida'],
    rating: 4.2,
    rating_count: 65,
    warehouse_stock: [
      { warehouse_id: 'sultanganj', stock: 20 },
      { warehouse_id: 'bhagalpur', stock: 0 },
      { warehouse_id: 'khagaria', stock: 0 }
    ]
  },
  {
    id: 'spice-12',
    name_en: 'Cloves',
    name_hi: 'Laung',
    description: 'Aromatic whole cloves for masala and garam masala blends',
    brand: 'Heritage Spices',
    category_id: 'cat-4',
    mrp: 220,
    price: 200,
    stock_qty: 60,
    unit: '50 g',
    pack_size: '50 g',
    is_veg: true,
    delivery_mode: 'standard',
    image: 'https://picsum.photos/seed/spice-12/400/400',
    imageHint: 'cloves',
    tags: ['spice', 'laung', 'cloves'],
    rating: 4.5,
    rating_count: 70,
    warehouse_stock: [
      { warehouse_id: 'sultanganj', stock: 15 },
      { warehouse_id: 'bhagalpur', stock: 0 },
      { warehouse_id: 'khagaria', stock: 0 }
    ]
  },
  {
    id: 'spice-13',
    name_en: 'Cinnamon Sticks',
    name_hi: 'Dalchini',
    description: 'High-quality cinnamon sticks for teas and masala',
    brand: 'Cinnamon Co',
    category_id: 'cat-4',
    mrp: 190,
    price: 175,
    stock_qty: 70,
    unit: '50 g',
    pack_size: '50 g',
    is_veg: true,
    delivery_mode: 'standard',
    image: 'https://picsum.photos/seed/spice-13/400/400',
    imageHint: 'cinnamon sticks',
    tags: ['spice', 'dalchini', 'cinnamon'],
    rating: 4.4,
    rating_count: 85,
    warehouse_stock: [
      { warehouse_id: 'sultanganj', stock: 20 },
      { warehouse_id: 'bhagalpur', stock: 0 },
      { warehouse_id: 'khagaria', stock: 0 }
    ]
  },
  {
    id: 'spice-14',
    name_en: 'Green Cardamom',
    name_hi: 'Elaichi',
    description: 'Premium green cardamom pods for desserts and chai',
    brand: 'Royal Spices',
    category_id: 'cat-4',
    mrp: 450,
    price: 420,
    stock_qty: 40,
    unit: '25 g',
    pack_size: '25 g',
    is_veg: true,
    delivery_mode: 'standard',
    image: 'https://picsum.photos/seed/spice-14/400/400',
    imageHint: 'green cardamom',
    tags: ['spice', 'elaichi', 'cardamom'],
    rating: 4.7,
    rating_count: 95,
    warehouse_stock: [
      { warehouse_id: 'sultanganj', stock: 10 },
      { warehouse_id: 'bhagalpur', stock: 0 },
      { warehouse_id: 'khagaria', stock: 0 }
    ]
  },
  {
    id: 'spice-15',
    name_en: 'Bay Leaves',
    name_hi: 'Tej Patta',
    description: 'Dried bay leaves for curries and biryanis',
    brand: 'Local Farm',
    category_id: 'cat-4',
    mrp: 80,
    price: 74,
    stock_qty: 120,
    unit: '20 g',
    pack_size: '20 g',
    is_veg: true,
    delivery_mode: 'standard',
    image: 'https://picsum.photos/seed/spice-15/400/400',
    imageHint: 'bay leaves',
    tags: ['spice', 'tej patta', 'bay leaves'],
    rating: 4.1,
    rating_count: 60,
    warehouse_stock: [
      { warehouse_id: 'sultanganj', stock: 35 },
      { warehouse_id: 'bhagalpur', stock: 0 },
      { warehouse_id: 'khagaria', stock: 0 }
    ]
  },
  {
    id: 'spice-16',
    name_en: 'Black Cardamom',
    name_hi: 'Badi Elaichi',
    description: 'Smoky black cardamom for rich gravies',
    brand: 'Desi Spices',
    category_id: 'cat-4',
    mrp: 240,
    price: 220,
    stock_qty: 45,
    unit: '25 g',
    pack_size: '25 g',
    is_veg: true,
    delivery_mode: 'standard',
    image: 'https://picsum.photos/seed/spice-16/400/400',
    imageHint: 'black cardamom',
    tags: ['spice', 'badi elaichi', 'black cardamom'],
    rating: 4.3,
    rating_count: 50,
    warehouse_stock: [
      { warehouse_id: 'sultanganj', stock: 12 },
      { warehouse_id: 'bhagalpur', stock: 0 },
      { warehouse_id: 'khagaria', stock: 0 }
    ]
  },
  {
    id: 'spice-17',
    name_en: 'Carom Seeds',
    name_hi: 'Ajwain',
    description: 'Ajwain seeds for digestion and tadka',
    brand: 'AgroFresh',
    category_id: 'cat-4',
    mrp: 95,
    price: 88,
    stock_qty: 130,
    unit: '100 g',
    pack_size: '100 g',
    is_veg: true,
    delivery_mode: 'standard',
    image: 'https://picsum.photos/seed/spice-17/400/400',
    imageHint: 'carom seeds',
    tags: ['spice', 'ajwain', 'carom'],
    rating: 4.2,
    rating_count: 80,
    warehouse_stock: [
      { warehouse_id: 'sultanganj', stock: 40 },
      { warehouse_id: 'bhagalpur', stock: 0 },
      { warehouse_id: 'khagaria', stock: 0 }
    ]
  },
  {
    id: 'spice-18',
    name_en: 'Nigella Seeds',
    name_hi: 'Kalonji',
    description: 'Kalonji seeds used for pickles and parathas',
    brand: 'Local Mill',
    category_id: 'cat-4',
    mrp: 110,
    price: 100,
    stock_qty: 95,
    unit: '100 g',
    pack_size: '100 g',
    is_veg: true,
    delivery_mode: 'standard',
    image: 'https://picsum.photos/seed/spice-18/400/400',
    imageHint: 'nigella seeds',
    tags: ['spice', 'kalonji', 'nigella'],
    rating: 4.1,
    rating_count: 70,
    warehouse_stock: [
      { warehouse_id: 'sultanganj', stock: 30 },
      { warehouse_id: 'bhagalpur', stock: 0 },
      { warehouse_id: 'khagaria', stock: 0 }
    ]
  },
  {
    id: 'spice-19',
    name_en: 'White Pepper (Powder)',
    name_hi: 'Safed Mirch Powder',
    description: 'Fine white pepper powder for light sauces and soups',
    brand: 'Premium Spices',
    category_id: 'cat-4',
    mrp: 160,
    price: 150,
    stock_qty: 60,
    unit: '50 g',
    pack_size: '50 g',
    is_veg: true,
    delivery_mode: 'standard',
    image: 'https://picsum.photos/seed/spice-19/400/400',
    imageHint: 'white pepper',
    tags: ['spice', 'safed mirch', 'white pepper'],
    rating: 4.2,
    rating_count: 45,
    warehouse_stock: [
      { warehouse_id: 'sultanganj', stock: 15 },
      { warehouse_id: 'bhagalpur', stock: 0 },
      { warehouse_id: 'khagaria', stock: 0 }
    ]
  },
  {
    id: 'spice-20',
    name_en: 'Saffron',
    name_hi: 'Kesar',
    description: 'Premium saffron threads for aroma and color (small pack)',
    brand: 'Royal Saffron',
    category_id: 'cat-4',
    mrp: 1200,
    price: 1150,
    stock_qty: 12,
    unit: '1 g',
    pack_size: '1 g',
    is_veg: true,
    delivery_mode: 'standard',
    image: 'https://picsum.photos/seed/spice-20/400/400',
    imageHint: 'saffron',
    tags: ['spice', 'kesar', 'saffron'],
    rating: 4.7,
    rating_count: 30,
    warehouse_stock: [
      { warehouse_id: 'sultanganj', stock: 4 },
      { warehouse_id: 'bhagalpur', stock: 0 },
      { warehouse_id: 'khagaria', stock: 0 }
    ]
  },
  {
    id: 'spice-21',
    name_en: 'Everest Turmeric Powder 100g',
    name_hi: 'Everest Haldi Powder 100g',
    description: 'Pure turmeric powder with strong color',
    brand: 'Everest',
    category_id: 'cat-4',
    mrp: 45,
    price: 42,
    stock_qty: 60,
    unit: '100 g',
    pack_size: '100 g',
    is_veg: true,
    delivery_mode: 'standard',
    image: 'https://picsum.photos/seed/spice-21/400/400',
    imageHint: 'everest haldi',
    tags: ['turmeric', 'haldi', 'spice'],
    rating: 4.5,
    rating_count: 180,
    warehouse_stock: [
      { warehouse_id: 'sultanganj', stock: 60 },
      { warehouse_id: 'bhagalpur', stock: 0 },
      { warehouse_id: 'khagaria', stock: 0 }
    ]
  },
  {
    id: 'spice-22',
    name_en: 'MDH Deggi Mirch 200g',
    name_hi: 'MDH Deggi Mirch 200g',
    description: 'Fiery red chili powder for taste and color',
    brand: 'MDH',
    category_id: 'cat-4',
    mrp: 120,
    price: 110,
    stock_qty: 40,
    unit: '200 g',
    pack_size: '200 g',
    is_veg: true,
    delivery_mode: 'standard',
    image: 'https://picsum.photos/seed/spice-22/400/400',
    imageHint: 'mdh mirch',
    tags: ['mirch', 'chili', 'spice'],
    rating: 4.4,
    rating_count: 140,
    warehouse_stock: [
      { warehouse_id: 'sultanganj', stock: 40 },
      { warehouse_id: 'bhagalpur', stock: 0 },
      { warehouse_id: 'khagaria', stock: 0 }
    ]
  },
  {
    id: 'spice-23',
    name_en: 'Tata Sampann Coriander Powder 500g',
    name_hi: 'Tata Sampann Dhania Powder 500g',
    description: 'Fresh coriander powder for everyday cooking',
    brand: 'Tata Sampann',
    category_id: 'cat-4',
    mrp: 95,
    price: 90,
    stock_qty: 50,
    unit: '500 g',
    pack_size: '500 g',
    is_veg: true,
    delivery_mode: 'standard',
    image: 'https://picsum.photos/seed/spice-23/400/400',
    imageHint: 'tata dhania',
    tags: ['coriander', 'dhaniya', 'spice'],
    rating: 4.6,
    rating_count: 160,
    warehouse_stock: [
      { warehouse_id: 'sultanganj', stock: 50 },
      { warehouse_id: 'bhagalpur', stock: 0 },
      { warehouse_id: 'khagaria', stock: 0 }
    ]
  },
  {
    id: 'spice-24',
    name_en: 'Catch Garam Masala 100g',
    name_hi: 'Catch Garam Masala 100g',
    description: 'Blend of premium spices for Indian curries',
    brand: 'Catch Spices',
    category_id: 'cat-4',
    mrp: 80,
    price: 75,
    stock_qty: 55,
    unit: '100 g',
    pack_size: '100 g',
    is_veg: true,
    delivery_mode: 'standard',
    image: 'https://picsum.photos/seed/spice-24/400/400',
    imageHint: 'catch garam masala',
    tags: ['garam masala', 'blend', 'spice'],
    rating: 4.5,
    rating_count: 150,
    warehouse_stock: [
      { warehouse_id: 'sultanganj', stock: 55 },
      { warehouse_id: 'bhagalpur', stock: 0 },
      { warehouse_id: 'khagaria', stock: 0 }
    ]
  },
  {
    id: 'spice-25',
    name_en: 'Loose Turmeric Powder 1kg',
    name_hi: 'Loose Haldi Powder 1kg',
    description: 'Freshly ground loose turmeric powder',
    brand: 'Loose Masala',
    category_id: 'cat-4',
    mrp: 180,
    price: 160,
    stock_qty: 70,
    unit: 'kg',
    pack_size: '1 kg',
    is_veg: true,
    delivery_mode: 'standard',
    image: 'https://picsum.photos/seed/spice-25/400/400',
    imageHint: 'loose haldi',
    tags: ['turmeric', 'haldi', 'loose'],
    rating: 4.2,
    rating_count: 90,
    warehouse_stock: [
      { warehouse_id: 'sultanganj', stock: 70 },
      { warehouse_id: 'bhagalpur', stock: 0 },
      { warehouse_id: 'khagaria', stock: 0 }
    ]
  },
  {
    id: 'spice-26',
    name_en: 'Everest Chicken Masala 100g',
    name_hi: 'Everest Chicken Masala 100g',
    description: 'Perfect spice blend for chicken curry',
    brand: 'Everest',
    category_id: 'cat-4',
    mrp: 85,
    price: 80,
    stock_qty: 45,
    unit: '100 g',
    pack_size: '100 g',
    is_veg: true,
    delivery_mode: 'standard',
    image: 'https://picsum.photos/seed/spice-26/400/400',
    imageHint: 'everest chicken masala',
    tags: ['chicken masala', 'spice mix'],
    rating: 4.6,
    rating_count: 170,
    warehouse_stock: [
      { warehouse_id: 'sultanganj', stock: 45 },
      { warehouse_id: 'bhagalpur', stock: 0 },
      { warehouse_id: 'khagaria', stock: 0 }
    ]
  },
  {
    id: 'spice-27',
    name_en: 'MDH Kitchen King 200g',
    name_hi: 'MDH Kitchen King 200g',
    description: 'Multi-purpose masala for veg curries',
    brand: 'MDH',
    category_id: 'cat-4',
    mrp: 120,
    price: 115,
    stock_qty: 40,
    unit: '200 g',
    pack_size: '200 g',
    is_veg: true,
    delivery_mode: 'standard',
    image: 'https://picsum.photos/seed/spice-27/400/400',
    imageHint: 'mdh kitchen king',
    tags: ['kitchen king', 'veg curry', 'spice'],
    rating: 4.4,
    rating_count: 100,
    warehouse_stock: [
      { warehouse_id: 'sultanganj', stock: 40 },
      { warehouse_id: 'bhagalpur', stock: 0 },
      { warehouse_id: 'khagaria', stock: 0 }
    ]
  },
  {
    id: 'spice-28',
    name_en: 'Tata Sampann Chana Masala 100g',
    name_hi: 'Tata Sampann Chana Masala 100g',
    description: 'Spice mix for perfect chana curry',
    brand: 'Tata Sampann',
    category_id: 'cat-4',
    mrp: 70,
    price: 65,
    stock_qty: 60,
    unit: '100 g',
    pack_size: '100 g',
    is_veg: true,
    delivery_mode: 'standard',
    image: 'https://picsum.photos/seed/spice-28/400/400',
    imageHint: 'tata chana masala',
    tags: ['chana masala', 'spice mix'],
    rating: 4.3,
    rating_count: 95,
    warehouse_stock: [
      { warehouse_id: 'sultanganj', stock: 60 },
      { warehouse_id: 'bhagalpur', stock: 0 },
      { warehouse_id: 'khagaria', stock: 0 }
    ]
  },
  {
    id: 'spice-29',
    name_en: 'Catch Meat Masala 200g',
    name_hi: 'Catch Meat Masala 200g',
    description: 'Rich flavored masala for meat curries',
    brand: 'Catch Spices',
    category_id: 'cat-4',
    mrp: 110,
    price: 100,
    stock_qty: 35,
    unit: '200 g',
    pack_size: '200 g',
    is_veg: true,
    delivery_mode: 'standard',
    image: 'https://picsum.photos/seed/spice-29/400/400',
    imageHint: 'catch meat masala',
    tags: ['meat masala', 'spice mix'],
    rating: 4.5,
    rating_count: 80,
    warehouse_stock: [
      { warehouse_id: 'sultanganj', stock: 35 },
      { warehouse_id: 'bhagalpur', stock: 0 },
      { warehouse_id: 'khagaria', stock: 0 }
    ]
  },
  {
    id: 'spice-30',
    name_en: 'Loose Coriander Powder 500g',
    name_hi: 'Loose Dhaniya Powder 500g',
    description: 'Fresh loose coriander powder',
    brand: 'Loose Masala',
    category_id: 'cat-4',
    mrp: 70,
    price: 65,
    stock_qty: 90,
    unit: '500 g',
    pack_size: '500 g',
    is_veg: true,
    delivery_mode: 'standard',
    image: 'https://picsum.photos/seed/spice-30/400/400',
    imageHint: 'loose dhania',
    tags: ['dhaniya', 'coriander', 'loose'],
    rating: 4.1,
    rating_count: 60,
    warehouse_stock: [
      { warehouse_id: 'sultanganj', stock: 90 },
      { warehouse_id: 'bhagalpur', stock: 0 },
      { warehouse_id: 'khagaria', stock: 0 }
    ]
  },
  {
    id: 'spice-31',
    name_en: 'Loose Red Chili Powder 1kg',
    name_hi: 'Loose Mirchi Powder 1kg',
    description: 'Locally sourced spicy red chilli powder',
    brand: 'Loose Masala',
    category_id: 'cat-4',
    mrp: 320,
    price: 300,
    stock_qty: 60,
    unit: 'kg',
    pack_size: '1 kg',
    is_veg: true,
    delivery_mode: 'standard',
    image: 'https://picsum.photos/seed/spice-31/400/400',
    imageHint: 'loose red chilli',
    tags: ['red chilli', 'loose', 'spice'],
    rating: 4.2,
    rating_count: 100,
    warehouse_stock: [
      { warehouse_id: 'sultanganj', stock: 60 },
      { warehouse_id: 'bhagalpur', stock: 0 },
      { warehouse_id: 'khagaria', stock: 0 }
    ]
  },
  {
    id: 'spice-32',
    name_en: 'Everest Chicken Masala 100g',
    name_hi: 'Everest Chicken Masala 100g',
    description: 'Aromatic blend for chicken curries',
    brand: 'Everest',
    category_id: 'cat-4',
    mrp: 85,
    price: 78,
    stock_qty: 150,
    unit: '100 g',
    pack_size: '100 g',
    is_veg: true,
    delivery_mode: 'standard',
    image: 'https://picsum.photos/seed/spice-32/400/400',
    imageHint: 'everest chicken masala',
    tags: ['chicken masala', 'everest', 'spice'],
    rating: 4.5,
    rating_count: 200,
    warehouse_stock: [
      { warehouse_id: 'sultanganj', stock: 150 },
      { warehouse_id: 'bhagalpur', stock: 0 },
      { warehouse_id: 'khagaria', stock: 0 }
    ]
  },
  {
    id: 'spice-33',
    name_en: 'MDH Kitchen King 200g',
    name_hi: 'MDH Kitchen King 200g',
    description: 'Perfect spice mix for veg & non-veg dishes',
    brand: 'MDH',
    category_id: 'cat-4',
    mrp: 120,
    price: 110,
    stock_qty: 100,
    unit: '200 g',
    pack_size: '200 g',
    is_veg: true,
    delivery_mode: 'standard',
    image: 'https://picsum.photos/seed/spice-33/400/400',
    imageHint: 'mdh kitchen king',
    tags: ['kitchen king', 'mdh', 'spice'],
    rating: 4.4,
    rating_count: 150,
    warehouse_stock: [
      { warehouse_id: 'sultanganj', stock: 100 },
      { warehouse_id: 'bhagalpur', stock: 0 },
      { warehouse_id: 'khagaria', stock: 0 }
    ]
  },
  {
    id: 'spice-34',
    name_en: 'Tata Sampann Coriander Powder 500g',
    name_hi: 'Tata Sampann Dhania Powder 500g',
    description: 'High quality coriander powder',
    brand: 'Tata Sampann',
    category_id: 'cat-4',
    mrp: 160,
    price: 150,
    stock_qty: 180,
    unit: '500 g',
    pack_size: '500 g',
    is_veg: true,
    delivery_mode: 'standard',
    image: 'https://picsum.photos/seed/spice-34/400/400',
    imageHint: 'tata dhania',
    tags: ['coriander', 'tata', 'spice'],
    rating: 4.6,
    rating_count: 220,
    warehouse_stock: [
      { warehouse_id: 'sultanganj', stock: 180 },
      { warehouse_id: 'bhagalpur', stock: 0 },
      { warehouse_id: 'khagaria', stock: 0 }
    ]
  },
  {
    id: 'spice-35',
    name_en: 'Catch Turmeric Powder 200g',
    name_hi: 'Catch Haldi Powder 200g',
    description: 'Bright color haldi for daily cooking',
    brand: 'Catch Spices',
    category_id: 'cat-4',
    mrp: 70,
    price: 65,
    stock_qty: 140,
    unit: '200 g',
    pack_size: '200 g',
    is_veg: true,
    delivery_mode: 'standard',
    image: 'https://picsum.photos/seed/spice-35/400/400',
    imageHint: 'catch haldi',
    tags: ['haldi', 'turmeric', 'catch'],
    rating: 4.3,
    rating_count: 130,
    warehouse_stock: [
      { warehouse_id: 'sultanganj', stock: 140 },
      { warehouse_id: 'bhagalpur', stock: 0 },
      { warehouse_id: 'khagaria', stock: 0 }
    ]
  },
  {
    id: 'spice-36',
    name_en: 'Loose Red Chilli Powder 1kg',
    name_hi: 'Loose Mirchi Powder 1kg',
    description: 'Locally sourced spicy red chilli powder',
    brand: 'Loose Masala',
    category_id: 'cat-4',
    mrp: 320,
    price: 300,
    stock_qty: 60,
    unit: 'kg',
    pack_size: '1 kg',
    is_veg: true,
    delivery_mode: 'standard',
    image: 'https://picsum.photos/seed/spice-36/400/400',
    imageHint: 'loose red chilli',
    tags: ['red chilli', 'loose', 'spice'],
    rating: 4.2,
    rating_count: 100,
    warehouse_stock: [
      { warehouse_id: 'sultanganj', stock: 60 },
      { warehouse_id: 'bhagalpur', stock: 0 },
      { warehouse_id: 'khagaria', stock: 0 }
    ]
  },
  {
    id: 'spice-37',
    name_en: 'Everest Pav Bhaji Masala 100g',
    name_hi: 'Everest Pav Bhaji Masala 100g',
    description: 'Delicious masala mix for pav bhaji',
    brand: 'Everest',
    category_id: 'cat-4',
    mrp: 85,
    price: 78,
    stock_qty: 170,
    unit: '100 g',
    pack_size: '100 g',
    is_veg: true,
    delivery_mode: 'standard',
    image: 'https://picsum.photos/seed/spice-37/400/400',
    imageHint: 'everest pav bhaji',
    tags: ['pav bhaji', 'everest', 'spice'],
    rating: 4.7,
    rating_count: 190,
    warehouse_stock: [
      { warehouse_id: 'sultanganj', stock: 170 },
      { warehouse_id: 'bhagalpur', stock: 0 },
      { warehouse_id: 'khagaria', stock: 0 }
    ]
  },
  {
    id: 'spice-38',
    name_en: 'MDH Deggi Mirch 100g',
    name_hi: 'MDH Deggi Mirch 100g',
    description: 'Mild spicy red chilli powder blend',
    brand: 'MDH',
    category_id: 'cat-4',
    mrp: 95,
    price: 88,
    stock_qty: 130,
    unit: '100 g',
    pack_size: '100 g',
    is_veg: true,
    delivery_mode: 'standard',
    image: 'https://picsum.photos/seed/spice-38/400/400',
    imageHint: 'mdh deggi mirch',
    tags: ['deggi mirch', 'mdh', 'spice'],
    rating: 4.5,
    rating_count: 160,
    warehouse_stock: [
      { warehouse_id: 'sultanganj', stock: 130 },
      { warehouse_id: 'bhagalpur', stock: 0 },
      { warehouse_id: 'khagaria', stock: 0 }
    ]
  },
  {
    id: 'spice-39',
    name_en: 'Tata Sampann Garam Masala 100g',
    name_hi: 'Tata Sampann Garam Masala 100g',
    description: 'Rich garam masala powder with natural oils',
    brand: 'Tata Sampann',
    category_id: 'cat-4',
    mrp: 90,
    price: 82,
    stock_qty: 160,
    unit: '100 g',
    pack_size: '100 g',
    is_veg: true,
    delivery_mode: 'standard',
    image: 'https://picsum.photos/seed/spice-39/400/400',
    imageHint: 'tata garam masala',
    tags: ['garam masala', 'tata', 'spice'],
    rating: 4.6,
    rating_count: 210,
    warehouse_stock: [
      { warehouse_id: 'sultanganj', stock: 160 },
      { warehouse_id: 'bhagalpur', stock: 0 },
      { warehouse_id: 'khagaria', stock: 0 }
    ]
  },
  {
    id: 'spice-40',
    name_en: 'Catch Black Pepper Powder 50g',
    name_hi: 'Catch Kali Mirch Powder 50g',
    description: 'Strong flavored black pepper powder',
    brand: 'Catch Spices',
    category_id: 'cat-4',
    mrp: 65,
    price: 60,
    stock_qty: 140,
    unit: '50 g',
    pack_size: '50 g',
    is_veg: true,
    delivery_mode: 'standard',
    image: 'https://picsum.photos/seed/spice-40/400/400',
    imageHint: 'catch kali mirch',
    tags: ['black pepper', 'catch', 'spice'],
    rating: 4.3,
    rating_count: 120,
    warehouse_stock: [
      { warehouse_id: 'sultanganj', stock: 140 },
      { warehouse_id: 'bhagalpur', stock: 0 },
      { warehouse_id: 'khagaria', stock: 0 }
    ]
  }
];

    